// generate-cpp.mjs
// Expands the C++ typing dictionary for vibetyper by writing a broad set of
// realistic, self-contained C++ units (functions, classes, structs) across
// many topic files. The existing sample.cpp is left untouched.
//
// Each "unit" is one top-level braced block — exactly what the braces-mode
// splitter turns into a typing block. `#include` lines at the top of each
// file group into a single header block, which is fine.
//
// Run: node scripts/generate/generate-cpp.mjs

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const outDir = path.resolve(here, '../../dictionary/cpp');

const MODULES = [
  './cpp/string-math.mjs',
  './cpp/containers-validation.mjs',
  './cpp/processing-filesystem.mjs',
  './cpp/networking-formatting.mjs',
  './cpp/structures-algorithms.mjs',
  './cpp/threading-models.mjs',
  './cpp/models2-geometry.mjs',
  './cpp/encoding-extra.mjs',
];

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

function renderFile(fd) {
  const includeBlock = fd.includes.map((h) => `#include ${h}`).join('\n');
  const header = `// ${fd.file} — generated by scripts/generate/generate-cpp.mjs (do not edit by hand).
// Realistic C++ typing blocks for vibetyper: ${fd.topic}.

${includeBlock}

`;
  return header + fd.units.join('\n\n') + '\n';
}

// ---------------------------------------------------------------------------
// Sanity checks
// ---------------------------------------------------------------------------

// Brace balance check that ignores braces inside // and /* */ comments,
// double-quoted strings and char literals. Mirrors the scanner used by
// server/blockSplitter.js so a unit that passes here splits as one block.
function checkUnitBalance(unit, file, idx) {
  const lines = unit.split('\n');
  let depth = 0;
  for (const line of lines) {
    let inBlock = false;
    let i = 0;
    while (i < line.length) {
      const ch = line[i];
      const next = line[i + 1];
      if (inBlock) {
        if (ch === '*' && next === '/') {
          inBlock = false;
          i += 2;
        } else {
          i++;
        }
        continue;
      }
      if (ch === '/' && next === '/') break;
      if (ch === '/' && next === '*') {
        inBlock = true;
        i += 2;
        continue;
      }
      if (ch === '"' || ch === "'") {
        const quote = ch;
        i++;
        while (i < line.length) {
          if (line[i] === '\\') {
            i += 2;
            continue;
          }
          if (line[i] === quote) {
            i++;
            break;
          }
          i++;
        }
        continue;
      }
      if (ch === '{') depth++;
      else if (ch === '}') depth--;
      i++;
    }
    if (depth < 0) {
      throw new Error(`${file} unit #${idx} has a closing brace with nothing to open:\n${unit}`);
    }
  }
  if (depth !== 0) {
    throw new Error(`${file} unit #${idx} has unbalanced braces (depth ${depth}):\n${unit}`);
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

let totalUnits = 0;
const written = [];

for (const modPath of MODULES) {
  const mod = await import(modPath);
  for (const fd of mod.default) {
    for (let i = 0; i < fd.units.length; i++) {
      checkUnitBalance(fd.units[i], fd.file, i);
    }
    const content = renderFile(fd);
    fs.writeFileSync(path.join(outDir, fd.file), content);
    totalUnits += fd.units.length;
    written.push(fd.file);
  }
}

console.log('Wrote %d C++ dictionary files, %d units total.', written.length, totalUnits);
for (const f of written) console.log('  -', f);
