// generate-go.mjs
// Expands the Go typing dictionary for vibetyper by writing a broad set of
// realistic, self-contained Go units (functions, structs, interfaces) across
// many topic files. The existing sample.go is left untouched.
//
// Each "unit" is one top-level braced block (or a short run of top-level
// statements) — exactly what the braces-mode splitter turns into a typing block.
//
// Run: node scripts/generate/generate-go.mjs

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const outDir = path.resolve(here, '../../dictionary/go');

const MODULES = [
  './go/string-math.mjs',
  './go/collections-validation.mjs',
  './go/processing-filesystem.mjs',
  './go/networking-formatting.mjs',
  './go/structures-algorithms.mjs',
  './go/concurrency-models.mjs',
  './go/models2-geometry.mjs',
  './go/encoding-extra.mjs',
];

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

function renderImports(pkgs) {
  if (!pkgs || pkgs.length === 0) return '';
  return `import (\n${pkgs.map((p) => `\t"${p}"`).join('\n')}\n)\n\n`;
}

function renderFile(fd) {
  const header = `// ${fd.file} — generated by scripts/generate/generate-go.mjs (do not edit by hand).
// Realistic Go typing blocks for vibetyper: ${fd.topic}.
package main

`;
  return header + renderImports(fd.imports) + fd.units.join('\n\n') + '\n';
}

// ---------------------------------------------------------------------------
// Sanity checks
// ---------------------------------------------------------------------------

// Brace balance check that ignores braces inside // comments, /* */ comments,
// double-quoted strings, single-quoted runes, and backtick raw strings.
// Mirrors the scanner used by server/blockSplitter.js so a unit that passes
// here will split as a single block.
function checkUnitBalance(unit, file, idx) {
  const lines = unit.split('\n');
  let depth = 0;
  for (const line of lines) {
    let inBlock = false;
    let i = 0;
    while (i < line.length) {
      const ch = line[i];
      const next = line[i + 1];
      if (inBlock) {
        if (ch === '*' && next === '/') {
          inBlock = false;
          i += 2;
        } else {
          i++;
        }
        continue;
      }
      if (ch === '/' && next === '/') break;
      if (ch === '/' && next === '*') {
        inBlock = true;
        i += 2;
        continue;
      }
      if (ch === '"' || ch === "'" || ch === '`') {
        const quote = ch;
        i++;
        while (i < line.length) {
          if (line[i] === '\\') {
            i += 2;
            continue;
          }
          if (line[i] === quote) {
            i++;
            break;
          }
          i++;
        }
        continue;
      }
      if (ch === '{') depth++;
      else if (ch === '}') depth--;
      i++;
    }
    if (depth < 0) {
      throw new Error(`${file} unit #${idx} has a closing brace with nothing to open:\n${unit}`);
    }
  }
  if (depth !== 0) {
    throw new Error(`${file} unit #${idx} has unbalanced braces (depth ${depth}):\n${unit}`);
  }
}

// Verify every declared import is actually referenced somewhere in the file.
function checkImportsUsed(fd, content) {
  const unused = fd.imports.filter((pkg) => {
    const last = pkg.split('/').pop();
    return !content.includes(last + '.');
  });
  if (unused.length) {
    throw new Error(`${fd.file}: declared but unused imports: ${unused.join(', ')}`);
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

let totalUnits = 0;
const written = [];

for (const modPath of MODULES) {
  const mod = await import(modPath);
  for (const fd of mod.default) {
    for (let i = 0; i < fd.units.length; i++) {
      checkUnitBalance(fd.units[i], fd.file, i);
    }
    const content = renderFile(fd);
    checkImportsUsed(fd, content);
    fs.writeFileSync(path.join(outDir, fd.file), content);
    totalUnits += fd.units.length;
    written.push(fd.file);
  }
}

console.log('Wrote %d Go dictionary files, %d units total.', written.length, totalUnits);
for (const f of written) console.log('  -', f);
