// algorithms.c — generated by scripts/generate/generate-c.mjs (do not edit by hand).
// Realistic C typing blocks for vibetyper: classic algorithms and dynamic programming.

#include <limits.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

// alg_binary_search returns the index of target in a sorted array, or -1.
long alg_binary_search(const int *sorted, size_t count, int target) {
    size_t lo = 0, hi = count;
    while (lo < hi) {
        size_t mid = lo + (hi - lo) / 2;
        if (sorted[mid] == target) return (long)mid;
        if (sorted[mid] < target) lo = mid + 1;
        else hi = mid;
    }
    return -1;
}

// alg_linear_search returns the index of the first match, or -1.
long alg_linear_search(const int *values, size_t count, int target) {
    for (size_t i = 0; i < count; i++) {
        if (values[i] == target) return (long)i;
    }
    return -1;
}

// alg_bubble_sort sorts values ascending in place.
void alg_bubble_sort(int *values, size_t count) {
    for (size_t i = 0; i + 1 < count; i++) {
        bool swapped = false;
        for (size_t j = 0; j + 1 < count - i; j++) {
            if (values[j] > values[j + 1]) {
                int tmp = values[j];
                values[j] = values[j + 1];
                values[j + 1] = tmp;
                swapped = true;
            }
        }
        if (!swapped) break;
    }
}

// alg_selection_sort sorts values ascending in place.
void alg_selection_sort(int *values, size_t count) {
    for (size_t i = 0; i + 1 < count; i++) {
        size_t min = i;
        for (size_t j = i + 1; j < count; j++) {
            if (values[j] < values[min]) min = j;
        }
        if (min != i) {
            int tmp = values[i];
            values[i] = values[min];
            values[min] = tmp;
        }
    }
}

// alg_insertion_sort sorts values ascending in place.
void alg_insertion_sort(int *values, size_t count) {
    for (size_t i = 1; i < count; i++) {
        int key = values[i];
        size_t j = i;
        while (j > 0 && values[j - 1] > key) {
            values[j] = values[j - 1];
            j--;
        }
        values[j] = key;
    }
}

// alg_quick_sort sorts values ascending with a Hoare partition.
void alg_quick_sort(int *values, size_t count) {
    if (count < 2) return;
    int pivot = values[count / 2];
    size_t i = 0, j = count - 1;
    while (i <= j) {
        while (values[i] < pivot) i++;
        while (values[j] > pivot) j--;
        if (i <= j) {
            int tmp = values[i];
            values[i] = values[j];
            values[j] = tmp;
            i++;
            j--;
        }
    }
    alg_quick_sort(values, j + 1);
    alg_quick_sort(values + i, count - i);
}

// alg_merge_sort sorts values ascending using a scratch buffer.
void alg_merge_sort(int *values, size_t count) {
    if (count < 2) return;
    size_t mid = count / 2;
    alg_merge_sort(values, mid);
    alg_merge_sort(values + mid, count - mid);
    int *merged = malloc(count * sizeof(int));
    if (merged == NULL) return;
    size_t i = 0, j = mid, k = 0;
    while (i < mid && j < count) merged[k++] = values[i] <= values[j] ? values[i++] : values[j++];
    while (i < mid) merged[k++] = values[i++];
    while (j < count) merged[k++] = values[j++];
    memcpy(values, merged, count * sizeof(int));
    free(merged);
}

// alg_counting_sort sorts values in [0, max_value] into out (which must
// hold at least count entries) using a counting array.
void alg_counting_sort(const int *values, size_t count, int max_value, int *out) {
    size_t *counts = calloc((size_t)max_value + 1, sizeof(size_t));
    if (counts == NULL) return;
    for (size_t i = 0; i < count; i++) counts[values[i]]++;
    for (int v = 1; v <= max_value; v++) counts[v] += counts[v - 1];
    for (size_t i = count; i-- > 0;) {
        int v = values[i];
        out[--counts[v]] = v;
    }
    free(counts);
}

// alg_knapsack_01 returns the max value for a 0/1 knapsack of the given
// capacity using bottom-up dynamic programming.
int alg_knapsack_01(const int *weights, const int *values, size_t n, int capacity) {
    int *dp = calloc((size_t)capacity + 1, sizeof(int));
    if (dp == NULL) return 0;
    for (size_t i = 0; i < n; i++) {
        for (int w = capacity; w >= weights[i]; w--) {
            int take = dp[w - weights[i]] + values[i];
            if (take > dp[w]) dp[w] = take;
        }
    }
    int best = dp[capacity];
    free(dp);
    return best;
}

// alg_longest_common_subsequence returns the LCS length of a and b.
size_t alg_longest_common_subsequence(const char *a, const char *b) {
    size_t na = strlen(a), nb = strlen(b);
    size_t *prev = calloc(nb + 1, sizeof(size_t));
    size_t *curr = calloc(nb + 1, sizeof(size_t));
    if (prev == NULL || curr == NULL) { free(prev); free(curr); return 0; }
    for (size_t i = 1; i <= na; i++) {
        for (size_t j = 1; j <= nb; j++) {
            if (a[i - 1] == b[j - 1]) curr[j] = prev[j - 1] + 1;
            else curr[j] = prev[j] > curr[j - 1] ? prev[j] : curr[j - 1];
        }
        size_t *tmp = prev;
        prev = curr;
        curr = tmp;
    }
    size_t result = prev[nb];
    free(prev);
    free(curr);
    return result;
}

// alg_longest_increasing_subsequence returns the LIS length of values.
size_t alg_longest_increasing_subsequence(const int *values, size_t count) {
    size_t *lengths = malloc(count * sizeof(size_t));
    if (lengths == NULL) return 0;
    size_t best = 0;
    for (size_t i = 0; i < count; i++) {
        lengths[i] = 1;
        for (size_t j = 0; j < i; j++) {
            if (values[j] < values[i] && lengths[j] + 1 > lengths[i]) lengths[i] = lengths[j] + 1;
        }
        if (lengths[i] > best) best = lengths[i];
    }
    free(lengths);
    return best;
}

// alg_edit_distance returns the Levenshtein distance between a and b.
size_t alg_edit_distance(const char *a, const char *b) {
    size_t na = strlen(a), nb = strlen(b);
    size_t *prev = malloc((nb + 1) * sizeof(size_t));
    size_t *curr = malloc((nb + 1) * sizeof(size_t));
    if (prev == NULL || curr == NULL) { free(prev); free(curr); return 0; }
    for (size_t j = 0; j <= nb; j++) prev[j] = j;
    for (size_t i = 1; i <= na; i++) {
        curr[0] = i;
        for (size_t j = 1; j <= nb; j++) {
            size_t cost = a[i - 1] == b[j - 1] ? 0 : 1;
            size_t del = prev[j] + 1;
            size_t ins = curr[j - 1] + 1;
            size_t sub = prev[j - 1] + cost;
            size_t best = del < ins ? del : ins;
            curr[j] = sub < best ? sub : best;
        }
        size_t *tmp = prev;
        prev = curr;
        curr = tmp;
    }
    size_t result = prev[nb];
    free(prev);
    free(curr);
    return result;
}

// alg_coin_change returns the fewest coins summing to amount, or -1.
int alg_coin_change(const int *coins, size_t n, int amount) {
    int *dp = malloc((size_t)(amount + 1) * sizeof(int));
    if (dp == NULL) return -1;
    dp[0] = 0;
    for (int a = 1; a <= amount; a++) dp[a] = amount + 1;
    for (int a = 1; a <= amount; a++) {
        for (size_t i = 0; i < n; i++) {
            if (coins[i] <= a && dp[a - coins[i]] + 1 < dp[a]) dp[a] = dp[a - coins[i]] + 1;
        }
    }
    int best = dp[amount] > amount ? -1 : dp[amount];
    free(dp);
    return best;
}

// alg_max_subarray returns the largest contiguous subarray sum (Kadane).
int alg_max_subarray(const int *values, size_t count) {
    if (count == 0) return 0;
    int best = values[0], running = values[0];
    for (size_t i = 1; i < count; i++) {
        running = running + values[i] > values[i] ? running + values[i] : values[i];
        if (running > best) best = running;
    }
    return best;
}

// alg_fibonacci_memo computes fib(n) with an explicit memoization table.
uint64_t alg_fibonacci_memo(unsigned int n) {
    if (n < 2) return n;
    uint64_t *memo = calloc(n + 1, sizeof(uint64_t));
    if (memo == NULL) return 0;
    memo[1] = 1;
    for (unsigned int i = 2; i <= n; i++) memo[i] = memo[i - 1] + memo[i - 2];
    uint64_t result = memo[n];
    free(memo);
    return result;
}

// alg_binary_gcd computes gcd via Stein's binary algorithm (no division).
uint64_t alg_binary_gcd(uint64_t a, uint64_t b) {
    if (a == 0) return b;
    if (b == 0) return a;
    unsigned int shift = 0;
    while (((a | b) & 1u) == 0) {
        a >>= 1;
        b >>= 1;
        shift++;
    }
    while ((a & 1u) == 0) a >>= 1;
    while (b != 0) {
        while ((b & 1u) == 0) b >>= 1;
        if (a > b) {
            uint64_t t = a;
            a = b;
            b = t;
        }
        b -= a;
    }
    return a << shift;
}

// alg_dijkstra finds shortest paths from src in a dense graph given as an
// n*n adjacency matrix; dist entries use INT_MAX for no edge.
void alg_dijkstra(const int *graph, int n, int src, int *dist) {
    bool *visited = calloc((size_t)n, sizeof(bool));
    if (visited == NULL) return;
    for (int i = 0; i < n; i++) dist[i] = INT_MAX;
    dist[src] = 0;
    for (int iter = 0; iter < n; iter++) {
        int u = -1;
        for (int i = 0; i < n; i++) {
            if (!visited[i] && (u == -1 || dist[i] < dist[u])) u = i;
        }
        if (u == -1 || dist[u] == INT_MAX) break;
        visited[u] = true;
        for (int v = 0; v < n; v++) {
            int w = graph[u * n + v];
            if (w >= 0 && dist[u] != INT_MAX && dist[u] + w < dist[v]) dist[v] = dist[u] + w;
        }
    }
    free(visited);
}

// alg_bfs computes hop distances from src in an n*n adjacency matrix,
// marking unreachable nodes with -1 (uses a simple queue).
void alg_bfs(const int *graph, int n, int src, int *dist) {
    int *queue = malloc((size_t)n * sizeof(int));
    if (queue == NULL) return;
    for (int i = 0; i < n; i++) dist[i] = -1;
    int head = 0, tail = 0;
    queue[tail++] = src;
    dist[src] = 0;
    while (head < tail) {
        int u = queue[head++];
        for (int v = 0; v < n; v++) {
            if (graph[u * n + v] && dist[v] == -1) {
                dist[v] = dist[u] + 1;
                queue[tail++] = v;
            }
        }
    }
    free(queue);
}

// alg_dfs visits every node reachable from u in an adjacency matrix and
// records the discovery order in order (n entries).
void alg_dfs(const int *graph, int n, int u, bool *visited, int *order, int *pos) {
    visited[u] = true;
    order[(*pos)++] = u;
    for (int v = 0; v < n; v++) {
        if (graph[u * n + v] && !visited[v]) alg_dfs(graph, n, v, visited, order, pos);
    }
}

// alg_rotated_min finds the minimum in a rotated sorted array.
int alg_rotated_min(const int *values, size_t count) {
    size_t lo = 0, hi = count - 1;
    while (lo < hi) {
        size_t mid = lo + (hi - lo) / 2;
        if (values[mid] > values[hi]) lo = mid + 1;
        else hi = mid;
    }
    return values[lo];
}
