// arrays_collections.c — generated by scripts/generate/generate-c.mjs (do not edit by hand).
// Realistic C typing blocks for vibetyper: array and collection helpers.

#include <limits.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>

// array_sum returns the sum of every element in values.
long array_sum(const int *values, size_t count) {
    long total = 0;
    for (size_t i = 0; i < count; i++) total += values[i];
    return total;
}

// array_min returns the smallest element, or 0 for an empty array.
int array_min(const int *values, size_t count) {
    if (count == 0) return 0;
    int best = values[0];
    for (size_t i = 1; i < count; i++) {
        if (values[i] < best) best = values[i];
    }
    return best;
}

// array_max returns the largest element, or 0 for an empty array.
int array_max(const int *values, size_t count) {
    if (count == 0) return 0;
    int best = values[0];
    for (size_t i = 1; i < count; i++) {
        if (values[i] > best) best = values[i];
    }
    return best;
}

// array_average returns the arithmetic mean, or 0.0 for an empty array.
double array_average(const int *values, size_t count) {
    if (count == 0) return 0.0;
    return (double)array_sum(values, count) / (double)count;
}

// array_reverse reverses the element order in place.
void array_reverse(int *values, size_t count) {
    for (size_t i = 0; i < count / 2; i++) {
        int tmp = values[i];
        values[i] = values[count - 1 - i];
        values[count - 1 - i] = tmp;
    }
}

// array_rotate_left shifts every element steps positions to the left.
void array_rotate_left(int *values, size_t count, size_t steps) {
    if (count == 0) return;
    steps %= count;
    for (size_t s = 0; s < steps; s++) {
        int first = values[0];
        for (size_t i = 0; i + 1 < count; i++) values[i] = values[i + 1];
        values[count - 1] = first;
    }
}

// array_shuffle permutes values in place with the Fisher-Yates method.
void array_shuffle(int *values, size_t count) {
    for (size_t i = count; i > 1; i--) {
        size_t j = (size_t)rand() % i;
        int tmp = values[i - 1];
        values[i - 1] = values[j];
        values[j] = tmp;
    }
}

// array_find returns the index of the first match, or (size_t)-1 if absent.
size_t array_find(const int *values, size_t count, int target) {
    for (size_t i = 0; i < count; i++) {
        if (values[i] == target) return i;
    }
    return (size_t)-1;
}

// array_contains reports whether target appears anywhere in values.
bool array_contains(const int *values, size_t count, int target) {
    return array_find(values, count, target) != (size_t)-1;
}

// array_unique_count counts distinct values using quadratic scan.
size_t array_unique_count(const int *values, size_t count) {
    size_t distinct = 0;
    for (size_t i = 0; i < count; i++) {
        bool seen = false;
        for (size_t j = 0; j < i; j++) {
            if (values[j] == values[i]) { seen = true; break; }
        }
        if (!seen) distinct++;
    }
    return distinct;
}

// array_copy returns a heap copy of values, or NULL on failure.
int *array_copy(const int *src, size_t count) {
    int *copy = malloc(count * sizeof(int));
    if (copy == NULL) return NULL;
    memcpy(copy, src, count * sizeof(int));
    return copy;
}

// array_swap_elements exchanges elements at indices i and j (if valid).
void array_swap_elements(int *values, size_t i, size_t j, size_t count) {
    if (i >= count || j >= count) return;
    int tmp = values[i];
    values[i] = values[j];
    values[j] = tmp;
}

// array_running_sum writes cumulative prefix sums into out.
void array_running_sum(const int *values, size_t count, long *out) {
    long total = 0;
    for (size_t i = 0; i < count; i++) {
        total += values[i];
        out[i] = total;
    }
}

// array_second_largest returns the second largest distinct value, or the
// largest value when fewer than two distinct values exist.
int array_second_largest(const int *values, size_t count) {
    int largest = array_max(values, count);
    int second = INT_MIN;
    for (size_t i = 0; i < count; i++) {
        if (values[i] != largest && values[i] > second) second = values[i];
    }
    return second == INT_MIN ? largest : second;
}

// array_majority_element returns an element appearing more than count/2
// times (Boyer-Moore voting), or INT_MIN when there is none.
int array_majority_element(const int *values, size_t count) {
    int candidate = 0;
    int votes = 0;
    for (size_t i = 0; i < count; i++) {
        if (votes == 0) candidate = values[i];
        votes += values[i] == candidate ? 1 : -1;
    }
    size_t tally = 0;
    for (size_t i = 0; i < count; i++) {
        if (values[i] == candidate) tally++;
    }
    return tally > count / 2 ? candidate : INT_MIN;
}

// array_merge_sorted merges two sorted arrays into a new allocation.
int *array_merge_sorted(const int *a, size_t na, const int *b, size_t nb, size_t *out_count) {
    int *merged = malloc((na + nb) * sizeof(int));
    if (merged == NULL) return NULL;
    size_t i = 0, j = 0, k = 0;
    while (i < na && j < nb) merged[k++] = a[i] <= b[j] ? a[i++] : b[j++];
    while (i < na) merged[k++] = a[i++];
    while (j < nb) merged[k++] = b[j++];
    *out_count = k;
    return merged;
}

// array_remove_duplicates removes duplicate values in place, preserving
// first-occurrence order, and returns the new length.
size_t array_remove_duplicates(int *values, size_t count) {
    if (count < 2) return count;
    size_t write = 1;
    for (size_t read = 1; read < count; read++) {
        bool seen = false;
        for (size_t j = 0; j < write; j++) {
            if (values[j] == values[read]) { seen = true; break; }
        }
        if (!seen) values[write++] = values[read];
    }
    return write;
}

// array_clamp_all clamps every element into [low, high] in place.
void array_clamp_all(int *values, size_t count, int low, int high) {
    for (size_t i = 0; i < count; i++) {
        if (values[i] < low) values[i] = low;
        else if (values[i] > high) values[i] = high;
    }
}

// array_partition rearranges values so elements < pivot precede the rest,
// returning the boundary index (Lomuto scheme).
size_t array_partition(int *values, size_t count, int pivot) {
    size_t boundary = 0;
    for (size_t i = 0; i < count; i++) {
        if (values[i] < pivot) {
            int tmp = values[boundary];
            values[boundary] = values[i];
            values[i] = tmp;
            boundary++;
        }
    }
    return boundary;
}

// array_dot_product returns the dot product of two equal-length arrays.
long array_dot_product(const int *a, const int *b, size_t count) {
    long total = 0;
    for (size_t i = 0; i < count; i++) total += (long)a[i] * b[i];
    return total;
}
