// binary_tree.c — generated by scripts/generate/generate-c.mjs (do not edit by hand).
// Realistic C typing blocks for vibetyper: binary search tree.

#include <stdbool.h>
#include <stddef.h>
#include <stdlib.h>

typedef struct bst_node {
    int value;
    struct bst_node *left;
    struct bst_node *right;
} bst_node_t;

// bst_insert adds value to the tree and returns the (possibly new) root.
bst_node_t *bst_insert(bst_node_t *root, int value) {
    if (root == NULL) {
        root = malloc(sizeof(bst_node_t));
        if (root == NULL) return NULL;
        root->value = value;
        root->left = root->right = NULL;
        return root;
    }
    if (value < root->value) root->left = bst_insert(root->left, value);
    else if (value > root->value) root->right = bst_insert(root->right, value);
    return root;
}

// bst_search reports whether value is present in the tree.
bool bst_search(const bst_node_t *root, int value) {
    const bst_node_t *node = root;
    while (node != NULL) {
        if (value == node->value) return true;
        node = value < node->value ? node->left : node->right;
    }
    return false;
}

// bst_min returns the smallest value in the tree, or 0 for an empty tree.
int bst_min(const bst_node_t *root) {
    const bst_node_t *node = root;
    while (node != NULL && node->left != NULL) node = node->left;
    return node != NULL ? node->value : 0;
}

// bst_max returns the largest value in the tree, or 0 for an empty tree.
int bst_max(const bst_node_t *root) {
    const bst_node_t *node = root;
    while (node != NULL && node->right != NULL) node = node->right;
    return node != NULL ? node->value : 0;
}

// bst_height returns the number of levels in the tree.
size_t bst_height(const bst_node_t *root) {
    if (root == NULL) return 0;
    size_t left = bst_height(root->left);
    size_t right = bst_height(root->right);
    return 1 + (left > right ? left : right);
}

// bst_size returns the number of nodes in the tree.
size_t bst_size(const bst_node_t *root) {
    if (root == NULL) return 0;
    return 1 + bst_size(root->left) + bst_size(root->right);
}

// bst_inorder fills out with values in ascending order, returning the count.
size_t bst_inorder(const bst_node_t *root, int *out) {
    if (root == NULL) return 0;
    size_t n = bst_inorder(root->left, out);
    out[n++] = root->value;
    return n + bst_inorder(root->right, out + n);
}

// bst_preorder fills out in preorder (root, left, right), returning the count.
size_t bst_preorder(const bst_node_t *root, int *out) {
    if (root == NULL) return 0;
    size_t n = 1;
    out[0] = root->value;
    n += bst_preorder(root->left, out + n);
    n += bst_preorder(root->right, out + n);
    return n;
}

// bst_postorder fills out in postorder (left, right, root), returning the count.
size_t bst_postorder(const bst_node_t *root, int *out) {
    if (root == NULL) return 0;
    size_t n = bst_postorder(root->left, out);
    n += bst_postorder(root->right, out + n);
    out[n++] = root->value;
    return n;
}

// bst_remove deletes value and returns the new root.
bst_node_t *bst_remove(bst_node_t *root, int value) {
    if (root == NULL) return NULL;
    if (value < root->value) {
        root->left = bst_remove(root->left, value);
    } else if (value > root->value) {
        root->right = bst_remove(root->right, value);
    } else {
        if (root->left == NULL) {
            bst_node_t *right = root->right;
            free(root);
            return right;
        }
        if (root->right == NULL) {
            bst_node_t *left = root->left;
            free(root);
            return left;
        }
        int successor = bst_min(root->right);
        root->value = successor;
        root->right = bst_remove(root->right, successor);
    }
    return root;
}

// bst_free releases every node in the tree.
void bst_free(bst_node_t *root) {
    if (root == NULL) return;
    bst_free(root->left);
    bst_free(root->right);
    free(root);
}

// bst_is_balanced reports whether subtree heights differ by at most one.
bool bst_is_balanced(const bst_node_t *root) {
    if (root == NULL) return true;
    size_t left = bst_height(root->left);
    size_t right = bst_height(root->right);
    long diff = (long)left - (long)right;
    return diff >= -1 && diff <= 1 && bst_is_balanced(root->left) && bst_is_balanced(root->right);
}

// bst_lca returns the lowest common ancestor of two values in a BST.
bst_node_t *bst_lca(bst_node_t *root, int a, int b) {
    bst_node_t *node = root;
    while (node != NULL) {
        if (a < node->value && b < node->value) node = node->left;
        else if (a > node->value && b > node->value) node = node->right;
        else return node;
    }
    return NULL;
}

// bst_count_leaves returns the number of leaf nodes.
size_t bst_count_leaves(const bst_node_t *root) {
    if (root == NULL) return 0;
    if (root->left == NULL && root->right == NULL) return 1;
    return bst_count_leaves(root->left) + bst_count_leaves(root->right);
}

// bst_sum returns the sum of all values in the tree.
long bst_sum(const bst_node_t *root) {
    if (root == NULL) return 0;
    return (long)root->value + bst_sum(root->left) + bst_sum(root->right);
}
