// bit_manipulation.c — generated by scripts/generate/generate-c.mjs (do not edit by hand).
// Realistic C typing blocks for vibetyper: bit manipulation.

#include <stdbool.h>
#include <stdint.h>

// bits_count_set returns the number of set bits (popcount).
unsigned int bits_count_set(uint32_t value) {
    unsigned int count = 0;
    while (value != 0) {
        value &= value - 1;
        count++;
    }
    return count;
}

// bits_is_power_of_two reports whether value is a positive power of two.
bool bits_is_power_of_two(uint32_t value) {
    return value != 0 && (value & (value - 1)) == 0;
}

// bits_set returns value with the given bit set to 1.
uint32_t bits_set(uint32_t value, unsigned int bit) {
    return value | (1u << bit);
}

// bits_clear returns value with the given bit cleared to 0.
uint32_t bits_clear(uint32_t value, unsigned int bit) {
    return value & ~(1u << bit);
}

// bits_toggle returns value with the given bit flipped.
uint32_t bits_toggle(uint32_t value, unsigned int bit) {
    return value ^ (1u << bit);
}

// bits_get reports whether the given bit is set.
bool bits_get(uint32_t value, unsigned int bit) {
    return (value >> bit) & 1u;
}

// bits_highest_set returns the index of the most significant set bit, or -1.
int bits_highest_set(uint32_t value) {
    int highest = -1;
    for (unsigned int i = 0; i < 32; i++) {
        if (value & (1u << i)) highest = (int)i;
    }
    return highest;
}

// bits_lowest_set isolates the least significant set bit.
uint32_t bits_lowest_set(uint32_t value) {
    return value & (~value + 1u);
}

// bits_rotate_left rotates value left by shift bit positions.
uint32_t bits_rotate_left(uint32_t value, unsigned int shift) {
    shift &= 31u;
    return shift == 0 ? value : (value << shift) | (value >> (32u - shift));
}

// bits_rotate_right rotates value right by shift bit positions.
uint32_t bits_rotate_right(uint32_t value, unsigned int shift) {
    shift &= 31u;
    return shift == 0 ? value : (value >> shift) | (value << (32u - shift));
}

// bits_reverse reverses the order of all 32 bits.
uint32_t bits_reverse(uint32_t value) {
    uint32_t result = 0;
    for (unsigned int i = 0; i < 32; i++) {
        result = (result << 1) | (value & 1u);
        value >>= 1;
    }
    return result;
}

// bits_swap_nibbles swaps the high and low nibble of every byte.
uint32_t bits_swap_nibbles(uint32_t value) {
    return ((value & 0x0F0F0F0Fu) << 4) | ((value & 0xF0F0F0F0u) >> 4);
}

// bits_count_leading_zeros counts zero bits above the highest set bit.
unsigned int bits_count_leading_zeros(uint32_t value) {
    if (value == 0) return 32;
    unsigned int count = 0;
    for (int i = 31; i >= 0; i--) {
        if (value & (1u << i)) break;
        count++;
    }
    return count;
}

// bits_parity returns 1 when value has an odd number of set bits.
unsigned int bits_parity(uint32_t value) {
    unsigned int parity = 0;
    while (value != 0) {
        parity ^= 1u;
        value &= value - 1;
    }
    return parity;
}

// bits_add adds a and b using only bitwise operations.
int bits_add(int a, int b) {
    while (b != 0) {
        int carry = a & b;
        a = a ^ b;
        b = carry << 1;
    }
    return a;
}

// bits_to_gray converts value to its binary Gray code.
uint32_t bits_to_gray(uint32_t value) {
    return value ^ (value >> 1);
}

// bits_from_gray converts a Gray code back to binary.
uint32_t bits_from_gray(uint32_t value) {
    uint32_t result = value;
    while (value >>= 1) result ^= value;
    return result;
}

// bits_swap_halves exchanges the upper and lower 16 bits.
uint32_t bits_swap_halves(uint32_t value) {
    return (value << 16) | (value >> 16);
}
