// data_processing.c — generated by scripts/generate/generate-c.mjs (do not edit by hand).
// Realistic C typing blocks for vibetyper: data processing and statistics.

#include <math.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// dp_strdup returns a heap copy of s, or NULL on failure.
char *dp_strdup(const char *s) {
    size_t len = strlen(s) + 1;
    char *copy = malloc(len);
    if (copy == NULL) return NULL;
    memcpy(copy, s, len);
    return copy;
}

// dp_count_lines counts newline characters in a text buffer.
size_t dp_count_lines(const char *text) {
    size_t lines = 0;
    for (const char *p = text; *p != '\0'; p++) {
        if (*p == '\n') lines++;
    }
    return lines;
}

// dp_csv_field_count counts the fields in one CSV line, honoring quotes.
size_t dp_csv_field_count(const char *line) {
    size_t fields = 0;
    bool in_quotes = false, in_field = false;
    for (const char *p = line; *p != '\0'; p++) {
        if (*p == '"') { in_quotes = !in_quotes; in_field = true; }
        else if (*p == ',' && !in_quotes) { fields++; in_field = false; }
        else if (*p != '\r' && *p != '\n') in_field = true;
    }
    return in_field ? fields + 1 : fields;
}

// dp_split_csv_row splits one CSV line into freshly allocated fields and
// returns the count (caller frees each field and the array).
size_t dp_split_csv_row(const char *line, char ***fields_out) {
    size_t capacity = 8, count = 0;
    char **fields = calloc(capacity, sizeof(char *));
    if (fields == NULL) return 0;
    const char *p = line;
    while (*p != '\0') {
        char field[1024];
        size_t len = 0;
        bool quoted = *p == '"';
        if (quoted) p++;
        while (*p != '\0' && !(quoted ? *p == '"' : *p == ',')) {
            if (len + 1 < sizeof(field)) field[len++] = *p;
            p++;
        }
        if (quoted && *p == '"') p++;
        field[len] = '\0';
        if (count == capacity) {
            capacity *= 2;
            char **grown = realloc(fields, capacity * sizeof(char *));
            if (grown == NULL) { free(fields); return 0; }
            fields = grown;
        }
        fields[count++] = dp_strdup(field);
        if (*p == ',') p++;
    }
    *fields_out = fields;
    return count;
}

// dp_sum returns the total of values.
double dp_sum(const double *values, size_t count) {
    double total = 0.0;
    for (size_t i = 0; i < count; i++) total += values[i];
    return total;
}

// dp_mean returns the arithmetic mean, or 0.0 for an empty sample.
double dp_mean(const double *values, size_t count) {
    return count == 0 ? 0.0 : dp_sum(values, count) / (double)count;
}

// dp_sort_doubles sorts values ascending with insertion sort.
void dp_sort_doubles(double *values, size_t count) {
    for (size_t i = 1; i < count; i++) {
        double key = values[i];
        size_t j = i;
        while (j > 0 && values[j - 1] > key) {
            values[j] = values[j - 1];
            j--;
        }
        values[j] = key;
    }
}

// dp_median returns the median of a sorted copy of values.
double dp_median(const double *values, size_t count) {
    if (count == 0) return 0.0;
    double *sorted = malloc(count * sizeof(double));
    if (sorted == NULL) return 0.0;
    memcpy(sorted, values, count * sizeof(double));
    dp_sort_doubles(sorted, count);
    double median = count % 2 == 1
        ? sorted[count / 2]
        : (sorted[count / 2 - 1] + sorted[count / 2]) / 2.0;
    free(sorted);
    return median;
}

// dp_standard_deviation returns the population standard deviation.
double dp_standard_deviation(const double *values, size_t count) {
    if (count == 0) return 0.0;
    double mean = dp_mean(values, count);
    double sum_sq = 0.0;
    for (size_t i = 0; i < count; i++) {
        double diff = values[i] - mean;
        sum_sq += diff * diff;
    }
    return sqrt(sum_sq / (double)count);
}

// dp_min_max reports the smallest and largest values via out parameters.
void dp_min_max(const double *values, size_t count, double *min_out, double *max_out) {
    if (count == 0) { *min_out = *max_out = 0.0; return; }
    double min = values[0], max = values[0];
    for (size_t i = 1; i < count; i++) {
        if (values[i] < min) min = values[i];
        if (values[i] > max) max = values[i];
    }
    *min_out = min;
    *max_out = max;
}

// dp_histogram buckets values into n_bins over the range [min, max].
void dp_histogram(const double *values, size_t count, double min, double max, size_t n_bins, size_t *bins) {
    for (size_t b = 0; b < n_bins; b++) bins[b] = 0;
    if (count == 0 || max <= min) return;
    for (size_t i = 0; i < count; i++) {
        double t = (values[i] - min) / (max - min);
        size_t b = t < 0.0 ? 0 : t >= 1.0 ? n_bins - 1 : (size_t)(t * n_bins);
        bins[b]++;
    }
}

// dp_moving_average writes a trailing-window average into out.
void dp_moving_average(const double *values, size_t count, size_t window, double *out) {
    for (size_t i = 0; i < count; i++) {
        size_t start = i >= window ? i - window + 1 : 0;
        double total = 0.0;
        for (size_t j = start; j <= i; j++) total += values[j];
        out[i] = total / (double)(i - start + 1);
    }
}

// dp_normalize rescales values into [0, 1] in place.
void dp_normalize(double *values, size_t count) {
    if (count == 0) return;
    double min, max;
    dp_min_max(values, count, &min, &max);
    double span = max - min;
    for (size_t i = 0; i < count; i++) {
        values[i] = span == 0.0 ? 0.5 : (values[i] - min) / span;
    }
}

// dp_frequency_count counts values within epsilon of a target.
size_t dp_frequency_count(const double *values, size_t count, double target, double epsilon) {
    size_t hits = 0;
    for (size_t i = 0; i < count; i++) {
        if (fabs(values[i] - target) <= epsilon) hits++;
    }
    return hits;
}

// dp_parse_key_value splits "key=value" on the first '=' into two buffers.
bool dp_parse_key_value(const char *line, char *key, char *value, size_t cap) {
    const char *eq = strchr(line, '=');
    if (eq == NULL || eq == line) return false;
    size_t key_len = (size_t)(eq - line);
    if (key_len + 1 > cap) return false;
    memcpy(key, line, key_len);
    key[key_len] = '\0';
    snprintf(value, cap, "%s", eq + 1);
    return true;
}

// dp_zscore writes standard scores (z-scores) of values into out.
void dp_zscore(const double *values, size_t count, double *out) {
    double mean = dp_mean(values, count);
    double sd = dp_standard_deviation(values, count);
    for (size_t i = 0; i < count; i++) {
        out[i] = sd == 0.0 ? 0.0 : (values[i] - mean) / sd;
    }
}

// dp_json_escape copies s into out, escaping quotes and backslashes.
size_t dp_json_escape(const char *s, char *out, size_t cap) {
    size_t w = 0;
    for (const char *p = s; *p != '\0' && w + 2 < cap; p++) {
        if (*p == '"' || *p == '\\') out[w++] = '\\';
        out[w++] = *p;
    }
    out[w] = '\0';
    return w;
}

// dp_weighted_mean returns the mean of values weighted by weights.
double dp_weighted_mean(const double *values, const double *weights, size_t count) {
    double total = 0.0, weight_sum = 0.0;
    for (size_t i = 0; i < count; i++) {
        total += values[i] * weights[i];
        weight_sum += weights[i];
    }
    return weight_sum == 0.0 ? 0.0 : total / weight_sum;
}
