// date_time.c — generated by scripts/generate/generate-c.mjs (do not edit by hand).
// Realistic C typing blocks for vibetyper: date and time utilities.

#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>
#include <time.h>

typedef struct date {
    int year;
    int month;
    int day;
} date_t;

// dt_is_leap reports whether year is a Gregorian leap year.
bool dt_is_leap(int year) {
    return (year % 4 == 0 && year % 100 != 0) || year % 400 == 0;
}

// dt_days_in_month returns the number of days in a month, or 0 if invalid.
int dt_days_in_month(int year, int month) {
    static const int days[] = {31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};
    if (month < 1 || month > 12) return 0;
    if (month == 2 && dt_is_leap(year)) return 29;
    return days[month - 1];
}

// dt_days_in_year returns 366 for a leap year, otherwise 365.
int dt_days_in_year(int year) {
    return dt_is_leap(year) ? 366 : 365;
}

// dt_is_valid_date checks a date for month and day ranges.
bool dt_is_valid_date(const date_t *d) {
    if (d->month < 1 || d->month > 12 || d->day < 1) return false;
    return d->day <= dt_days_in_month(d->year, d->month);
}

// dt_day_of_week returns 0=Sunday .. 6=Saturday (Sakamoto's algorithm).
int dt_day_of_week(const date_t *d) {
    static const int offsets[] = {0, 3, 2, 5, 0, 3, 5, 1, 4, 6, 2, 4};
    int y = d->year;
    if (d->month < 3) y -= 1;
    return (y + y / 4 - y / 100 + y / 400 + offsets[d->month - 1] + d->day) % 7;
}

// dt_day_of_year returns the 1-based day within the year.
int dt_day_of_year(const date_t *d) {
    int total = d->day;
    for (int m = 1; m < d->month; m++) total += dt_days_in_month(d->year, m);
    return total;
}

// dt_days_since_epoch returns days from 1970-01-01 (civil calendar math).
long dt_days_since_epoch(const date_t *d) {
    long y = d->year - (d->month <= 2 ? 1 : 0);
    long era = (y >= 0 ? y : y - 399) / 400;
    long yoe = y - era * 400;
    long doy = (153 * (d->month + (d->month > 2 ? -3 : 9)) + 2) / 5 + d->day - 1;
    long doe = yoe * 365 + yoe / 4 - yoe / 100 + doy;
    return era * 146097 + doe - 719468;
}

// dt_days_between returns the signed number of days from a to b.
long dt_days_between(const date_t *a, const date_t *b) {
    return dt_days_since_epoch(b) - dt_days_since_epoch(a);
}

// dt_add_days shifts a date forward by n days (n may be negative).
void dt_add_days(date_t *d, long n) {
    long days = dt_days_since_epoch(d) + n + 719468;
    long era = (days >= 0 ? days : days - 146096) / 146097;
    long doe = days - era * 146097;
    long yoe = (doe - doe / 1460 + doe / 36524 - doe / 146096) / 365;
    long y = yoe + era * 400;
    long doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    long mp = (5 * doy + 2) / 153;
    d->day = (int)(doy - (153 * mp + 2) / 5 + 1);
    d->month = (int)(mp + (mp < 10 ? 3 : -9));
    d->year = (int)(y + (d->month <= 2 ? 1 : 0));
}

// dt_compare returns negative, zero, or positive for a before/equal/after b.
int dt_compare(const date_t *a, const date_t *b) {
    if (a->year != b->year) return a->year - b->year;
    if (a->month != b->month) return a->month - b->month;
    return a->day - b->day;
}

// dt_parse_iso parses "YYYY-MM-DD" into a date; returns false on error.
bool dt_parse_iso(const char *text, date_t *out) {
    int year, month, day;
    if (sscanf(text, "%d-%d-%d", &year, &month, &day) != 3) return false;
    out->year = year;
    out->month = month;
    out->day = day;
    return dt_is_valid_date(out);
}

// dt_format_iso writes a date as "YYYY-MM-DD" into buf.
void dt_format_iso(const date_t *d, char *buf, size_t cap) {
    snprintf(buf, cap, "%04d-%02d-%02d", d->year, d->month, d->day);
}

// dt_timestamp_string writes the current local time as a timestamp.
void dt_timestamp_string(char *buf, size_t cap) {
    time_t now = time(NULL);
    struct tm *local = localtime(&now);
    strftime(buf, cap, "%Y-%m-%d %H:%M:%S", local);
}

// dt_elapsed_ms returns milliseconds elapsed since a clock() start value.
long dt_elapsed_ms(clock_t start) {
    return (long)((clock() - start) * 1000 / CLOCKS_PER_SEC);
}

// dt_week_of_year returns an approximate week number within the year.
int dt_week_of_year(const date_t *d) {
    return (dt_day_of_year(d) - dt_day_of_week(d) + 10) / 7;
}

// dt_is_weekend reports whether the date is a Saturday or Sunday.
bool dt_is_weekend(const date_t *d) {
    int dow = dt_day_of_week(d);
    return dow == 0 || dow == 6;
}
