// domain_models.c — generated by scripts/generate/generate-c.mjs (do not edit by hand).
// Realistic C typing blocks for vibetyper: domain models and small structs.

#include <math.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>

typedef struct point {
    double x;
    double y;
} point_t;

// point_distance returns the Euclidean distance between two points.
double point_distance(point_t a, point_t b) {
    double dx = a.x - b.x;
    double dy = a.y - b.y;
    return sqrt(dx * dx + dy * dy);
}

// point_midpoint returns the midpoint between two points.
point_t point_midpoint(point_t a, point_t b) {
    point_t mid = {(a.x + b.x) / 2.0, (a.y + b.y) / 2.0};
    return mid;
}

typedef struct rectangle {
    double x;
    double y;
    double width;
    double height;
} rectangle_t;

// rect_area returns the area of a rectangle.
double rect_area(rectangle_t r) {
    return r.width * r.height;
}

// rect_contains reports whether a point lies within a rectangle.
bool rect_contains(rectangle_t r, point_t p) {
    return p.x >= r.x && p.x <= r.x + r.width && p.y >= r.y && p.y <= r.y + r.height;
}

typedef struct circle {
    point_t center;
    double radius;
} circle_t;

// circle_area returns the area of a circle.
double circle_area(circle_t c) {
    static const double PI = 3.14159265358979323846;
    return PI * c.radius * c.radius;
}

typedef struct complex {
    double real;
    double imag;
} complex_t;

// complex_add returns the sum of two complex numbers.
complex_t complex_add(complex_t a, complex_t b) {
    complex_t result = {a.real + b.real, a.imag + b.imag};
    return result;
}

// complex_mul returns the product of two complex numbers.
complex_t complex_mul(complex_t a, complex_t b) {
    complex_t result = {
        a.real * b.real - a.imag * b.imag,
        a.real * b.imag + a.imag * b.real
    };
    return result;
}

typedef struct vector3 {
    double x;
    double y;
    double z;
} vector3_t;

// vector3_magnitude returns the length of a 3D vector.
double vector3_magnitude(vector3_t v) {
    return sqrt(v.x * v.x + v.y * v.y + v.z * v.z);
}

// vector3_dot returns the dot product of two 3D vectors.
double vector3_dot(vector3_t a, vector3_t b) {
    return a.x * b.x + a.y * b.y + a.z * b.z;
}

typedef struct bank_account {
    char owner[64];
    double balance;
} bank_account_t;

// account_deposit adds a positive amount to the balance.
void account_deposit(bank_account_t *account, double amount) {
    if (amount > 0.0) account->balance += amount;
}

// account_withdraw removes amount when sufficient funds exist.
bool account_withdraw(bank_account_t *account, double amount) {
    if (amount <= 0.0 || amount > account->balance) return false;
    account->balance -= amount;
    return true;
}

typedef struct fraction {
    long numerator;
    long denominator;
} fraction_t;

// fraction_reduce returns the fraction in lowest terms.
fraction_t fraction_reduce(fraction_t f) {
    long a = f.numerator, b = f.denominator;
    while (b != 0) {
        long t = a % b;
        a = b;
        b = t;
    }
    long gcd = a < 0 ? -a : a;
    if (gcd == 0) gcd = 1;
    fraction_t result = {f.numerator / gcd, f.denominator / gcd};
    return result;
}

typedef struct rgb_color {
    unsigned char red;
    unsigned char green;
    unsigned char blue;
} rgb_color_t;

// rgb_to_hex formats an RGB color as "#RRGGBB".
void rgb_to_hex(rgb_color_t color, char *out, size_t cap) {
    snprintf(out, cap, "#%02X%02X%02X", color.red, color.green, color.blue);
}
