// filesystem.c — generated by scripts/generate/generate-c.mjs (do not edit by hand).
// Realistic C typing blocks for vibetyper: filesystem and file I/O helpers.

#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

// fs_file_exists reports whether a path is readable.
bool fs_file_exists(const char *path) {
    FILE *fp = fopen(path, "rb");
    if (fp == NULL) return false;
    fclose(fp);
    return true;
}

// fs_file_size returns the size of a file in bytes, or -1 on error.
long fs_file_size(const char *path) {
    struct stat info;
    if (stat(path, &info) != 0) return -1;
    return (long)info.st_size;
}

// fs_read_file loads an entire file into a NUL-terminated heap buffer.
char *fs_read_file(const char *path, size_t *size_out) {
    FILE *fp = fopen(path, "rb");
    if (fp == NULL) return NULL;
    fseek(fp, 0, SEEK_END);
    long length = ftell(fp);
    fseek(fp, 0, SEEK_SET);
    char *buf = malloc((size_t)length + 1);
    if (buf == NULL) { fclose(fp); return NULL; }
    size_t got = fread(buf, 1, (size_t)length, fp);
    buf[got] = '\0';
    fclose(fp);
    if (size_out) *size_out = got;
    return buf;
}

// fs_write_file writes size bytes of data to path, returning success.
bool fs_write_file(const char *path, const void *data, size_t size) {
    FILE *fp = fopen(path, "wb");
    if (fp == NULL) return false;
    size_t written = fwrite(data, 1, size, fp);
    fclose(fp);
    return written == size;
}

// fs_count_lines returns the number of newline characters in a file.
long fs_count_lines(const char *path) {
    FILE *fp = fopen(path, "r");
    if (fp == NULL) return -1;
    long lines = 0;
    int ch;
    while ((ch = fgetc(fp)) != EOF) {
        if (ch == '\n') lines++;
    }
    fclose(fp);
    return lines;
}

// fs_copy_file copies src to dst using a fixed-size buffer.
bool fs_copy_file(const char *src, const char *dst) {
    FILE *in = fopen(src, "rb");
    if (in == NULL) return false;
    FILE *out = fopen(dst, "wb");
    if (out == NULL) { fclose(in); return false; }
    char buf[4096];
    size_t n;
    while ((n = fread(buf, 1, sizeof(buf), in)) > 0) {
        if (fwrite(buf, 1, n, out) != n) { fclose(in); fclose(out); return false; }
    }
    fclose(in);
    fclose(out);
    return true;
}

// fs_append_line appends line plus a newline to the end of a file.
bool fs_append_line(const char *path, const char *line) {
    FILE *fp = fopen(path, "a");
    if (fp == NULL) return false;
    int ok = fprintf(fp, "%s\n", line) >= 0;
    fclose(fp);
    return ok;
}

// fs_read_first_line reads the first line (without its newline) into buf.
bool fs_read_first_line(const char *path, char *buf, size_t cap) {
    FILE *fp = fopen(path, "r");
    if (fp == NULL || fgets(buf, (int)cap, fp) == NULL) {
        if (fp) fclose(fp);
        return false;
    }
    fclose(fp);
    size_t len = strlen(buf);
    while (len > 0 && (buf[len - 1] == '\n' || buf[len - 1] == '\r')) buf[--len] = '\0';
    return true;
}

// fs_get_basename returns the final path component after the last '/'.
const char *fs_get_basename(const char *path) {
    const char *slash = strrchr(path, '/');
    return slash == NULL ? path : slash + 1;
}

// fs_get_extension returns the suffix after the last '.', or "".
const char *fs_get_extension(const char *path) {
    const char *base = fs_get_basename(path);
    const char *dot = strrchr(base, '.');
    return dot == NULL || dot == base ? "" : dot + 1;
}

// fs_get_directory copies the directory portion of path into dir.
bool fs_get_directory(const char *path, char *dir, size_t cap) {
    const char *slash = strrchr(path, '/');
    if (slash == NULL) { dir[0] = '.'; dir[1] = '\0'; return false; }
    size_t len = (size_t)(slash - path);
    if (len == 0) len = 1;
    if (len + 1 > cap) return false;
    memcpy(dir, path, len);
    dir[len] = '\0';
    return true;
}

// fs_path_join concatenates dir and name with a single '/'.
char *fs_path_join(const char *dir, const char *name) {
    size_t dlen = strlen(dir);
    bool needs_slash = dlen > 0 && dir[dlen - 1] != '/';
    char *joined = malloc(dlen + (needs_slash ? 1 : 0) + strlen(name) + 1);
    if (joined == NULL) return NULL;
    memcpy(joined, dir, dlen);
    size_t pos = dlen;
    if (needs_slash) joined[pos++] = '/';
    strcpy(joined + pos, name);
    return joined;
}

// fs_is_directory reports whether path names a directory.
bool fs_is_directory(const char *path) {
    struct stat info;
    return stat(path, &info) == 0 && S_ISDIR(info.st_mode);
}

// fs_remove_file deletes a file, returning true on success.
bool fs_remove_file(const char *path) {
    return remove(path) == 0;
}

// fs_count_words counts whitespace-delimited words in a text file.
long fs_count_words(const char *path) {
    FILE *fp = fopen(path, "r");
    if (fp == NULL) return -1;
    long words = 0;
    bool in_word = false;
    int ch;
    while ((ch = fgetc(fp)) != EOF) {
        bool ws = ch == ' ' || ch == '\t' || ch == '\n' || ch == '\r';
        if (!ws && !in_word) { words++; in_word = true; }
        else if (ws) in_word = false;
    }
    fclose(fp);
    return words;
}

// fs_files_identical compares two files byte by byte.
bool fs_files_identical(const char *a, const char *b) {
    FILE *fa = fopen(a, "rb");
    FILE *fb = fopen(b, "rb");
    if (fa == NULL || fb == NULL) {
        if (fa) fclose(fa);
        if (fb) fclose(fb);
        return false;
    }
    int ca, cb;
    do {
        ca = fgetc(fa);
        cb = fgetc(fb);
        if (ca != cb) { fclose(fa); fclose(fb); return false; }
    } while (ca != EOF);
    fclose(fa);
    fclose(fb);
    return true;
}

// fs_temp_name writes a unique temporary path using the process id.
void fs_temp_name(char *buf, size_t cap) {
    snprintf(buf, cap, "/tmp/vibetyper-%ld.tmp", (long)getpid());
}

// fs_read_all_lines loads every line of a file into an allocated array,
// returning the line count (caller frees each line and the array).
long fs_read_all_lines(const char *path, char ***lines_out) {
    FILE *fp = fopen(path, "r");
    if (fp == NULL) return -1;
    size_t capacity = 16, count = 0;
    char **lines = malloc(capacity * sizeof(char *));
    if (lines == NULL) { fclose(fp); return -1; }
    char line[1024];
    while (fgets(line, sizeof(line), fp) != NULL) {
        size_t len = strlen(line);
        while (len > 0 && (line[len - 1] == '\n' || line[len - 1] == '\r')) line[--len] = '\0';
        if (count == capacity) {
            capacity *= 2;
            char **grown = realloc(lines, capacity * sizeof(char *));
            if (grown == NULL) break;
            lines = grown;
        }
        lines[count] = malloc(len + 1);
        if (lines[count] == NULL) break;
        memcpy(lines[count], line, len + 1);
        count++;
    }
    fclose(fp);
    *lines_out = lines;
    return (long)count;
}
