// formatting.c — generated by scripts/generate/generate-c.mjs (do not edit by hand).
// Realistic C typing blocks for vibetyper: text and number formatting.

#include <ctype.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

// fmt_hex_dump writes a hex representation of len bytes (e.g. "4d 5a").
size_t fmt_hex_dump(const unsigned char *data, size_t len, char *out, size_t cap) {
    size_t w = 0;
    for (size_t i = 0; i < len && w + 3 < cap; i++) {
        if (i > 0) out[w++] = ' ';
        w += (size_t)snprintf(out + w, cap - w, "%02x", data[i]);
    }
    out[w] = '\0';
    return w;
}

// fmt_bytes_human formats a byte count like "1.50 KiB" or "3.9 GiB".
void fmt_bytes_human(uint64_t bytes, char *out, size_t cap) {
    static const char *units[] = {"B", "KiB", "MiB", "GiB", "TiB"};
    double value = (double)bytes;
    size_t unit = 0;
    while (value >= 1024.0 && unit + 1 < sizeof(units) / sizeof(units[0])) {
        value /= 1024.0;
        unit++;
    }
    snprintf(out, cap, unit == 0 ? "%.0f %s" : "%.2f %s", value, units[unit]);
}

// fmt_duration formats seconds as "hh:mm:ss".
void fmt_duration(long seconds, char *out, size_t cap) {
    long h = seconds / 3600;
    long m = (seconds % 3600) / 60;
    long s = seconds % 60;
    snprintf(out, cap, "%02ld:%02ld:%02ld", h, m, s);
}

// fmt_comma_number writes value with thousands separators (e.g. "1,234,567").
void fmt_comma_number(long long value, char *out, size_t cap) {
    char raw[32];
    snprintf(raw, sizeof(raw), "%lld", value);
    size_t len = strlen(raw);
    size_t groups = (len - 1) / 3;
    size_t total = len + groups;
    if (total + 1 > cap) return;
    out[total] = '\0';
    size_t w = total;
    for (size_t i = len, g = 0; i > 0; i--, g++) {
        out[--w] = raw[i - 1];
        if (g % 3 == 2 && i > 1) out[--w] = ',';
    }
}

// fmt_pad_right copies s into out, right-padding with fill to width.
void fmt_pad_right(const char *s, size_t width, char fill, char *out, size_t cap) {
    size_t len = strlen(s);
    size_t keep = len < cap ? len : cap - 1;
    memcpy(out, s, keep);
    size_t w = keep;
    while (w < width && w + 1 < cap) out[w++] = fill;
    out[w] = '\0';
}

// fmt_center writes s centered within width, padded with fill.
void fmt_center(const char *s, size_t width, char fill, char *out, size_t cap) {
    size_t len = strlen(s);
    size_t left = len < width ? (width - len) / 2 : 0;
    size_t w = 0;
    for (size_t i = 0; i < left && w + 1 < cap; i++) out[w++] = fill;
    for (size_t i = 0; s[i] != '\0' && w + 1 < cap; i++) out[w++] = s[i];
    while (w < width && w + 1 < cap) out[w++] = fill;
    out[w] = '\0';
}

// fmt_fixed_decimal formats value with a fixed number of decimal places.
void fmt_fixed_decimal(double value, int decimals, char *out, size_t cap) {
    char format[16];
    snprintf(format, sizeof(format), "%%.%df", decimals);
    snprintf(out, cap, format, value);
}

// fmt_percent formats a ratio in [0, 1] as "42.5%".
void fmt_percent(double ratio, char *out, size_t cap) {
    snprintf(out, cap, "%.1f%%", ratio * 100.0);
}

// fmt_snake_to_camel converts "some_name" to "someName" in place.
void fmt_snake_to_camel(char *s) {
    char *write = s;
    bool upper_next = false;
    for (char *read = s; *read != '\0'; read++) {
        if (*read == '_') {
            upper_next = true;
        } else if (upper_next) {
            *write++ = (char)toupper((unsigned char)*read);
            upper_next = false;
        } else {
            *write++ = *read;
        }
    }
    *write = '\0';
}

// fmt_camel_to_snake converts "someName" to "some_name" into out.
void fmt_camel_to_snake(const char *s, char *out, size_t cap) {
    size_t w = 0;
    for (const char *p = s; *p != '\0' && w + 2 < cap; p++) {
        if (isupper((unsigned char)*p)) {
            if (w > 0) out[w++] = '_';
            out[w++] = (char)tolower((unsigned char)*p);
        } else {
            out[w++] = *p;
        }
    }
    out[w] = '\0';
}

// fmt_truncate copies s, shortening with an ellipsis when longer than max.
void fmt_truncate(const char *s, size_t max, char *out, size_t cap) {
    size_t len = strlen(s);
    if (len <= max || max < 3) {
        snprintf(out, cap, "%s", s);
        return;
    }
    snprintf(out, cap, "%.*s...", (int)(max - 3), s);
}

// fmt_binary_string writes value in binary with width bits and leading zeros.
void fmt_binary_string(uint32_t value, unsigned int width, char *out, size_t cap) {
    if (width > cap - 1) width = (unsigned int)(cap - 1);
    for (unsigned int i = 0; i < width; i++) {
        out[width - 1 - i] = (value & 1u) ? '1' : '0';
        value >>= 1u;
    }
    out[width] = '\0';
}

// fmt_roman_numeral writes the Roman numeral for value (1-3999) into out.
void fmt_roman_numeral(int value, char *out, size_t cap) {
    static const int vals[] = {1000, 900, 500, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1};
    static const char *syms[] = {"M", "CM", "D", "CD", "C", "XC", "L", "XL", "X", "IX", "V", "IV", "I"};
    out[0] = '\0';
    for (size_t i = 0; i < sizeof(vals) / sizeof(vals[0]); i++) {
        while (value >= vals[i]) {
            strncat(out, syms[i], cap - strlen(out) - 1);
            value -= vals[i];
        }
    }
}

// fmt_ordinal formats a number with its English suffix ("1st", "22nd").
void fmt_ordinal(int n, char *out, size_t cap) {
    const char *suffix = "th";
    int last = n % 10;
    int second = (n / 10) % 10;
    if (second != 1) {
        if (last == 1) suffix = "st";
        else if (last == 2) suffix = "nd";
        else if (last == 3) suffix = "rd";
    }
    snprintf(out, cap, "%d%s", n, suffix);
}

// fmt_url_encode percent-encodes s, leaving alphanumerics and "-_.~" as-is.
void fmt_url_encode(const char *s, char *out, size_t cap) {
    size_t w = 0;
    for (const char *p = s; *p != '\0' && w + 4 < cap; p++) {
        unsigned char c = (unsigned char)*p;
        if (isalnum(c) || c == '-' || c == '_' || c == '.' || c == '~') {
            out[w++] = (char)c;
        } else {
            w += (size_t)snprintf(out + w, cap - w, "%%%02X", c);
        }
    }
    out[w] = '\0';
}

// fmt_base64_encode encodes len bytes using the standard alphabet, writing
// unpadded base64 text into out and returning its length.
size_t fmt_base64_encode(const unsigned char *data, size_t len, char *out, size_t cap) {
    static const char table[] =
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    size_t w = 0;
    for (size_t i = 0; i < len; i += 3) {
        uint32_t chunk = (uint32_t)data[i] << 16;
        if (i + 1 < len) chunk |= (uint32_t)data[i + 1] << 8;
        if (i + 2 < len) chunk |= data[i + 2];
        if (w + 4 < cap) out[w++] = table[(chunk >> 18) & 0x3F];
        if (w + 4 < cap) out[w++] = table[(chunk >> 12) & 0x3F];
        if (i + 1 < len && w + 4 < cap) out[w++] = table[(chunk >> 6) & 0x3F];
        if (i + 2 < len && w + 4 < cap) out[w++] = table[chunk & 0x3F];
    }
    out[w] = '\0';
    return w;
}

// fmt_rgb_hex formats an RGB color as "#RRGGBB".
void fmt_rgb_hex(unsigned char r, unsigned char g, unsigned char b, char *out, size_t cap) {
    snprintf(out, cap, "#%02X%02X%02X", r, g, b);
}

// fmt_repeat_char writes ch repeated count times, NUL-terminating the buffer.
size_t fmt_repeat_char(char ch, size_t count, char *out, size_t cap) {
    size_t n = count < cap - 1 ? count : cap - 1;
    for (size_t i = 0; i < n; i++) out[i] = ch;
    out[n] = '\0';
    return n;
}
