// hash_table.c — generated by scripts/generate/generate-c.mjs (do not edit by hand).
// Realistic C typing blocks for vibetyper: string-keyed hash table.

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

typedef struct ht_entry {
    char *key;
    int value;
    struct ht_entry *next;
} ht_entry_t;

typedef struct hash_table {
    ht_entry_t **buckets;
    size_t bucket_count;
    size_t size;
} hash_table_t;

// hash_djb2 computes the classic Dan Bernstein string hash.
uint64_t hash_djb2(const char *key) {
    uint64_t hash = 5381;
    int c;
    while ((c = (unsigned char)*key++) != 0) {
        hash = ((hash << 5) + hash) + (uint64_t)c;
    }
    return hash;
}

// hash_fnv1a computes the 64-bit FNV-1a string hash.
uint64_t hash_fnv1a(const char *key) {
    uint64_t hash = 0xcbf29ce484222325ULL;
    while (*key != '\0') {
        hash ^= (unsigned char)*key++;
        hash *= 0x100000001b3ULL;
    }
    return hash;
}

// ht_create allocates a hash table with the given number of buckets.
hash_table_t *ht_create(size_t bucket_count) {
    hash_table_t *table = calloc(1, sizeof(hash_table_t));
    if (table == NULL) return NULL;
    table->buckets = calloc(bucket_count, sizeof(ht_entry_t *));
    if (table->buckets == NULL) { free(table); return NULL; }
    table->bucket_count = bucket_count;
    return table;
}

// ht_put inserts or updates the value stored under key.
bool ht_put(hash_table_t *table, const char *key, int value) {
    size_t index = (size_t)(hash_fnv1a(key) % table->bucket_count);
    ht_entry_t *entry = table->buckets[index];
    while (entry != NULL) {
        if (strcmp(entry->key, key) == 0) {
            entry->value = value;
            return true;
        }
        entry = entry->next;
    }
    entry = malloc(sizeof(ht_entry_t));
    if (entry == NULL) return false;
    size_t key_len = strlen(key) + 1;
    entry->key = malloc(key_len);
    if (entry->key == NULL) { free(entry); return false; }
    memcpy(entry->key, key, key_len);
    entry->value = value;
    entry->next = table->buckets[index];
    table->buckets[index] = entry;
    table->size++;
    return true;
}

// ht_get stores the value for key into out and returns true when present.
bool ht_get(const hash_table_t *table, const char *key, int *out) {
    size_t index = (size_t)(hash_fnv1a(key) % table->bucket_count);
    for (const ht_entry_t *entry = table->buckets[index]; entry != NULL; entry = entry->next) {
        if (strcmp(entry->key, key) == 0) {
            if (out != NULL) *out = entry->value;
            return true;
        }
    }
    return false;
}

// ht_remove deletes key from the table and frees its storage.
bool ht_remove(hash_table_t *table, const char *key) {
    size_t index = (size_t)(hash_fnv1a(key) % table->bucket_count);
    ht_entry_t **indirect = &table->buckets[index];
    while (*indirect != NULL) {
        if (strcmp((*indirect)->key, key) == 0) {
            ht_entry_t *victim = *indirect;
            *indirect = victim->next;
            free(victim->key);
            free(victim);
            table->size--;
            return true;
        }
        indirect = &(*indirect)->next;
    }
    return false;
}

// ht_contains reports whether key is present in the table.
bool ht_contains(const hash_table_t *table, const char *key) {
    return ht_get(table, key, NULL);
}

// ht_size returns the number of key/value pairs stored.
size_t ht_size(const hash_table_t *table) {
    return table->size;
}

// ht_free releases every entry, its key, the bucket array, and the table.
void ht_free(hash_table_t *table) {
    if (table == NULL) return;
    for (size_t i = 0; i < table->bucket_count; i++) {
        ht_entry_t *entry = table->buckets[i];
        while (entry != NULL) {
            ht_entry_t *next = entry->next;
            free(entry->key);
            free(entry);
            entry = next;
        }
    }
    free(table->buckets);
    free(table);
}

// ht_load_factor returns the ratio of entries to buckets.
double ht_load_factor(const hash_table_t *table) {
    return table->bucket_count == 0 ? 0.0 : (double)table->size / (double)table->bucket_count;
}

// ht_keys collects every key into an allocated array and returns the count.
size_t ht_keys(const hash_table_t *table, char ***keys_out) {
    char **keys = malloc((table->size + 1) * sizeof(char *));
    if (keys == NULL) return 0;
    size_t w = 0;
    for (size_t i = 0; i < table->bucket_count; i++) {
        for (const ht_entry_t *entry = table->buckets[i]; entry != NULL; entry = entry->next) {
            size_t len = strlen(entry->key) + 1;
            keys[w] = malloc(len);
            if (keys[w] == NULL) break;
            memcpy(keys[w], entry->key, len);
            w++;
        }
    }
    keys[w] = NULL;
    *keys_out = keys;
    return w;
}

// ht_collision_count counts entries sharing a bucket with another key.
size_t ht_collision_count(const hash_table_t *table) {
    size_t collisions = 0;
    for (size_t i = 0; i < table->bucket_count; i++) {
        size_t chain = 0;
        for (const ht_entry_t *entry = table->buckets[i]; entry != NULL; entry = entry->next) chain++;
        if (chain > 1) collisions += chain - 1;
    }
    return collisions;
}
