// heap.c — generated by scripts/generate/generate-c.mjs (do not edit by hand).
// Realistic C typing blocks for vibetyper: binary min-heap.

#include <stdbool.h>
#include <stddef.h>
#include <stdlib.h>

typedef struct heap {
    int *items;
    size_t capacity;
    size_t count;
} heap_t;

// heap_create allocates a min-heap with room for capacity items.
heap_t *heap_create(size_t capacity) {
    heap_t *h = malloc(sizeof(heap_t));
    if (h == NULL) return NULL;
    h->items = malloc(capacity * sizeof(int));
    if (h->items == NULL) { free(h); return NULL; }
    h->capacity = capacity;
    h->count = 0;
    return h;
}

// heap_sift_up bubbles the item at index toward the root to restore
// the min-heap invariant.
static void heap_sift_up(int *items, size_t index) {
    while (index > 0) {
        size_t parent = (index - 1) / 2;
        if (items[parent] <= items[index]) break;
        int tmp = items[parent];
        items[parent] = items[index];
        items[index] = tmp;
        index = parent;
    }
}

// heap_sift_down pushes the item at index toward the leaves.
static void heap_sift_down(int *items, size_t count, size_t index) {
    for (;;) {
        size_t left = 2 * index + 1;
        size_t right = left + 1;
        size_t smallest = index;
        if (left < count && items[left] < items[smallest]) smallest = left;
        if (right < count && items[right] < items[smallest]) smallest = right;
        if (smallest == index) break;
        int tmp = items[index];
        items[index] = items[smallest];
        items[smallest] = tmp;
        index = smallest;
    }
}

// heap_push inserts value; returns false when the heap is full.
bool heap_push(heap_t *h, int value) {
    if (h->count >= h->capacity) return false;
    h->items[h->count] = value;
    heap_sift_up(h->items, h->count);
    h->count++;
    return true;
}

// heap_pop removes and returns the minimum value via out.
bool heap_pop(heap_t *h, int *out) {
    if (h->count == 0) return false;
    *out = h->items[0];
    h->items[0] = h->items[--h->count];
    heap_sift_down(h->items, h->count, 0);
    return true;
}

// heap_peek reads the minimum value without removing it.
bool heap_peek(const heap_t *h, int *out) {
    if (h->count == 0) return false;
    *out = h->items[0];
    return true;
}

// heap_size returns the number of items currently held.
size_t heap_size(const heap_t *h) {
    return h->count;
}

// heap_is_empty reports whether the heap holds no items.
bool heap_is_empty(const heap_t *h) {
    return h->count == 0;
}

// heap_free releases the heap and its backing array.
void heap_free(heap_t *h) {
    if (h == NULL) return;
    free(h->items);
    free(h);
}

// heap_build rearranges an array of count items into a valid min-heap.
void heap_build(int *items, size_t count) {
    for (size_t i = count / 2; i-- > 0;) {
        heap_sift_down(items, count, i);
    }
}

// heap_sort sorts values ascending in place using an in-array max-heap.
void heap_sort(int *values, size_t count) {
    if (count < 2) return;
    for (size_t start = count / 2; start > 0;) {
        start--;
        size_t i = start;
        for (;;) {
            size_t child = 2 * i + 1;
            if (child >= count) break;
            if (child + 1 < count && values[child + 1] > values[child]) child++;
            if (values[child] <= values[i]) break;
            int tmp = values[i];
            values[i] = values[child];
            values[child] = tmp;
            i = child;
        }
    }
    for (size_t end = count - 1; end > 0; end--) {
        int tmp = values[0];
        values[0] = values[end];
        values[end] = tmp;
        size_t i = 0;
        for (;;) {
            size_t child = 2 * i + 1;
            if (child >= end) break;
            if (child + 1 < end && values[child + 1] > values[child]) child++;
            if (values[child] <= values[i]) break;
            int tmp2 = values[i];
            values[i] = values[child];
            values[child] = tmp2;
            i = child;
        }
    }
}

// heap_replace removes the minimum, inserts value, and returns the old min.
bool heap_replace(heap_t *h, int value, int *out) {
    if (h->count == 0) return heap_push(h, value);
    *out = h->items[0];
    h->items[0] = value;
    heap_sift_down(h->items, h->count, 0);
    return true;
}
