// linked_list.c — generated by scripts/generate/generate-c.mjs (do not edit by hand).
// Realistic C typing blocks for vibetyper: singly linked list.

#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>

typedef struct list_node {
    int value;
    struct list_node *next;
} list_node_t;

// list_push_front inserts value at the head and returns the new node.
list_node_t *list_push_front(list_node_t **head, int value) {
    list_node_t *node = malloc(sizeof(list_node_t));
    if (node == NULL) return NULL;
    node->value = value;
    node->next = *head;
    *head = node;
    return node;
}

// list_push_back appends value at the tail and returns the new node.
list_node_t *list_push_back(list_node_t **head, int value) {
    list_node_t *node = malloc(sizeof(list_node_t));
    if (node == NULL) return NULL;
    node->value = value;
    node->next = NULL;
    if (*head == NULL) {
        *head = node;
    } else {
        list_node_t *tail = *head;
        while (tail->next != NULL) tail = tail->next;
        tail->next = node;
    }
    return node;
}

// list_pop_front removes the head node, storing its value and freeing it.
bool list_pop_front(list_node_t **head, int *out) {
    if (*head == NULL) return false;
    list_node_t *old = *head;
    *head = old->next;
    if (out != NULL) *out = old->value;
    free(old);
    return true;
}

// list_find returns the first node matching value, or NULL.
list_node_t *list_find(const list_node_t *head, int value) {
    for (const list_node_t *p = head; p != NULL; p = p->next) {
        if (p->value == value) return (list_node_t *)p;
    }
    return NULL;
}

// list_remove deletes the first node matching value; returns true if found.
bool list_remove(list_node_t **head, int value) {
    list_node_t **indirect = head;
    while (*indirect != NULL && (*indirect)->value != value) {
        indirect = &(*indirect)->next;
    }
    if (*indirect == NULL) return false;
    list_node_t *victim = *indirect;
    *indirect = victim->next;
    free(victim);
    return true;
}

// list_length returns the number of nodes in the list.
size_t list_length(const list_node_t *head) {
    size_t n = 0;
    for (const list_node_t *p = head; p != NULL; p = p->next) n++;
    return n;
}

// list_reverse reverses the list in place.
void list_reverse(list_node_t **head) {
    list_node_t *prev = NULL, *curr = *head;
    while (curr != NULL) {
        list_node_t *next = curr->next;
        curr->next = prev;
        prev = curr;
        curr = next;
    }
    *head = prev;
}

// list_free frees every node in the list.
void list_free(list_node_t *head) {
    while (head != NULL) {
        list_node_t *next = head->next;
        free(head);
        head = next;
    }
}

// list_append concatenates tail onto the end of the list at head.
void list_append(list_node_t **head, list_node_t *tail) {
    if (*head == NULL) {
        *head = tail;
        return;
    }
    list_node_t *last = *head;
    while (last->next != NULL) last = last->next;
    last->next = tail;
}

// list_nth returns the node at zero-based index, or NULL if out of range.
list_node_t *list_nth(list_node_t *head, size_t index) {
    size_t i = 0;
    for (list_node_t *p = head; p != NULL; p = p->next, i++) {
        if (i == index) return p;
    }
    return NULL;
}

// list_has_cycle detects a loop with Floyd's tortoise-and-hare algorithm.
bool list_has_cycle(const list_node_t *head) {
    const list_node_t *slow = head, *fast = head;
    while (fast != NULL && fast->next != NULL) {
        slow = slow->next;
        fast = fast->next->next;
        if (slow == fast) return true;
    }
    return false;
}

// list_middle returns the middle node using the fast/slow pointer trick.
list_node_t *list_middle(list_node_t *head) {
    list_node_t *slow = head, *fast = head;
    while (fast != NULL && fast->next != NULL) {
        slow = slow->next;
        fast = fast->next->next;
    }
    return slow;
}

// list_insert_sorted inserts value into a list kept in ascending order.
void list_insert_sorted(list_node_t **head, int value) {
    list_node_t *node = malloc(sizeof(list_node_t));
    if (node == NULL) return;
    node->value = value;
    while (*head != NULL && (*head)->value < value) head = &(*head)->next;
    node->next = *head;
    *head = node;
}

// list_remove_duplicates removes repeated values, keeping the first of each.
void list_remove_duplicates(list_node_t *head) {
    for (list_node_t *p = head; p != NULL; p = p->next) {
        list_node_t **prev = &p->next;
        while (*prev != NULL) {
            if ((*prev)->value == p->value) {
                list_node_t *dup = *prev;
                *prev = dup->next;
                free(dup);
            } else {
                prev = &(*prev)->next;
            }
        }
    }
}

// list_print writes the list as "1 -> 2 -> 3" followed by a newline.
void list_print(const list_node_t *head) {
    for (const list_node_t *p = head; p != NULL; p = p->next) {
        printf("%d%s", p->value, p->next ? " -> " : "\n");
    }
}
