// math_numeric.c — generated by scripts/generate/generate-c.mjs (do not edit by hand).
// Realistic C typing blocks for vibetyper: math and numeric utilities.

#include <math.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// math_gcd returns the greatest common divisor of a and b (Euclid).
int math_gcd(int a, int b) {
    while (b != 0) {
        int t = a % b;
        a = b;
        b = t;
    }
    return a < 0 ? -a : a;
}

// math_lcm returns the least common multiple of a and b.
int math_lcm(int a, int b) {
    int g = math_gcd(a, b);
    return g == 0 ? 0 : (a / g) * b;
}

// math_factorial returns n! as a 64-bit value (overflow is caller's concern).
uint64_t math_factorial(unsigned int n) {
    uint64_t result = 1;
    for (unsigned int i = 2; i <= n; i++) result *= i;
    return result;
}

// math_fibonacci returns the nth Fibonacci number, F(0) = 0.
uint64_t math_fibonacci(unsigned int n) {
    uint64_t a = 0, b = 1;
    for (unsigned int i = 0; i < n; i++) {
        uint64_t next = a + b;
        a = b;
        b = next;
    }
    return a;
}

// math_is_prime tests primality with trial division by odd factors.
bool math_is_prime(uint64_t n) {
    if (n < 2) return false;
    if (n % 2 == 0) return n == 2;
    for (uint64_t d = 3; d * d <= n; d += 2) {
        if (n % d == 0) return false;
    }
    return true;
}

// math_next_prime returns the smallest prime greater than n.
uint64_t math_next_prime(uint64_t n) {
    uint64_t candidate = n < 2 ? 2 : n + 1;
    if (candidate > 2 && candidate % 2 == 0) candidate++;
    while (!math_is_prime(candidate)) candidate += 2;
    return candidate;
}

// math_isqrt returns floor(sqrt(n)) using Newton's method.
uint64_t math_isqrt(uint64_t n) {
    if (n < 2) return n;
    uint64_t x = n, y = (x + 1) / 2;
    while (y < x) {
        x = y;
        y = (y + n / y) / 2;
    }
    return x;
}

// math_pow_int raises base to exp using exponentiation by squaring.
int64_t math_pow_int(int64_t base, unsigned int exp) {
    int64_t result = 1;
    while (exp > 0) {
        if (exp & 1u) result *= base;
        base *= base;
        exp >>= 1u;
    }
    return result;
}

// math_is_perfect_square reports whether n is an exact square.
bool math_is_perfect_square(uint64_t n) {
    uint64_t r = math_isqrt(n);
    return r * r == n;
}

// math_sum_digits sums the decimal digits of n.
unsigned int math_sum_digits(uint64_t n) {
    unsigned int sum = 0;
    while (n > 0) {
        sum += (unsigned int)(n % 10);
        n /= 10;
    }
    return sum;
}

// math_reverse_digits reverses the decimal digits of n.
uint64_t math_reverse_digits(uint64_t n) {
    uint64_t reversed = 0;
    while (n > 0) {
        reversed = reversed * 10 + n % 10;
        n /= 10;
    }
    return reversed;
}

// math_count_digits counts the decimal digits of n.
unsigned int math_count_digits(uint64_t n) {
    unsigned int count = n == 0 ? 1 : 0;
    while (n > 0) {
        count++;
        n /= 10;
    }
    return count;
}

// math_is_armstrong reports whether n equals the sum of its digits
// each raised to the power of the digit count.
bool math_is_armstrong(uint64_t n) {
    unsigned int digits = math_count_digits(n);
    uint64_t sum = 0, rest = n;
    while (rest > 0) {
        unsigned int d = (unsigned int)(rest % 10);
        sum += (uint64_t)math_pow_int(d, digits);
        rest /= 10;
    }
    return sum == n;
}

// math_is_palindrome_number reports whether n reads the same reversed.
bool math_is_palindrome_number(uint64_t n) {
    return n == math_reverse_digits(n);
}

// math_random_range returns a uniform integer in [min, max].
int math_random_range(int min, int max) {
    if (min > max) {
        int t = min;
        min = max;
        max = t;
    }
    return min + rand() % (max - min + 1);
}

// math_clamp constrains value to the inclusive range [low, high].
int math_clamp(int value, int low, int high) {
    if (value < low) return low;
    if (value > high) return high;
    return value;
}

// math_lerp linearly interpolates between a and b by t in [0, 1].
double math_lerp(double a, double b, double t) {
    return a + (b - a) * t;
}

// math_solve_quadratic solves ax^2 + bx + c = 0, storing up to two real
// roots in roots and returning the number of real roots found.
int math_solve_quadratic(double a, double b, double c, double roots[2]) {
    if (a == 0.0) {
        if (b == 0.0) return 0;
        roots[0] = -c / b;
        return 1;
    }
    double disc = b * b - 4.0 * a * c;
    if (disc < 0.0) return 0;
    if (disc == 0.0) {
        roots[0] = -b / (2.0 * a);
        return 1;
    }
    double s = sqrt(disc);
    roots[0] = (-b - s) / (2.0 * a);
    roots[1] = (-b + s) / (2.0 * a);
    return 2;
}

// math_sieve_count_primes counts primes <= limit with a byte sieve.
size_t math_sieve_count_primes(uint64_t limit) {
    if (limit < 2) return 0;
    unsigned char *composite = calloc((size_t)limit + 1, 1);
    if (composite == NULL) return 0;
    size_t count = 0;
    for (uint64_t i = 2; i <= limit; i++) {
        if (!composite[i]) {
            count++;
            for (uint64_t j = i * i; j <= limit; j += i) composite[j] = 1;
        }
    }
    free(composite);
    return count;
}

// math_round_to_nearest rounds value to the nearest multiple of step.
long math_round_to_nearest(long value, long step) {
    if (step <= 0) return value;
    long remainder = value % step;
    if (remainder * 2 >= step) return value + (step - remainder);
    return value - remainder;
}
