// memory_utils.c — generated by scripts/generate/generate-c.mjs (do not edit by hand).
// Realistic C typing blocks for vibetyper: memory utilities.

#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// mem_alloc_zero allocates and zeroes count elements of size bytes each,
// exiting on failure so callers need not check for NULL.
void *mem_alloc_zero(size_t count, size_t size) {
    void *ptr = calloc(count, size);
    if (ptr == NULL && count > 0 && size > 0) {
        fprintf(stderr, "calloc(%zu, %zu) failed\n", count, size);
        exit(EXIT_FAILURE);
    }
    return ptr;
}

// mem_resize grows or shrinks an allocation, freeing it on failure.
void *mem_resize(void *ptr, size_t new_size) {
    void *grown = realloc(ptr, new_size);
    if (grown == NULL) {
        free(ptr);
        return NULL;
    }
    return grown;
}

// mem_zero fills a buffer with zero bytes.
void mem_zero(void *ptr, size_t size) {
    memset(ptr, 0, size);
}

// mem_reverse_bytes reverses the byte order of an in-memory buffer.
void mem_reverse_bytes(void *buf, size_t size) {
    unsigned char *p = buf;
    for (size_t i = 0; i < size / 2; i++) {
        unsigned char tmp = p[i];
        p[i] = p[size - 1 - i];
        p[size - 1 - i] = tmp;
    }
}

// mem_compare compares two buffers lexicographically.
int mem_compare(const void *a, const void *b, size_t size) {
    return memcmp(a, b, size);
}

// mem_find_byte returns the offset of the first matching byte, or -1.
long mem_find_byte(const void *buf, size_t size, unsigned char needle) {
    const unsigned char *p = memchr(buf, needle, size);
    return p == NULL ? -1 : (long)(p - (const unsigned char *)buf);
}

// mem_contains reports whether needle appears within haystack.
bool mem_contains(const void *haystack, size_t haystack_size, const void *needle, size_t needle_size) {
    if (needle_size == 0 || needle_size > haystack_size) return false;
    const unsigned char *h = haystack;
    for (size_t i = 0; i + needle_size <= haystack_size; i++) {
        if (memcmp(h + i, needle, needle_size) == 0) return true;
    }
    return false;
}

// mem_clone returns a heap copy of size bytes, or NULL on failure.
void *mem_clone(const void *src, size_t size) {
    void *copy = malloc(size);
    if (copy == NULL) return NULL;
    memcpy(copy, src, size);
    return copy;
}

// mem_grow_array reallocates an array when count reaches capacity, doubling
// capacity; returns the possibly-moved pointer or NULL on failure.
void *mem_grow_array(void *ptr, size_t element_size, size_t count, size_t *capacity) {
    if (count < *capacity) return ptr;
    size_t next = *capacity == 0 ? 8 : *capacity * 2;
    void *grown = realloc(ptr, next * element_size);
    if (grown == NULL) return NULL;
    *capacity = next;
    return grown;
}

// mem_align_up rounds size up to the next multiple of alignment.
size_t mem_align_up(size_t size, size_t alignment) {
    size_t remainder = size % alignment;
    return remainder == 0 ? size : size + (alignment - remainder);
}

// mem_all_zero reports whether every byte of a buffer is zero.
bool mem_all_zero(const void *buf, size_t size) {
    const unsigned char *p = buf;
    for (size_t i = 0; i < size; i++) {
        if (p[i] != 0) return false;
    }
    return true;
}

// mem_fill_pattern repeats a byte pattern across the destination buffer.
void mem_fill_pattern(void *dst, size_t size, const unsigned char *pattern, size_t pattern_size) {
    unsigned char *p = dst;
    for (size_t i = 0; i < size; i++) p[i] = pattern[i % pattern_size];
}

// mem_copy_str copies a NUL-terminated string into a heap buffer.
char *mem_copy_str(const char *src) {
    size_t len = strlen(src) + 1;
    char *copy = malloc(len);
    if (copy == NULL) return NULL;
    memcpy(copy, src, len);
    return copy;
}

// mem_swap exchanges the contents of two equally sized buffers.
void mem_swap(void *a, void *b, size_t size) {
    unsigned char *pa = a, *pb = b;
    for (size_t i = 0; i < size; i++) {
        unsigned char tmp = pa[i];
        pa[i] = pb[i];
        pb[i] = tmp;
    }
}

// mem_trim reallocates a buffer down to an exact size, preserving contents.
void *mem_trim(void *ptr, size_t size) {
    return realloc(ptr, size);
}

// mem_concat joins two byte buffers into a single heap allocation.
void *mem_concat(const void *a, size_t na, const void *b, size_t nb) {
    void *joined = malloc(na + nb);
    if (joined == NULL) return NULL;
    memcpy(joined, a, na);
    memcpy((unsigned char *)joined + na, b, nb);
    return joined;
}
