// networking.c — generated by scripts/generate/generate-c.mjs (do not edit by hand).
// Realistic C typing blocks for vibetyper: POSIX socket networking helpers.

#include <arpa/inet.h>
#include <errno.h>
#include <fcntl.h>
#include <netdb.h>
#include <netinet/in.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/time.h>
#include <sys/types.h>
#include <unistd.h>

// net_create_tcp_socket opens an IPv4 stream socket, or returns -1.
int net_create_tcp_socket(void) {
    return socket(AF_INET, SOCK_STREAM, 0);
}

// net_bind_and_listen binds a socket to any interface and starts listening.
int net_bind_and_listen(int sock, unsigned short port, int backlog) {
    struct sockaddr_in addr;
    memset(&addr, 0, sizeof(addr));
    addr.sin_family = AF_INET;
    addr.sin_addr.s_addr = htonl(INADDR_ANY);
    addr.sin_port = htons(port);
    if (bind(sock, (struct sockaddr *)&addr, sizeof(addr)) < 0) return -1;
    return listen(sock, backlog);
}

// net_connect_to opens a connection to host:port, returning the socket.
int net_connect_to(const char *host, unsigned short port) {
    int sock = net_create_tcp_socket();
    if (sock < 0) return -1;
    struct sockaddr_in addr;
    memset(&addr, 0, sizeof(addr));
    addr.sin_family = AF_INET;
    addr.sin_port = htons(port);
    if (inet_pton(AF_INET, host, &addr.sin_addr) != 1) {
        close(sock);
        return -1;
    }
    if (connect(sock, (struct sockaddr *)&addr, sizeof(addr)) < 0) {
        close(sock);
        return -1;
    }
    return sock;
}

// net_send_all sends the entire buffer, handling partial writes.
ssize_t net_send_all(int sock, const void *buf, size_t len) {
    const char *p = buf;
    size_t sent = 0;
    while (sent < len) {
        ssize_t n = send(sock, p + sent, len - sent, 0);
        if (n < 0) return -1;
        sent += (size_t)n;
    }
    return (ssize_t)sent;
}

// net_recv_line reads one CR/LF-terminated line into buf, without the newline.
ssize_t net_recv_line(int sock, char *buf, size_t cap) {
    size_t got = 0;
    while (got + 1 < cap) {
        char c;
        ssize_t n = recv(sock, &c, 1, 0);
        if (n <= 0) return n;
        if (c == '\n') break;
        if (c != '\r') buf[got++] = c;
    }
    buf[got] = '\0';
    return (ssize_t)got;
}

// net_set_reuseaddr allows a listening socket to rebind after restart.
int net_set_reuseaddr(int sock) {
    int opt = 1;
    return setsockopt(sock, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));
}

// net_set_nonblocking toggles a socket into non-blocking mode.
int net_set_nonblocking(int sock) {
    int flags = fcntl(sock, F_GETFL, 0);
    if (flags < 0) return -1;
    return fcntl(sock, F_SETFL, flags | O_NONBLOCK);
}

// net_hostname_to_ip resolves host and stores the first IPv4 string in ip.
int net_hostname_to_ip(const char *host, char *ip, size_t cap) {
    struct addrinfo hints, *result = NULL;
    memset(&hints, 0, sizeof(hints));
    hints.ai_family = AF_INET;
    hints.ai_socktype = SOCK_STREAM;
    if (getaddrinfo(host, NULL, &hints, &result) != 0 || result == NULL) return -1;
    struct sockaddr_in *addr = (struct sockaddr_in *)result->ai_addr;
    const char *text = inet_ntop(AF_INET, &addr->sin_addr, ip, (socklen_t)cap);
    freeaddrinfo(result);
    return text != NULL ? 0 : -1;
}

// net_parse_ipv4 converts "a.b.c.d" into a network-order 32-bit value.
int net_parse_ipv4(const char *text, uint32_t *out) {
    struct in_addr addr;
    if (inet_pton(AF_INET, text, &addr) != 1) return -1;
    *out = addr.s_addr;
    return 0;
}

// net_set_timeout sets the receive timeout for a socket in seconds.
int net_set_timeout(int sock, long seconds) {
    struct timeval tv;
    tv.tv_sec = seconds;
    tv.tv_usec = 0;
    return setsockopt(sock, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));
}

// net_close_socket closes a valid socket descriptor.
void net_close_socket(int sock) {
    if (sock >= 0) close(sock);
}

// net_accept_client accepts a pending connection on a listening socket.
int net_accept_client(int listen_sock) {
    struct sockaddr_in client;
    socklen_t len = sizeof(client);
    return accept(listen_sock, (struct sockaddr *)&client, &len);
}

// net_build_http_request formats a minimal HTTP request into buf.
int net_build_http_request(const char *method, const char *path, const char *host, char *buf, size_t cap) {
    return snprintf(buf, cap,
        "%s %s HTTP/1.1\r\nHost: %s\r\nConnection: close\r\n\r\n",
        method, path, host);
}

// net_parse_http_status extracts the numeric code from a status line.
int net_parse_http_status(const char *line) {
    const char *space = strchr(line, ' ');
    if (space == NULL) return -1;
    return atoi(space + 1);
}

// net_get_port_name looks up the service name for a well-known TCP port.
const char *net_get_port_name(unsigned short port) {
    struct servent *entry = getservbyport(htons(port), "tcp");
    return entry != NULL ? entry->s_name : "unknown";
}

// net_would_block reports whether errno indicates a non-blocking retry.
bool net_would_block(int error) {
    return error == EAGAIN || error == EWOULDBLOCK;
}
