// ring_buffer.c — generated by scripts/generate/generate-c.mjs (do not edit by hand).
// Realistic C typing blocks for vibetyper: circular ring buffer.

#include <stdbool.h>
#include <stddef.h>
#include <stdlib.h>

typedef struct ring_buffer {
    unsigned char *buffer;
    size_t capacity;
    size_t head;
    size_t tail;
} ring_buffer_t;

// rb_create allocates a ring buffer that stores capacity - 1 bytes.
ring_buffer_t *rb_create(size_t capacity) {
    ring_buffer_t *rb = malloc(sizeof(ring_buffer_t));
    if (rb == NULL) return NULL;
    rb->buffer = malloc(capacity);
    if (rb->buffer == NULL) { free(rb); return NULL; }
    rb->capacity = capacity;
    rb->head = rb->tail = 0;
    return rb;
}

// rb_write_byte stores one byte; returns false when the buffer is full.
bool rb_write_byte(ring_buffer_t *rb, unsigned char byte) {
    size_t next = (rb->head + 1) % rb->capacity;
    if (next == rb->tail) return false;
    rb->buffer[rb->head] = byte;
    rb->head = next;
    return true;
}

// rb_read_byte removes and returns the oldest byte via out.
bool rb_read_byte(ring_buffer_t *rb, unsigned char *out) {
    if (rb->head == rb->tail) return false;
    *out = rb->buffer[rb->tail];
    rb->tail = (rb->tail + 1) % rb->capacity;
    return true;
}

// rb_peek reads the oldest byte without removing it.
bool rb_peek(const ring_buffer_t *rb, unsigned char *out) {
    if (rb->head == rb->tail) return false;
    *out = rb->buffer[rb->tail];
    return true;
}

// rb_count returns the number of bytes currently stored.
size_t rb_count(const ring_buffer_t *rb) {
    return (rb->head - rb->tail + rb->capacity) % rb->capacity;
}

// rb_is_empty reports whether the buffer holds no bytes.
bool rb_is_empty(const ring_buffer_t *rb) {
    return rb->head == rb->tail;
}

// rb_is_full reports whether no more bytes can be stored.
bool rb_is_full(const ring_buffer_t *rb) {
    return ((rb->head + 1) % rb->capacity) == rb->tail;
}

// rb_available returns how many more bytes can be written.
size_t rb_available(const ring_buffer_t *rb) {
    return rb->capacity - 1 - rb_count(rb);
}

// rb_free releases the buffer and its storage.
void rb_free(ring_buffer_t *rb) {
    if (rb == NULL) return;
    free(rb->buffer);
    free(rb);
}

// rb_clear resets the buffer to empty without freeing storage.
void rb_clear(ring_buffer_t *rb) {
    rb->head = rb->tail = 0;
}

// rb_write copies as many bytes as fit, returning the number stored.
size_t rb_write(ring_buffer_t *rb, const void *data, size_t len) {
    const unsigned char *p = data;
    size_t written = 0;
    while (written < len && rb_write_byte(rb, p[written])) written++;
    return written;
}

// rb_read removes up to len bytes into out, returning the number read.
size_t rb_read(ring_buffer_t *rb, void *out, size_t len) {
    unsigned char *p = out;
    size_t got = 0;
    while (got < len && rb_read_byte(rb, &p[got])) got++;
    return got;
}

// rb_discard drops up to len bytes, returning the number discarded.
size_t rb_discard(ring_buffer_t *rb, size_t len) {
    size_t dropped = 0;
    unsigned char sink;
    while (dropped < len && rb_read_byte(rb, &sink)) dropped++;
    return dropped;
}
