// stack_queue.c — generated by scripts/generate/generate-c.mjs (do not edit by hand).
// Realistic C typing blocks for vibetyper: stack and queue containers.

#include <stdbool.h>
#include <stddef.h>
#include <stdlib.h>

typedef struct stack {
    int *items;
    size_t capacity;
    size_t top;
} stack_t;

// stack_create allocates a stack with room for capacity items.
stack_t *stack_create(size_t capacity) {
    stack_t *s = malloc(sizeof(stack_t));
    if (s == NULL) return NULL;
    s->items = malloc(capacity * sizeof(int));
    if (s->items == NULL) { free(s); return NULL; }
    s->capacity = capacity;
    s->top = 0;
    return s;
}

// stack_push places value on top; returns false when the stack is full.
bool stack_push(stack_t *s, int value) {
    if (s->top >= s->capacity) return false;
    s->items[s->top++] = value;
    return true;
}

// stack_pop removes and returns the top value via out.
bool stack_pop(stack_t *s, int *out) {
    if (s->top == 0) return false;
    *out = s->items[--s->top];
    return true;
}

// stack_peek reads the top value without removing it.
bool stack_peek(const stack_t *s, int *out) {
    if (s->top == 0) return false;
    *out = s->items[s->top - 1];
    return true;
}

// stack_is_empty reports whether the stack holds no items.
bool stack_is_empty(const stack_t *s) {
    return s->top == 0;
}

// stack_size returns the number of items currently held.
size_t stack_size(const stack_t *s) {
    return s->top;
}

// stack_free releases the stack and its backing array.
void stack_free(stack_t *s) {
    if (s == NULL) return;
    free(s->items);
    free(s);
}

typedef struct queue_node {
    int value;
    struct queue_node *next;
} queue_node_t;

typedef struct queue {
    queue_node_t *head;
    queue_node_t *tail;
    size_t count;
} queue_t;

// queue_create allocates an empty linked queue.
queue_t *queue_create(void) {
    return calloc(1, sizeof(queue_t));
}

// queue_enqueue appends value at the tail; returns false on allocation failure.
bool queue_enqueue(queue_t *q, int value) {
    queue_node_t *node = malloc(sizeof(queue_node_t));
    if (node == NULL) return false;
    node->value = value;
    node->next = NULL;
    if (q->tail == NULL) {
        q->head = q->tail = node;
    } else {
        q->tail->next = node;
        q->tail = node;
    }
    q->count++;
    return true;
}

// queue_dequeue removes and returns the front value via out.
bool queue_dequeue(queue_t *q, int *out) {
    if (q->head == NULL) return false;
    queue_node_t *old = q->head;
    q->head = old->next;
    if (q->head == NULL) q->tail = NULL;
    if (out != NULL) *out = old->value;
    free(old);
    q->count--;
    return true;
}

// queue_peek reads the front value without removing it.
bool queue_peek(const queue_t *q, int *out) {
    if (q->head == NULL) return false;
    *out = q->head->value;
    return true;
}

// queue_is_empty reports whether the queue holds no items.
bool queue_is_empty(const queue_t *q) {
    return q->head == NULL;
}

// queue_size returns the number of items currently held.
size_t queue_size(const queue_t *q) {
    return q->count;
}

// queue_free releases every node and then the queue itself.
void queue_free(queue_t *q) {
    if (q == NULL) return;
    while (q->head != NULL) {
        queue_node_t *next = q->head->next;
        free(q->head);
        q->head = next;
    }
    free(q);
}
