// string_utils.c — generated by scripts/generate/generate-c.mjs (do not edit by hand).
// Realistic C typing blocks for vibetyper: string manipulation and parsing.

#include <ctype.h>
#include <errno.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>

// str_reverse reverses a NUL-terminated string in place.
void str_reverse(char *s) {
    size_t len = strlen(s);
    for (size_t i = 0; i < len / 2; i++) {
        char tmp = s[i];
        s[i] = s[len - 1 - i];
        s[len - 1 - i] = tmp;
    }
}

// str_count_char counts occurrences of needle within haystack.
size_t str_count_char(const char *haystack, char needle) {
    size_t count = 0;
    for (const char *p = haystack; *p != '\0'; p++) {
        if (*p == needle) count++;
    }
    return count;
}

// str_trim removes leading and trailing whitespace in place and
// returns a pointer to the trimmed start of the string.
char *str_trim(char *s) {
    while (isspace((unsigned char)*s)) s++;
    char *end = s + strlen(s) - 1;
    while (end >= s && isspace((unsigned char)*end)) *end-- = '\0';
    return s;
}

// str_to_upper converts every ASCII letter in s to uppercase in place.
void str_to_upper(char *s) {
    for (char *p = s; *p != '\0'; p++) {
        if (*p >= 'a' && *p <= 'z') *p = (char)(*p - 'a' + 'A');
    }
}

// str_to_lower converts every ASCII letter in s to lowercase in place.
void str_to_lower(char *s) {
    for (char *p = s; *p != '\0'; p++) {
        if (*p >= 'A' && *p <= 'Z') *p = (char)(*p - 'A' + 'a');
    }
}

// str_starts_with reports whether s begins with prefix.
bool str_starts_with(const char *s, const char *prefix) {
    while (*prefix != '\0') {
        if (*s++ != *prefix++) return false;
    }
    return true;
}

// str_ends_with reports whether s ends with suffix.
bool str_ends_with(const char *s, const char *suffix) {
    size_t slen = strlen(s);
    size_t xlen = strlen(suffix);
    if (xlen > slen) return false;
    return strcmp(s + slen - xlen, suffix) == 0;
}

// str_find_last returns a pointer to the last occurrence of c, or NULL.
char *str_find_last(const char *s, char c) {
    const char *last = NULL;
    for (const char *p = s; *p != '\0'; p++) {
        if (*p == c) last = p;
    }
    return (char *)last;
}

// str_count_words counts whitespace-delimited words in s.
size_t str_count_words(const char *s) {
    size_t words = 0;
    bool in_word = false;
    for (const char *p = s; *p != '\0'; p++) {
        bool ws = isspace((unsigned char)*p);
        if (!ws && !in_word) { words++; in_word = true; }
        else if (ws) in_word = false;
    }
    return words;
}

// str_replace_char replaces every old byte with new, returning the count.
size_t str_replace_char(char *s, char old_c, char new_c) {
    size_t replaced = 0;
    for (char *p = s; *p != '\0'; p++) {
        if (*p == old_c) { *p = new_c; replaced++; }
    }
    return replaced;
}

// str_duplicate returns a heap copy of s, or NULL on allocation failure.
char *str_duplicate(const char *s) {
    size_t len = strlen(s) + 1;
    char *copy = malloc(len);
    if (copy == NULL) return NULL;
    memcpy(copy, s, len);
    return copy;
}

// str_concat joins two strings into a single heap allocation.
char *str_concat(const char *a, const char *b) {
    size_t la = strlen(a), lb = strlen(b);
    char *joined = malloc(la + lb + 1);
    if (joined == NULL) return NULL;
    memcpy(joined, a, la);
    memcpy(joined + la, b, lb + 1);
    return joined;
}

// str_join concatenates an array of strings with sep between them.
char *str_join(const char **parts, size_t count, const char *sep) {
    size_t sep_len = strlen(sep);
    size_t total = 1;
    for (size_t i = 0; i < count; i++) total += strlen(parts[i]) + (i ? sep_len : 0);
    char *out = malloc(total);
    if (out == NULL) return NULL;
    out[0] = '\0';
    for (size_t i = 0; i < count; i++) {
        if (i) strcat(out, sep);
        strcat(out, parts[i]);
    }
    return out;
}

// str_repeat returns a heap string with s repeated times times.
char *str_repeat(const char *s, size_t times) {
    size_t len = strlen(s);
    char *out = malloc(len * times + 1);
    if (out == NULL) return NULL;
    for (size_t i = 0; i < times; i++) memcpy(out + i * len, s, len);
    out[len * times] = '\0';
    return out;
}

// str_chop strips a single trailing newline or CR/LF pair in place.
void str_chop(char *line) {
    size_t len = strlen(line);
    while (len > 0 && (line[len - 1] == '\n' || line[len - 1] == '\r')) {
        line[--len] = '\0';
    }
}

// str_pad_left returns s left-padded with fill to at least width chars.
char *str_pad_left(const char *s, size_t width, char fill) {
    size_t len = strlen(s);
    size_t size = len > width ? len + 1 : width + 1;
    char *out = malloc(size);
    if (out == NULL) return NULL;
    size_t pad = len < width ? width - len : 0;
    for (size_t i = 0; i < pad; i++) out[i] = fill;
    memcpy(out + pad, s, len + 1);
    return out;
}

// str_cmp_ignore_case compares two strings without regard to case.
int str_cmp_ignore_case(const char *a, const char *b) {
    while (*a != '\0' && *b != '\0') {
        int ca = tolower((unsigned char)*a);
        int cb = tolower((unsigned char)*b);
        if (ca != cb) return ca - cb;
        a++;
        b++;
    }
    return tolower((unsigned char)*a) - tolower((unsigned char)*b);
}

// str_is_palindrome reports whether s reads the same forward and backward.
bool str_is_palindrome(const char *s) {
    size_t len = strlen(s);
    for (size_t i = 0; i < len / 2; i++) {
        if (s[i] != s[len - 1 - i]) return false;
    }
    return true;
}

// str_remove deletes the first occurrence of sub from s in place.
bool str_remove(char *s, const char *sub) {
    char *found = strstr(s, sub);
    if (found == NULL) return false;
    char *tail = found + strlen(sub);
    memmove(found, tail, strlen(tail) + 1);
    return true;
}

// str_to_long parses a base-10 integer, reporting success via *ok.
long str_to_long(const char *s, bool *ok) {
    char *end = NULL;
    errno = 0;
    long value = strtol(s, &end, 10);
    *ok = errno == 0 && end != s && *end == '\0';
    return value;
}
