// validation.c — generated by scripts/generate/generate-c.mjs (do not edit by hand).
// Realistic C typing blocks for vibetyper: input validation.

#include <ctype.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>

// val_is_digits reports whether s is non-empty and all decimal digits.
bool val_is_digits(const char *s) {
    if (*s == '\0') return false;
    for (const char *p = s; *p != '\0'; p++) {
        if (!isdigit((unsigned char)*p)) return false;
    }
    return true;
}

// val_is_alpha reports whether s is non-empty and all letters.
bool val_is_alpha(const char *s) {
    if (*s == '\0') return false;
    for (const char *p = s; *p != '\0'; p++) {
        if (!isalpha((unsigned char)*p)) return false;
    }
    return true;
}

// val_is_alnum reports whether s is non-empty letters and digits.
bool val_is_alnum(const char *s) {
    if (*s == '\0') return false;
    for (const char *p = s; *p != '\0'; p++) {
        if (!isalnum((unsigned char)*p)) return false;
    }
    return true;
}

// val_is_hex_string reports whether s is non-empty hexadecimal digits.
bool val_is_hex_string(const char *s) {
    if (*s == '\0') return false;
    for (const char *p = s; *p != '\0'; p++) {
        if (!isxdigit((unsigned char)*p)) return false;
    }
    return true;
}

// val_is_valid_ipv4 checks a dotted-quad address like "192.168.0.1".
bool val_is_valid_ipv4(const char *s) {
    int octets = 0, digits = 0, value = 0;
    for (const char *p = s; *p != '\0'; p++) {
        if (isdigit((unsigned char)*p)) {
            if (++digits > 3) return false;
            value = value * 10 + (*p - '0');
        } else if (*p == '.') {
            if (digits == 0 || value > 255) return false;
            octets++;
            digits = 0;
            value = 0;
        } else {
            return false;
        }
    }
    return octets == 3 && digits > 0 && value <= 255;
}

// val_is_valid_email applies a pragmatic shape check to an address.
bool val_is_valid_email(const char *s) {
    const char *at = strchr(s, '@');
    if (at == NULL || at == s) return false;
    const char *dot = strchr(at + 1, '.');
    if (dot == NULL || dot == at + 1 || dot[1] == '\0') return false;
    for (const char *p = s; *p != '\0'; p++) {
        unsigned char c = (unsigned char)*p;
        if (!(isalnum(c) || c == '@' || c == '.' || c == '_' || c == '-' || c == '+')) {
            return false;
        }
    }
    return true;
}

// val_is_valid_username enforces 3-20 chars of letters, digits, '_' and '-',
// with the first character a letter.
bool val_is_valid_username(const char *s) {
    size_t len = strlen(s);
    if (len < 3 || len > 20 || !isalpha((unsigned char)s[0])) return false;
    for (const char *p = s; *p != '\0'; p++) {
        unsigned char c = (unsigned char)*p;
        if (!(isalnum(c) || c == '_' || c == '-')) return false;
    }
    return true;
}

// val_is_strong_password requires at least 8 chars from four classes.
bool val_is_strong_password(const char *s) {
    size_t len = strlen(s);
    if (len < 8) return false;
    bool has_upper = false, has_lower = false, has_digit = false, has_symbol = false;
    for (const char *p = s; *p != '\0'; p++) {
        unsigned char c = (unsigned char)*p;
        if (isupper(c)) has_upper = true;
        else if (islower(c)) has_lower = true;
        else if (isdigit(c)) has_digit = true;
        else has_symbol = true;
    }
    return has_upper && has_lower && has_digit && has_symbol;
}

// val_is_valid_luhn verifies a numeric string against the Luhn checksum.
bool val_is_valid_luhn(const char *digits) {
    int sum = 0;
    bool alternate = false;
    size_t len = strlen(digits);
    for (size_t i = len; i-- > 0;) {
        int d = digits[i] - '0';
        if (alternate) {
            d *= 2;
            if (d > 9) d -= 9;
        }
        sum += d;
        alternate = !alternate;
    }
    return sum % 10 == 0;
}

// val_is_valid_credit_card checks digit-ness, length, and the Luhn sum.
bool val_is_valid_credit_card(const char *number) {
    if (!val_is_digits(number)) return false;
    size_t len = strlen(number);
    return len >= 13 && len <= 19 && val_is_valid_luhn(number);
}

// val_is_valid_isbn10 verifies a 10-digit ISBN including an 'X' check.
bool val_is_valid_isbn10(const char *isbn) {
    if (strlen(isbn) != 10) return false;
    int sum = 0;
    for (int i = 0; i < 10; i++) {
        int weight = 10 - i;
        char c = isbn[i];
        if (c == 'X' || c == 'x') sum += 10 * weight;
        else if (isdigit((unsigned char)c)) sum += (c - '0') * weight;
        else return false;
    }
    return sum % 11 == 0;
}

// val_is_valid_isbn13 verifies a 13-digit ISBN with alternating weights.
bool val_is_valid_isbn13(const char *isbn) {
    if (strlen(isbn) != 13 || !val_is_digits(isbn)) return false;
    int sum = 0;
    for (int i = 0; i < 13; i++) {
        int digit = isbn[i] - '0';
        sum += (i % 2 == 0) ? digit : digit * 3;
    }
    return sum % 10 == 0;
}

// val_is_leap_year reports whether year is a Gregorian leap year.
bool val_is_leap_year(int year) {
    return (year % 4 == 0 && year % 100 != 0) || year % 400 == 0;
}

// val_is_valid_date checks a calendar date for month and day ranges.
bool val_is_valid_date(int year, int month, int day) {
    if (month < 1 || month > 12 || day < 1) return false;
    static const int days[] = {31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31};
    int limit = days[month - 1];
    if (month == 2 && val_is_leap_year(year)) limit = 29;
    return day <= limit;
}

// val_in_range reports whether value falls within [low, high].
bool val_in_range(int value, int low, int high) {
    return value >= low && value <= high;
}

// val_is_valid_port checks that s is a number in the TCP port range 1-65535.
bool val_is_valid_port(const char *s) {
    if (!val_is_digits(s)) return false;
    long port = strtol(s, NULL, 10);
    return port >= 1 && port <= 65535;
}

// val_is_valid_hex_color accepts "#RGB" or "#RRGGBB" (case-insensitive).
bool val_is_valid_hex_color(const char *s) {
    if (s[0] != '#') return false;
    size_t len = strlen(s + 1);
    return (len == 3 || len == 6) && val_is_hex_string(s + 1);
}

// val_is_valid_mac_address checks six hex pairs joined by ':' or '-'.
bool val_is_valid_mac_address(const char *s) {
    int groups = 0, digits = 0;
    for (const char *p = s; *p != '\0'; p++) {
        if (isxdigit((unsigned char)*p)) {
            if (++digits > 2) return false;
        } else if (*p == ':' || *p == '-') {
            if (digits != 2) return false;
            groups++;
            digits = 0;
        } else {
            return false;
        }
    }
    return groups == 5 && digits == 2;
}
