// algorithms.cpp — generated by scripts/generate/generate-cpp.mjs (do not edit by hand).
// Realistic C++ typing blocks for vibetyper: classic algorithms.

#include <algorithm>
#include <map>
#include <queue>
#include <set>
#include <string>
#include <unordered_map>
#include <vector>

// binary_search returns the index of target in a sorted vector, or -1.
int binary_search(const std::vector<int>& sorted, int target) {
    int lo = 0, hi = static_cast<int>(sorted.size()) - 1;
    while (lo <= hi) {
        int mid = lo + (hi - lo) / 2;
        if (sorted[mid] == target) {
            return mid;
        }
        if (sorted[mid] < target) {
            lo = mid + 1;
        } else {
            hi = mid - 1;
        }
    }
    return -1;
}

// binary_search_first finds the first index of target in a sorted
// vector that may contain duplicates, or -1.
int binary_search_first(const std::vector<int>& sorted, int target) {
    int lo = 0, hi = static_cast<int>(sorted.size()) - 1;
    int first = -1;
    while (lo <= hi) {
        int mid = lo + (hi - lo) / 2;
        if (sorted[mid] < target) {
            lo = mid + 1;
        } else {
            if (sorted[mid] == target) {
                first = mid;
            }
            hi = mid - 1;
        }
    }
    return first;
}

// quick_sort sorts a vector in place with a Hoare partition.
void quick_sort(std::vector<int>& items, int lo, int hi) {
    if (lo >= hi) {
        return;
    }
    int pivot = items[lo + (hi - lo) / 2];
    int i = lo, j = hi;
    while (i <= j) {
        while (items[i] < pivot) ++i;
        while (items[j] > pivot) --j;
        if (i <= j) {
            std::swap(items[i], items[j]);
            ++i;
            --j;
        }
    }
    quick_sort(items, lo, j);
    quick_sort(items, i, hi);
}

// merge_sort returns a sorted copy of values.
std::vector<int> merge_sort(const std::vector<int>& values) {
    if (values.size() <= 1) {
        return values;
    }
    size_t mid = values.size() / 2;
    std::vector<int> left = merge_sort(
        std::vector<int>(values.begin(), values.begin() + static_cast<long>(mid)));
    std::vector<int> right = merge_sort(
        std::vector<int>(values.begin() + static_cast<long>(mid), values.end()));
    std::vector<int> merged;
    merged.reserve(values.size());
    size_t i = 0, j = 0;
    while (i < left.size() && j < right.size()) {
        if (left[i] <= right[j]) {
            merged.push_back(left[i++]);
        } else {
            merged.push_back(right[j++]);
        }
    }
    while (i < left.size()) merged.push_back(left[i++]);
    while (j < right.size()) merged.push_back(right[j++]);
    return merged;
}

// insertion_sort sorts a vector in place, efficient for nearly-sorted
// input.
void insertion_sort(std::vector<int>& items) {
    for (size_t i = 1; i < items.size(); ++i) {
        int key = items[i];
        size_t j = i;
        while (j > 0 && items[j - 1] > key) {
            items[j] = items[j - 1];
            --j;
        }
        items[j] = key;
    }
}

// selection_sort sorts a vector in place by repeatedly picking the
// minimum of the unsorted tail.
void selection_sort(std::vector<int>& items) {
    for (size_t i = 0; i + 1 < items.size(); ++i) {
        size_t minIdx = i;
        for (size_t j = i + 1; j < items.size(); ++j) {
            if (items[j] < items[minIdx]) {
                minIdx = j;
            }
        }
        std::swap(items[i], items[minIdx]);
    }
}

// two_sum finds indices of two values that add up to target.
std::pair<int, int> two_sum(const std::vector<int>& values, int target) {
    std::unordered_map<int, int> seen;
    for (size_t i = 0; i < values.size(); ++i) {
        auto it = seen.find(target - values[i]);
        if (it != seen.end()) {
            return {it->second, static_cast<int>(i)};
        }
        seen[values[i]] = static_cast<int>(i);
    }
    return {-1, -1};
}

// max_subarray_sum returns the largest sum of any contiguous subarray
// using Kadane's algorithm.
int max_subarray_sum(const std::vector<int>& values) {
    if (values.empty()) {
        return 0;
    }
    int best = values.front();
    int current = values.front();
    for (size_t i = 1; i < values.size(); ++i) {
        current = std::max(values[i], current + values[i]);
        best = std::max(best, current);
    }
    return best;
}

// longest_unique_substring returns the length of the longest substring
// without repeating characters.
size_t longest_unique_substring(const std::string& s) {
    std::unordered_map<char, size_t> lastSeen;
    size_t start = 0, longest = 0;
    for (size_t i = 0; i < s.size(); ++i) {
        auto it = lastSeen.find(s[i]);
        if (it != lastSeen.end() && it->second >= start) {
            start = it->second + 1;
        }
        lastSeen[s[i]] = i;
        longest = std::max(longest, i - start + 1);
    }
    return longest;
}

// knapsack returns the maximum value that fits in capacity using 0/1
// dynamic programming.
int knapsack(const std::vector<int>& weights, const std::vector<int>& values,
             int capacity) {
    std::vector<int> dp(capacity + 1, 0);
    for (size_t i = 0; i < weights.size(); ++i) {
        for (int w = capacity; w >= weights[i]; --w) {
            dp[w] = std::max(dp[w], dp[w - weights[i]] + values[i]);
        }
    }
    return dp[capacity];
}

// coin_change returns the minimum coins from denominations needed to
// make amount, or -1 when impossible.
int coin_change(const std::vector<int>& denominations, int amount) {
    const int inf = amount + 1;
    std::vector<int> dp(amount + 1, inf);
    dp[0] = 0;
    for (int coin : denominations) {
        for (int a = coin; a <= amount; ++a) {
            dp[a] = std::min(dp[a], dp[a - coin] + 1);
        }
    }
    return dp[amount] == inf ? -1 : dp[amount];
}

// longest_common_subsequence returns the length of the longest common
// subsequence of two strings.
size_t longest_common_subsequence(const std::string& a, const std::string& b) {
    std::vector<std::vector<size_t>> dp(a.size() + 1,
                                        std::vector<size_t>(b.size() + 1, 0));
    for (size_t i = 1; i <= a.size(); ++i) {
        for (size_t j = 1; j <= b.size(); ++j) {
            if (a[i - 1] == b[j - 1]) {
                dp[i][j] = dp[i - 1][j - 1] + 1;
            } else {
                dp[i][j] = std::max(dp[i - 1][j], dp[i][j - 1]);
            }
        }
    }
    return dp[a.size()][b.size()];
}

// topological_sort orders nodes so every edge points forward, returning
// false when the graph contains a cycle.
bool topological_sort(
    const std::unordered_map<std::string, std::vector<std::string>>& graph,
    std::vector<std::string>& order) {
    std::unordered_map<std::string, int> indegree;
    for (const auto& entry : graph) {
        indegree[entry.first] += 0;
        for (const std::string& next : entry.second) {
            indegree[next]++;
        }
    }
    std::queue<std::string> ready;
    for (const auto& entry : indegree) {
        if (entry.second == 0) {
            ready.push(entry.first);
        }
    }
    order.clear();
    while (!ready.empty()) {
        std::string node = ready.front();
        ready.pop();
        order.push_back(node);
        auto it = graph.find(node);
        if (it == graph.end()) {
            continue;
        }
        for (const std::string& next : it->second) {
            if (--indegree[next] == 0) {
                ready.push(next);
            }
        }
    }
    return order.size() == graph.size();
}

// dijkstra returns the shortest distance from start to every node in a
// weighted adjacency map.
std::map<std::string, int> dijkstra(
    const std::map<std::string, std::map<std::string, int>>& graph,
    const std::string& start) {
    const int inf = 1 << 30;
    std::map<std::string, int> dist;
    std::set<std::string> visited;
    for (const auto& entry : graph) {
        dist[entry.first] = inf;
    }
    dist[start] = 0;
    while (true) {
        std::string next;
        int best = inf;
        for (const auto& entry : dist) {
            if (visited.count(entry.first) == 0 && entry.second < best) {
                best = entry.second;
                next = entry.first;
            }
        }
        if (next.empty()) {
            break;
        }
        visited.insert(next);
        auto it = graph.find(next);
        if (it == graph.end()) {
            continue;
        }
        for (const auto& edge : it->second) {
            int candidate = dist[next] + edge.second;
            if (candidate < dist[edge.first]) {
                dist[edge.first] = candidate;
            }
        }
    }
    return dist;
}

// majority_element returns the value appearing more than n/2 times
// using the Boyer-Moore voting algorithm.
int majority_element(const std::vector<int>& values) {
    int candidate = 0, count = 0;
    for (int v : values) {
        if (count == 0) {
            candidate = v;
        }
        count += (v == candidate) ? 1 : -1;
    }
    return candidate;
}

// find_missing_number finds the one missing integer in a permutation of
// 0..n using XOR cancellation.
int find_missing_number(const std::vector<int>& values) {
    int missing = 0;
    for (size_t i = 0; i <= values.size(); ++i) {
        missing ^= static_cast<int>(i);
    }
    for (int v : values) {
        missing ^= v;
    }
    return missing;
}

// dutch_flag sorts an array of 0s, 1s and 2s in a single pass.
void dutch_flag(std::vector<int>& items) {
    size_t lo = 0, mid = 0, hi = items.size();
    while (mid < hi) {
        if (items[mid] == 0) {
            std::swap(items[lo++], items[mid++]);
        } else if (items[mid] == 1) {
            ++mid;
        } else {
            std::swap(items[mid], items[--hi]);
        }
    }
}

// next_permutation rearranges items into the next lexicographic
// permutation, returning false when already descending.
bool next_permutation(std::vector<int>& items) {
    int i = static_cast<int>(items.size()) - 2;
    while (i >= 0 && items[i] >= items[i + 1]) {
        --i;
    }
    if (i < 0) {
        return false;
    }
    int j = static_cast<int>(items.size()) - 1;
    while (items[j] <= items[i]) {
        --j;
    }
    std::swap(items[i], items[j]);
    std::reverse(items.begin() + i + 1, items.end());
    return true;
}

// merge_sorted_vectors merges two sorted vectors into one sorted vector.
std::vector<int> merge_sorted_vectors(const std::vector<int>& a,
                                      const std::vector<int>& b) {
    std::vector<int> out;
    out.reserve(a.size() + b.size());
    size_t i = 0, j = 0;
    while (i < a.size() && j < b.size()) {
        if (a[i] <= b[j]) {
            out.push_back(a[i++]);
        } else {
            out.push_back(b[j++]);
        }
    }
    while (i < a.size()) out.push_back(a[i++]);
    while (j < b.size()) out.push_back(b[j++]);
    return out;
}
