// containers_utils.cpp — generated by scripts/generate/generate-cpp.mjs (do not edit by hand).
// Realistic C++ typing blocks for vibetyper: containers and collection helpers.

#include <deque>
#include <list>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

// Stack is a LIFO container of integers.
class Stack {
public:
    void push(int value);
    int pop();
    bool empty() const;
    size_t size() const;

private:
    std::vector<int> items_;
};

void Stack::push(int value) {
    items_.push_back(value);
}

int Stack::pop() {
    int top = items_.back();
    items_.pop_back();
    return top;
}

bool Stack::empty() const {
    return items_.empty();
}

size_t Stack::size() const {
    return items_.size();
}

// StringQueue is a FIFO queue of strings.
class StringQueue {
public:
    void enqueue(const std::string& value);
    std::string dequeue();
    bool empty() const;
    size_t size() const;

private:
    std::deque<std::string> items_;
};

void StringQueue::enqueue(const std::string& value) {
    items_.push_back(value);
}

std::string StringQueue::dequeue() {
    std::string front = items_.front();
    items_.pop_front();
    return front;
}

bool StringQueue::empty() const {
    return items_.empty();
}

size_t StringQueue::size() const {
    return items_.size();
}

// StringSet stores unique strings.
class StringSet {
public:
    void add(const std::string& value);
    bool has(const std::string& value) const;
    void remove(const std::string& value);
    size_t size() const;

private:
    std::unordered_set<std::string> items_;
};

void StringSet::add(const std::string& value) {
    items_.insert(value);
}

bool StringSet::has(const std::string& value) const {
    return items_.find(value) != items_.end();
}

void StringSet::remove(const std::string& value) {
    items_.erase(value);
}

size_t StringSet::size() const {
    return items_.size();
}

// RingBuffer is a fixed-capacity circular buffer of integers.
class RingBuffer {
public:
    explicit RingBuffer(size_t capacity);
    void write(int value);
    bool read(int& value);
    size_t size() const;

private:
    std::vector<int> data_;
    size_t head_ = 0;
    size_t count_ = 0;
};

RingBuffer::RingBuffer(size_t capacity) : data_(capacity) {}

void RingBuffer::write(int value) {
    if (data_.empty()) {
        return;
    }
    data_[(head_ + count_) % data_.size()] = value;
    if (count_ < data_.size()) {
        ++count_;
    } else {
        head_ = (head_ + 1) % data_.size();
    }
}

bool RingBuffer::read(int& value) {
    if (count_ == 0) {
        return false;
    }
    value = data_[head_];
    head_ = (head_ + 1) % data_.size();
    --count_;
    return true;
}

size_t RingBuffer::size() const {
    return count_;
}

// LRUCache evicts the least recently used entry when it reaches capacity.
class LRUCache {
public:
    explicit LRUCache(size_t capacity);
    bool get(const std::string& key, std::string& value);
    void put(const std::string& key, const std::string& value);

private:
    using Entry = std::pair<std::string, std::string>;
    std::list<Entry> order_;
    std::unordered_map<std::string, std::list<Entry>::iterator> lookup_;
    size_t capacity_;
};

LRUCache::LRUCache(size_t capacity) : capacity_(capacity) {}

bool LRUCache::get(const std::string& key, std::string& value) {
    auto it = lookup_.find(key);
    if (it == lookup_.end()) {
        return false;
    }
    order_.splice(order_.begin(), order_, it->second);
    value = it->second->second;
    return true;
}

void LRUCache::put(const std::string& key, const std::string& value) {
    auto it = lookup_.find(key);
    if (it != lookup_.end()) {
        it->second->second = value;
        order_.splice(order_.begin(), order_, it->second);
        return;
    }
    order_.emplace_front(key, value);
    lookup_[key] = order_.begin();
    if (order_.size() > capacity_) {
        lookup_.erase(order_.back().first);
        order_.pop_back();
    }
}

// frequency_map counts how often each string appears in a vector.
std::unordered_map<std::string, int> frequency_map(
    const std::vector<std::string>& items) {
    std::unordered_map<std::string, int> counts;
    for (const std::string& item : items) {
        counts[item]++;
    }
    return counts;
}

// chunk splits a vector into consecutive runs of at most size elements.
std::vector<std::vector<int>> chunk(const std::vector<int>& items, size_t size) {
    std::vector<std::vector<int>> out;
    if (size == 0) {
        return out;
    }
    for (size_t start = 0; start < items.size(); start += size) {
        size_t end = std::min(start + size, items.size());
        out.emplace_back(items.begin() + static_cast<long>(start),
                         items.begin() + static_cast<long>(end));
    }
    return out;
}

// unique_preserve_order removes duplicates, keeping first-seen order.
std::vector<std::string> unique_preserve_order(
    const std::vector<std::string>& items) {
    std::unordered_set<std::string> seen;
    std::vector<std::string> out;
    for (const std::string& item : items) {
        if (seen.insert(item).second) {
            out.push_back(item);
        }
    }
    return out;
}

// rotate_left shifts a vector left by k positions, wrapping around.
std::vector<int> rotate_left(const std::vector<int>& items, int k) {
    if (items.empty()) {
        return items;
    }
    k %= static_cast<int>(items.size());
    if (k < 0) {
        k += static_cast<int>(items.size());
    }
    std::vector<int> out;
    out.reserve(items.size());
    out.insert(out.end(), items.begin() + k, items.end());
    out.insert(out.end(), items.begin(), items.begin() + k);
    return out;
}

// min_value returns the smallest value in a vector.
template <typename T>
T min_value(const std::vector<T>& values) {
    if (values.empty()) {
        return T{};
    }
    T best = values.front();
    for (const T& v : values) {
        if (v < best) {
            best = v;
        }
    }
    return best;
}

// max_value returns the largest value in a vector.
template <typename T>
T max_value(const std::vector<T>& values) {
    if (values.empty()) {
        return T{};
    }
    T best = values.front();
    for (const T& v : values) {
        if (v > best) {
            best = v;
        }
    }
    return best;
}

// index_of returns the first index of target in items, or -1.
int index_of(const std::vector<std::string>& items, const std::string& target) {
    for (size_t i = 0; i < items.size(); ++i) {
        if (items[i] == target) {
            return static_cast<int>(i);
        }
    }
    return -1;
}

// merge_sorted merges two sorted vectors into one sorted vector.
std::vector<int> merge_sorted(const std::vector<int>& a,
                              const std::vector<int>& b) {
    std::vector<int> out;
    out.reserve(a.size() + b.size());
    size_t i = 0, j = 0;
    while (i < a.size() && j < b.size()) {
        if (a[i] <= b[j]) {
            out.push_back(a[i++]);
        } else {
            out.push_back(b[j++]);
        }
    }
    while (i < a.size()) {
        out.push_back(a[i++]);
    }
    while (j < b.size()) {
        out.push_back(b[j++]);
    }
    return out;
}
