// data_structures.cpp — generated by scripts/generate/generate-cpp.mjs (do not edit by hand).
// Realistic C++ typing blocks for vibetyper: classic data structures.

#include <algorithm>
#include <cstdint>
#include <memory>
#include <queue>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

// TreeNode is a node of a binary search tree.
struct TreeNode {
    int value;
    std::unique_ptr<TreeNode> left;
    std::unique_ptr<TreeNode> right;

    explicit TreeNode(int v) : value(v) {}
};

// tree_insert adds value into the tree keeping BST order.
void tree_insert(std::unique_ptr<TreeNode>& node, int value) {
    if (!node) {
        node = std::make_unique<TreeNode>(value);
        return;
    }
    if (value < node->value) {
        tree_insert(node->left, value);
    } else {
        tree_insert(node->right, value);
    }
}

// tree_contains reports whether value exists in the tree.
bool tree_contains(const TreeNode* node, int value) {
    if (node == nullptr) {
        return false;
    }
    if (value < node->value) {
        return tree_contains(node->left.get(), value);
    }
    if (value > node->value) {
        return tree_contains(node->right.get(), value);
    }
    return true;
}

// tree_inorder returns the values in sorted order.
std::vector<int> tree_inorder(const TreeNode* node) {
    std::vector<int> out;
    if (node == nullptr) {
        return out;
    }
    std::vector<int> left = tree_inorder(node->left.get());
    out.insert(out.end(), left.begin(), left.end());
    out.push_back(node->value);
    std::vector<int> right = tree_inorder(node->right.get());
    out.insert(out.end(), right.begin(), right.end());
    return out;
}

// tree_height returns the number of levels in the tree.
int tree_height(const TreeNode* node) {
    if (node == nullptr) {
        return 0;
    }
    int left = tree_height(node->left.get());
    int right = tree_height(node->right.get());
    return (left > right ? left : right) + 1;
}

// MinHeap is a binary min-heap backed by a vector.
class MinHeap {
public:
    void push(int value);
    bool pop(int& value);
    bool empty() const;

private:
    std::vector<int> items_;
};

void MinHeap::push(int value) {
    items_.push_back(value);
    size_t i = items_.size() - 1;
    while (i > 0) {
        size_t parent = (i - 1) / 2;
        if (items_[parent] <= items_[i]) {
            break;
        }
        std::swap(items_[parent], items_[i]);
        i = parent;
    }
}

bool MinHeap::pop(int& value) {
    if (items_.empty()) {
        return false;
    }
    value = items_.front();
    items_.front() = items_.back();
    items_.pop_back();
    size_t i = 0;
    while (true) {
        size_t left = 2 * i + 1;
        size_t right = 2 * i + 2;
        size_t smallest = i;
        if (left < items_.size() && items_[left] < items_[smallest]) {
            smallest = left;
        }
        if (right < items_.size() && items_[right] < items_[smallest]) {
            smallest = right;
        }
        if (smallest == i) {
            break;
        }
        std::swap(items_[i], items_[smallest]);
        i = smallest;
    }
    return true;
}

bool MinHeap::empty() const {
    return items_.empty();
}

// Graph is a directed graph keyed by node name.
class Graph {
public:
    void add_edge(const std::string& from, const std::string& to);
    std::vector<std::string> bfs(const std::string& start) const;

private:
    std::unordered_map<std::string, std::vector<std::string>> adjacency_;
};

void Graph::add_edge(const std::string& from, const std::string& to) {
    adjacency_[from].push_back(to);
}

std::vector<std::string> Graph::bfs(const std::string& start) const {
    std::vector<std::string> order;
    std::queue<std::string> pending;
    std::unordered_set<std::string> visited;
    pending.push(start);
    visited.insert(start);
    while (!pending.empty()) {
        std::string node = pending.front();
        pending.pop();
        order.push_back(node);
        auto it = adjacency_.find(node);
        if (it == adjacency_.end()) {
            continue;
        }
        for (const std::string& next : it->second) {
            if (visited.insert(next).second) {
                pending.push(next);
            }
        }
    }
    return order;
}

// TrieNode is one node of a prefix tree.
struct TrieNode {
    std::unordered_map<char, std::unique_ptr<TrieNode>> children;
    bool terminal = false;
};

// trie_insert adds a word to the trie.
void trie_insert(TrieNode& root, const std::string& word) {
    TrieNode* node = &root;
    for (char c : word) {
        auto& child = node->children[c];
        if (!child) {
            child = std::make_unique<TrieNode>();
        }
        node = child.get();
    }
    node->terminal = true;
}

// trie_search reports whether word is stored as a complete word.
bool trie_search(const TrieNode& root, const std::string& word) {
    const TrieNode* node = &root;
    for (char c : word) {
        auto it = node->children.find(c);
        if (it == node->children.end()) {
            return false;
        }
        node = it->second.get();
    }
    return node->terminal;
}

// trie_starts_with reports whether any stored word begins with prefix.
bool trie_starts_with(const TrieNode& root, const std::string& prefix) {
    const TrieNode* node = &root;
    for (char c : prefix) {
        auto it = node->children.find(c);
        if (it == node->children.end()) {
            return false;
        }
        node = it->second.get();
    }
    return true;
}

// fnv1a_hash is a 32-bit FNV-1a variant seeded per hash function.
uint32_t fnv1a_hash(const std::string& text, uint32_t seed) {
    uint32_t hash = 2166136261u ^ seed;
    for (unsigned char c : text) {
        hash ^= c;
        hash *= 16777619u;
    }
    return hash;
}

// BloomFilter is a probabilistic set with no false negatives.
class BloomFilter {
public:
    explicit BloomFilter(size_t bitCount);

    void add(const std::string& item);
    bool maybe_contains(const std::string& item) const;

private:
    std::vector<bool> bits_;
    size_t bitCount_;
};

BloomFilter::BloomFilter(size_t bitCount)
    : bits_(bitCount), bitCount_(bitCount) {}

void BloomFilter::add(const std::string& item) {
    bits_[fnv1a_hash(item, 0x9E3779B9u) % bitCount_] = true;
    bits_[fnv1a_hash(item, 0x85EBCA6Bu) % bitCount_] = true;
}

bool BloomFilter::maybe_contains(const std::string& item) const {
    return bits_[fnv1a_hash(item, 0x9E3779B9u) % bitCount_] &&
           bits_[fnv1a_hash(item, 0x85EBCA6Bu) % bitCount_];
}

// LinkedNode is one element of a singly linked list.
struct LinkedNode {
    int value;
    LinkedNode* next = nullptr;

    explicit LinkedNode(int v) : value(v) {}
};

// list_append adds a value to the end of a list.
void list_append(LinkedNode*& head, int value) {
    if (head == nullptr) {
        head = new LinkedNode(value);
        return;
    }
    LinkedNode* tail = head;
    while (tail->next != nullptr) {
        tail = tail->next;
    }
    tail->next = new LinkedNode(value);
}

// list_contains reports whether value appears in the list.
bool list_contains(const LinkedNode* head, int value) {
    for (const LinkedNode* node = head; node != nullptr; node = node->next) {
        if (node->value == value) {
            return true;
        }
    }
    return false;
}
