// domain_models_2.cpp — generated by scripts/generate/generate-cpp.mjs (do not edit by hand).
// Realistic C++ typing blocks for vibetyper: domain models and their methods.

#include <iomanip>
#include <sstream>
#include <string>
#include <utility>
#include <vector>

// Song is a track in the music library.
class Song {
public:
    Song(std::string title, std::string artist, int durationSec);

    std::string minutes() const;
    void bump_play_count();
    int plays() const;

private:
    std::string title_;
    std::string artist_;
    int durationSec_;
    int playCount_ = 0;
};

Song::Song(std::string title, std::string artist, int durationSec)
    : title_(std::move(title)), artist_(std::move(artist)),
      durationSec_(durationSec) {}

std::string Song::minutes() const {
    std::ostringstream out;
    out << (durationSec_ / 60) << ":"
        << std::setw(2) << std::setfill('0') << (durationSec_ % 60);
    return out.str();
}

void Song::bump_play_count() {
    ++playCount_;
}

int Song::plays() const {
    return playCount_;
}

// Task is a unit of work on a project board.
class Task {
public:
    Task(int id, std::string title);

    void complete();
    bool is_done() const;
    std::string title() const;

private:
    int id_;
    std::string title_;
    bool done_ = false;
};

Task::Task(int id, std::string title) : id_(id), title_(std::move(title)) {}

void Task::complete() {
    done_ = true;
}

bool Task::is_done() const {
    return done_;
}

std::string Task::title() const {
    return title_;
}

// SensorReading is one sample from an environmental sensor.
struct SensorReading {
    std::string deviceId;
    double temperature = 0.0;
    double humidity = 0.0;
};

// heat_index approximates the perceived temperature from humidity.
double heat_index(const SensorReading& reading) {
    double t = reading.temperature;
    double h = reading.humidity;
    return -42.379 + 2.04901523 * t + 10.14333127 * h -
           0.22475541 * t * h - 0.00683783 * t * t -
           0.05481717 * h * h + 0.00122874 * t * t * h +
           0.00085282 * t * h * h - 0.00000199 * t * t * h * h;
}

// CartItem is one product line in a shopping cart.
struct CartItem {
    std::string productSku;
    int quantity = 0;
    long long unitPriceCents = 0;
};

// line_total is the price of the whole line.
long long line_total(const CartItem& item) {
    return item.unitPriceCents * item.quantity;
}

// Session is a logged-in browser session with an expiry.
class Session {
public:
    Session(std::string token, int userId, long long expiresAtSec);

    bool expired(long long nowSec) const;
    long long remaining_sec(long long nowSec) const;

private:
    std::string token_;
    int userId_;
    long long expiresAtSec_;
};

Session::Session(std::string token, int userId, long long expiresAtSec)
    : token_(std::move(token)), userId_(userId), expiresAtSec_(expiresAtSec) {}

bool Session::expired(long long nowSec) const {
    return nowSec >= expiresAtSec_;
}

long long Session::remaining_sec(long long nowSec) const {
    return expiresAtSec_ > nowSec ? expiresAtSec_ - nowSec : 0;
}

// Notification is a user-facing alert.
class Notification {
public:
    Notification(std::string id, std::string kind, std::string message);

    void mark_read();
    bool is_read() const;

private:
    std::string id_;
    std::string kind_;
    std::string message_;
    bool read_ = false;
};

Notification::Notification(std::string id, std::string kind, std::string message)
    : id_(std::move(id)), kind_(std::move(kind)), message_(std::move(message)) {}

void Notification::mark_read() {
    read_ = true;
}

bool Notification::is_read() const {
    return read_;
}

// Address is a postal address for shipping or billing.
struct Address {
    std::string street;
    std::string city;
    std::string state;
    std::string zip;
};

// to_single_line renders the address on one line.
std::string to_single_line(const Address& address) {
    std::ostringstream out;
    out << address.street << ", " << address.city << ", "
        << address.state << " " << address.zip;
    return out.str();
}

// Recipe is a set of ingredients and a procedure.
class Recipe {
public:
    Recipe(std::string name, int servings);

    void add_ingredient(std::string ingredient);
    size_t ingredient_count() const;
    std::string name() const;

private:
    std::string name_;
    int servings_;
    std::vector<std::string> ingredients_;
};

Recipe::Recipe(std::string name, int servings)
    : name_(std::move(name)), servings_(servings) {}

void Recipe::add_ingredient(std::string ingredient) {
    ingredients_.push_back(std::move(ingredient));
}

size_t Recipe::ingredient_count() const {
    return ingredients_.size();
}

std::string Recipe::name() const {
    return name_;
}

// Payment is a single charge against an order.
class Payment {
public:
    Payment(std::string id, std::string orderId, long long amountCents);

    bool refundable() const;
    long long amount() const;

private:
    std::string id_;
    std::string orderId_;
    long long amountCents_;
};

Payment::Payment(std::string id, std::string orderId, long long amountCents)
    : id_(std::move(id)), orderId_(std::move(orderId)),
      amountCents_(amountCents) {}

bool Payment::refundable() const {
    return amountCents_ > 0;
}

long long Payment::amount() const {
    return amountCents_;
}

// Event is a timestamped fact emitted by an application.
struct Event {
    std::string type;
    long long createdAtSec = 0;
};

// event_key returns a stable deduplication key for an event.
std::string event_key(const Event& event) {
    return event.type + "@" + std::to_string(event.createdAtSec);
}

// Message is a chat message between two users.
class Message {
public:
    Message(std::string id, int fromId, int toId, std::string body);

    bool is_reply() const;
    std::string body() const;

private:
    std::string id_;
    int fromId_;
    int toId_;
    std::string replyToId_;
    std::string body_;
};

Message::Message(std::string id, int fromId, int toId, std::string body)
    : id_(std::move(id)), fromId_(fromId), toId_(toId),
      body_(std::move(body)) {}

bool Message::is_reply() const {
    return !replyToId_.empty();
}

std::string Message::body() const {
    return body_;
}
