// domain_models.cpp — generated by scripts/generate/generate-cpp.mjs (do not edit by hand).
// Realistic C++ typing blocks for vibetyper: domain models and their methods.

#include <string>
#include <utility>
#include <vector>

// User is a registered account in the system.
class User {
public:
    User(int id, std::string name, std::string email);

    std::string display_name() const;
    bool valid_email() const;

private:
    int id_;
    std::string name_;
    std::string email_;
};

User::User(int id, std::string name, std::string email)
    : id_(id), name_(std::move(name)), email_(std::move(email)) {}

std::string User::display_name() const {
    if (!name_.empty()) {
        return name_;
    }
    size_t at = email_.find('@');
    return at == std::string::npos ? "anonymous" : email_.substr(0, at);
}

bool User::valid_email() const {
    return email_.find('@') != std::string::npos &&
           email_.find('.', email_.find('@')) != std::string::npos;
}

// Product is an item available for sale, priced in cents.
class Product {
public:
    Product(std::string sku, std::string name, long long priceCents, int stock);

    long long total_value() const;
    void restock(int amount);

private:
    std::string sku_;
    std::string name_;
    long long priceCents_;
    int stock_;
};

Product::Product(std::string sku, std::string name, long long priceCents,
                 int stock)
    : sku_(std::move(sku)), name_(std::move(name)), priceCents_(priceCents),
      stock_(stock) {}

long long Product::total_value() const {
    return priceCents_ * stock_;
}

void Product::restock(int amount) {
    if (amount > 0) {
        stock_ += amount;
    }
}

// OrderItem is one line of an order.
struct OrderItem {
    std::string sku;
    int quantity = 0;
    long long price = 0;
};

// Order is a customer's purchase with a lifecycle status.
class Order {
public:
    void add_item(OrderItem item);
    long long subtotal() const;
    size_t item_count() const;

private:
    std::string id_;
    std::string status_ = "pending";
    std::vector<OrderItem> items_;
};

void Order::add_item(OrderItem item) {
    items_.push_back(std::move(item));
}

long long Order::subtotal() const {
    long long total = 0;
    for (const OrderItem& item : items_) {
        total += item.price * item.quantity;
    }
    return total;
}

size_t Order::item_count() const {
    return items_.size();
}

// BankAccount tracks a balance in cents for one owner.
class BankAccount {
public:
    explicit BankAccount(std::string owner);

    void deposit(long long amount);
    bool withdraw(long long amount);
    long long balance() const;

private:
    std::string owner_;
    long long balanceCents_ = 0;
};

BankAccount::BankAccount(std::string owner) : owner_(std::move(owner)) {}

void BankAccount::deposit(long long amount) {
    if (amount > 0) {
        balanceCents_ += amount;
    }
}

bool BankAccount::withdraw(long long amount) {
    if (amount <= 0 || amount > balanceCents_) {
        return false;
    }
    balanceCents_ -= amount;
    return true;
}

long long BankAccount::balance() const {
    return balanceCents_;
}

// Book is a published work in the library catalog.
class Book {
public:
    Book(std::string title, std::string author, int pages);

    std::string citation() const;
    int pages() const;

private:
    std::string title_;
    std::string author_;
    int pages_;
};

Book::Book(std::string title, std::string author, int pages)
    : title_(std::move(title)), author_(std::move(author)), pages_(pages) {}

std::string Book::citation() const {
    return author_ + ". " + title_ + ".";
}

int Book::pages() const {
    return pages_;
}

// Vehicle records the facts of a car in a fleet.
class Vehicle {
public:
    Vehicle(std::string make, std::string model, int year, int mileage);

    int age(int currentYear) const;
    void drive(int miles);

private:
    std::string make_;
    std::string model_;
    int year_;
    int mileage_;
};

Vehicle::Vehicle(std::string make, std::string model, int year, int mileage)
    : make_(std::move(make)), model_(std::move(model)), year_(year),
      mileage_(mileage) {}

int Vehicle::age(int currentYear) const {
    return currentYear < year_ ? 0 : currentYear - year_;
}

void Vehicle::drive(int miles) {
    if (miles > 0) {
        mileage_ += miles;
    }
}

// Employee is a member of staff with a yearly salary.
class Employee {
public:
    Employee(int id, std::string name, std::string department, int salary);

    int annual_bonus(double percent) const;
    std::string department() const;

private:
    int id_;
    std::string name_;
    std::string department_;
    int salary_;
};

Employee::Employee(int id, std::string name, std::string department, int salary)
    : id_(id), name_(std::move(name)), department_(std::move(department)),
      salary_(salary) {}

int Employee::annual_bonus(double percent) const {
    return static_cast<int>(salary_ * percent / 100.0);
}

std::string Employee::department() const {
    return department_;
}

// Student holds the course grades of one learner.
class Student {
public:
    explicit Student(std::string name);

    void add_grade(double grade);
    double average() const;
    size_t grade_count() const;

private:
    std::string name_;
    std::vector<double> grades_;
};

Student::Student(std::string name) : name_(std::move(name)) {}

void Student::add_grade(double grade) {
    if (grade >= 0.0 && grade <= 100.0) {
        grades_.push_back(grade);
    }
}

double Student::average() const {
    if (grades_.empty()) {
        return 0.0;
    }
    double sum = 0.0;
    for (double grade : grades_) {
        sum += grade;
    }
    return sum / static_cast<double>(grades_.size());
}

size_t Student::grade_count() const {
    return grades_.size();
}
