// filesystem_utils.cpp — generated by scripts/generate/generate-cpp.mjs (do not edit by hand).
// Realistic C++ typing blocks for vibetyper: filesystem helpers.

#include <algorithm>
#include <cctype>
#include <chrono>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

// file_exists reports whether path refers to an existing regular file.
bool file_exists(const std::string& path) {
    std::error_code ec;
    return std::filesystem::is_regular_file(path, ec) && !ec;
}

// is_directory reports whether path refers to an existing directory.
bool is_directory(const std::string& path) {
    std::error_code ec;
    return std::filesystem::is_directory(path, ec) && !ec;
}

// read_lines reads a text file and returns its lines.
std::vector<std::string> read_lines(const std::string& path) {
    std::vector<std::string> lines;
    std::ifstream input(path);
    std::string line;
    while (std::getline(input, line)) {
        lines.push_back(line);
    }
    return lines;
}

// write_lines writes each string as its own line to a file.
bool write_lines(const std::string& path,
                 const std::vector<std::string>& lines) {
    std::ofstream output(path, std::ios::trunc);
    if (!output) {
        return false;
    }
    for (const std::string& line : lines) {
        output << line << '\n';
    }
    return output.good();
}

// copy_file copies src to dst, overwriting an existing destination.
bool copy_file(const std::string& src, const std::string& dst) {
    std::error_code ec;
    std::filesystem::copy_file(src, dst,
                               std::filesystem::copy_options::overwrite_existing,
                               ec);
    return !ec;
}

// append_line adds one line to the end of a file, creating it if needed.
bool append_line(const std::string& path, const std::string& line) {
    std::ofstream output(path, std::ios::app);
    if (!output) {
        return false;
    }
    output << line << '\n';
    return output.good();
}

// file_extension returns the lowercase extension of a path including
// the dot.
std::string file_extension(const std::string& path) {
    std::string ext = std::filesystem::path(path).extension().string();
    std::transform(ext.begin(), ext.end(), ext.begin(),
                   [](unsigned char c) { return std::tolower(c); });
    return ext;
}

// file_stem returns the file name without its extension.
std::string file_stem(const std::string& path) {
    return std::filesystem::path(path).stem().string();
}

// file_size returns the size of a file in bytes, or -1 on error.
long long file_size(const std::string& path) {
    std::error_code ec;
    auto size = std::filesystem::file_size(path, ec);
    return ec ? -1 : static_cast<long long>(size);
}

// list_files returns every file under root whose extension matches
// exts.
std::vector<std::string> list_files(const std::string& root,
                                    const std::vector<std::string>& exts) {
    std::vector<std::string> out;
    std::error_code ec;
    for (const auto& entry :
         std::filesystem::recursive_directory_iterator(root, ec)) {
        if (ec || entry.is_directory()) {
            continue;
        }
        std::string ext = entry.path().extension().string();
        for (const std::string& wanted : exts) {
            if (ext == wanted) {
                out.push_back(entry.path().string());
                break;
            }
        }
    }
    return out;
}

// ensure_dir creates dir and any missing parents.
bool ensure_dir(const std::string& dir) {
    std::error_code ec;
    std::filesystem::create_directories(dir, ec);
    return !ec;
}

// remove_if_exists deletes path, ignoring "not found" errors.
bool remove_if_exists(const std::string& path) {
    std::error_code ec;
    std::filesystem::remove(path, ec);
    return !ec || ec == std::errc::no_such_file_or_directory;
}

// find_upward searches for name from start up through parent
// directories.
std::string find_upward(const std::string& start, const std::string& name) {
    std::filesystem::path dir(start);
    while (!dir.empty()) {
        std::filesystem::path candidate = dir / name;
        std::error_code ec;
        if (std::filesystem::is_regular_file(candidate, ec) && !ec) {
            return candidate.string();
        }
        std::filesystem::path parent = dir.parent_path();
        if (parent == dir) {
            break;
        }
        dir = parent;
    }
    return "";
}

// touch_file creates an empty file at path if missing.
bool touch_file(const std::string& path) {
    std::ofstream output(path, std::ios::app);
    return output.good();
}

// directory_of returns the parent directory of path.
std::string directory_of(const std::string& path) {
    return std::filesystem::path(path).parent_path().string();
}

// is_hidden reports whether the file name starts with a dot.
bool is_hidden(const std::string& path) {
    std::string name = std::filesystem::path(path).filename().string();
    return !name.empty() && name.front() == '.';
}

// rename_file moves path to newName, failing when the target exists.
bool rename_file(const std::string& path, const std::string& newName) {
    std::error_code ec;
    std::filesystem::rename(path, newName, ec);
    return !ec;
}

// last_modified returns the modification time of a file as a string.
std::string last_modified(const std::string& path) {
    std::error_code ec;
    auto time = std::filesystem::last_write_time(path, ec);
    if (ec) {
        return "";
    }
    auto seconds = std::chrono::duration_cast<std::chrono::seconds>(
                       time.time_since_epoch())
                       .count();
    return std::to_string(seconds);
}

// count_files reports how many regular files live under root.
size_t count_files(const std::string& root) {
    std::error_code ec;
    size_t count = 0;
    for (const auto& entry :
         std::filesystem::recursive_directory_iterator(root, ec)) {
        if (!ec && entry.is_regular_file()) {
            ++count;
        }
    }
    return count;
}
