// formatting_utils.cpp — generated by scripts/generate/generate-cpp.mjs (do not edit by hand).
// Realistic C++ typing blocks for vibetyper: number, size and text formatting.

#include <algorithm>
#include <cctype>
#include <iomanip>
#include <sstream>
#include <string>
#include <vector>

// comma_separate inserts thousands separators into an integer.
std::string comma_separate(long long n) {
    bool negative = n < 0;
    std::string digits = std::to_string(negative ? -n : n);
    std::string out;
    int count = 0;
    for (int i = static_cast<int>(digits.size()) - 1; i >= 0; --i) {
        out.push_back(digits[i]);
        if (++count % 3 == 0 && i > 0) {
            out.push_back(',');
        }
    }
    std::reverse(out.begin(), out.end());
    return negative ? "-" + out : out;
}

// percent_string renders a fraction as a percentage with fixed decimals.
std::string percent_string(double value, int decimals) {
    std::ostringstream out;
    out << std::fixed << std::setprecision(decimals) << (value * 100.0) << "%";
    return out.str();
}

// human_bytes renders a byte count as a compact human-readable size.
std::string human_bytes(long long bytes) {
    const char* units[] = {"B", "KiB", "MiB", "GiB", "TiB"};
    double value = static_cast<double>(bytes);
    int unit = 0;
    while (value >= 1024.0 && unit < 4) {
        value /= 1024.0;
        ++unit;
    }
    std::ostringstream out;
    out << std::fixed << std::setprecision(unit == 0 ? 0 : 1) << value << " "
        << units[unit];
    return out.str();
}

// human_duration renders seconds as "2h 5m" style text.
std::string human_duration(long long seconds) {
    std::ostringstream out;
    if (seconds < 60) {
        out << seconds << "s";
        return out.str();
    }
    long long minutes = seconds / 60;
    if (minutes < 60) {
        out << minutes << "m " << (seconds % 60) << "s";
        return out.str();
    }
    long long hours = minutes / 60;
    if (hours < 24) {
        out << hours << "h " << (minutes % 60) << "m";
        return out.str();
    }
    out << (hours / 24) << "d " << (hours % 24) << "h";
    return out.str();
}

// pluralize appends an "s" unless count is exactly one.
std::string pluralize(size_t count, const std::string& singular) {
    return count == 1 ? singular : singular + "s";
}

// ordinal_suffix returns the ordinal form of a number, e.g. 3 -> "3rd".
std::string ordinal_suffix(int n) {
    int mod100 = n % 100;
    if (mod100 >= 11 && mod100 <= 13) {
        return std::to_string(n) + "th";
    }
    switch (n % 10) {
    case 1: return std::to_string(n) + "st";
    case 2: return std::to_string(n) + "nd";
    case 3: return std::to_string(n) + "rd";
    default: return std::to_string(n) + "th";
    }
}

// join_with_and renders a list in prose form: "a, b and c".
std::string join_with_and(const std::vector<std::string>& items) {
    if (items.empty()) {
        return "";
    }
    if (items.size() == 1) {
        return items.front();
    }
    std::string out;
    for (size_t i = 0; i + 1 < items.size(); ++i) {
        if (i > 0) {
            out += ", ";
        }
        out += items[i];
    }
    out += " and " + items.back();
    return out;
}

// format_money renders a dollar amount given in cents.
std::string format_money(long long cents) {
    bool negative = cents < 0;
    long long abs = negative ? -cents : cents;
    std::string dollars = comma_separate(abs / 100);
    long long remainder = abs % 100;
    std::ostringstream out;
    if (negative) {
        out << "-";
    }
    out << dollars << "." << std::setw(2) << std::setfill('0') << remainder;
    return out.str();
}

// truncate_middle keeps the start and end of a long string.
std::string truncate_middle(const std::string& text, size_t maxLength) {
    if (text.size() <= maxLength || maxLength <= 3) {
        return text;
    }
    size_t keep = (maxLength - 3) / 2;
    return text.substr(0, keep) + "..." +
           text.substr(text.size() - keep);
}

// format_ratio renders a ratio in reduced form, e.g. 8:4 -> "2:1".
std::string format_ratio(int a, int b) {
    int x = a < 0 ? -a : a;
    int y = b < 0 ? -b : b;
    while (y != 0) {
        int t = x % y;
        x = y;
        y = t;
    }
    if (x == 0) {
        return "0:0";
    }
    return std::to_string(a / x) + ":" + std::to_string(b / x);
}

// pad_number zero-pads an integer to at least width digits.
std::string pad_number(int n, int width) {
    std::ostringstream out;
    out << std::setw(width) << std::setfill('0') << n;
    return out.str();
}

// relative_time renders a seconds-ago value as "5m ago".
std::string relative_time(long long secondsAgo) {
    if (secondsAgo < 60) {
        return "just now";
    }
    if (secondsAgo < 3600) {
        return std::to_string(secondsAgo / 60) + "m ago";
    }
    if (secondsAgo < 86400) {
        return std::to_string(secondsAgo / 3600) + "h ago";
    }
    return std::to_string(secondsAgo / 86400) + "d ago";
}

// format_float renders a double with up to maxDecimals, dropping
// trailing zeros, e.g. 3.50 -> "3.5".
std::string format_float(double value, int maxDecimals) {
    std::ostringstream out;
    out << std::fixed << std::setprecision(maxDecimals) << value;
    std::string text = out.str();
    while (!text.empty() && text.back() == '0') {
        text.pop_back();
    }
    if (!text.empty() && text.back() == '.') {
        text.pop_back();
    }
    return text;
}

// upper_first capitalizes the first letter of a string.
std::string upper_first(const std::string& text) {
    if (text.empty()) {
        return text;
    }
    std::string out = text;
    out[0] = static_cast<char>(
        std::toupper(static_cast<unsigned char>(out[0])));
    return out;
}

// bytes_per_second renders a transfer rate from bytes and elapsed
// seconds.
std::string bytes_per_second(long long bytes, double seconds) {
    if (seconds <= 0.0) {
        return "0 B/s";
    }
    return human_bytes(static_cast<long long>(bytes / seconds)) + "/s";
}

// signed_number renders a double with an explicit sign and fixed
// decimals.
std::string signed_number(double value, int decimals) {
    std::ostringstream out;
    out << std::showpos << std::fixed << std::setprecision(decimals) << value;
    return out.str();
}

// percent_change reports the relative change from oldValue to newValue.
std::string percent_change(double oldValue, double newValue) {
    if (oldValue == 0.0) {
        return "n/a";
    }
    double change = (newValue - oldValue) / oldValue * 100.0;
    std::ostringstream out;
    out << std::showpos << std::fixed << std::setprecision(1) << change << "%";
    return out.str();
}

// size_with_unit appends a K/M/G/T suffix to a count.
std::string size_with_unit(long long count) {
    const char* suffixes[] = {"", "K", "M", "G", "T"};
    double value = static_cast<double>(count);
    int index = 0;
    while (value >= 1000.0 && index < 4) {
        value /= 1000.0;
        ++index;
    }
    std::ostringstream out;
    out << std::fixed << std::setprecision(index == 0 ? 0 : 1) << value
        << suffixes[index];
    return out.str();
}

// format_table_row pads cells to their column widths and joins them.
std::string format_table_row(const std::vector<std::string>& cells,
                             const std::vector<size_t>& widths) {
    std::string out;
    for (size_t i = 0; i < cells.size(); ++i) {
        if (i > 0) {
            out += "  ";
        }
        std::string cell = cells[i];
        if (i < widths.size() && cell.size() < widths[i]) {
            cell.append(widths[i] - cell.size(), ' ');
        }
        out += cell;
    }
    return out;
}
