// geometry_math.cpp — generated by scripts/generate/generate-cpp.mjs (do not edit by hand).
// Realistic C++ typing blocks for vibetyper: geometry and matrix helpers.

#include <algorithm>
#include <cmath>
#include <vector>

// Point is a 2D coordinate.
struct Point {
    double x = 0.0;
    double y = 0.0;
};

// point_distance returns the Euclidean distance between two points.
double point_distance(const Point& a, const Point& b) {
    double dx = a.x - b.x;
    double dy = a.y - b.y;
    return std::sqrt(dx * dx + dy * dy);
}

// point_midpoint returns the point halfway between a and b.
Point point_midpoint(const Point& a, const Point& b) {
    return Point{(a.x + b.x) / 2.0, (a.y + b.y) / 2.0};
}

// Rect is an axis-aligned rectangle.
struct Rect {
    Point min;
    Point max;
};

// rect_contains reports whether p lies inside the rectangle, inclusive.
bool rect_contains(const Rect& rect, const Point& p) {
    return p.x >= rect.min.x && p.x <= rect.max.x &&
           p.y >= rect.min.y && p.y <= rect.max.y;
}

// rect_area is the rectangle's width times height.
double rect_area(const Rect& rect) {
    return (rect.max.x - rect.min.x) * (rect.max.y - rect.min.y);
}

// kPi is pi to enough digits for double precision.
constexpr double kPi = 3.14159265358979323846;

// Circle is defined by a center point and a radius.
struct Circle {
    Point center;
    double radius = 0.0;
};

// circle_area is pi times the radius squared.
double circle_area(const Circle& circle) {
    return kPi * circle.radius * circle.radius;
}

// circle_circumference is the distance around the circle.
double circle_circumference(const Circle& circle) {
    return 2.0 * kPi * circle.radius;
}

// Vec2 is a 2D vector.
struct Vec2 {
    double x = 0.0;
    double y = 0.0;
};

// vec_add returns the component-wise sum of two vectors.
Vec2 vec_add(const Vec2& a, const Vec2& b) {
    return Vec2{a.x + b.x, a.y + b.y};
}

// vec_dot returns the scalar product of two vectors.
double vec_dot(const Vec2& a, const Vec2& b) {
    return a.x * b.x + a.y * b.y;
}

// vec_length is the magnitude of the vector.
double vec_length(const Vec2& v) {
    return std::hypot(v.x, v.y);
}

// rotate_point rotates p around the origin by the given angle in radians.
Point rotate_point(const Point& p, double angle) {
    double cos = std::cos(angle);
    double sin = std::sin(angle);
    return Point{p.x * cos - p.y * sin, p.x * sin + p.y * cos};
}

// angle_between returns the unsigned angle in radians between two vectors.
double angle_between(const Vec2& a, const Vec2& b) {
    double denom = vec_length(a) * vec_length(b);
    if (denom == 0.0) {
        return 0.0;
    }
    return std::acos(vec_dot(a, b) / denom);
}

// polygon_area computes the signed area of a polygon with the shoelace
// formula.
double polygon_area(const std::vector<Point>& points) {
    if (points.size() < 3) {
        return 0.0;
    }
    double sum = 0.0;
    for (size_t i = 0; i < points.size(); ++i) {
        const Point& a = points[i];
        const Point& b = points[(i + 1) % points.size()];
        sum += a.x * b.y - b.x * a.y;
    }
    return sum / 2.0;
}

// distance_to_segment returns the shortest distance from p to the
// segment between a and b.
double distance_to_segment(const Point& p, const Point& a, const Point& b) {
    double dx = b.x - a.x;
    double dy = b.y - a.y;
    if (dx == 0.0 && dy == 0.0) {
        return point_distance(p, a);
    }
    double t = ((p.x - a.x) * dx + (p.y - a.y) * dy) / (dx * dx + dy * dy);
    t = std::max(0.0, std::min(1.0, t));
    Point closest{a.x + t * dx, a.y + t * dy};
    return point_distance(p, closest);
}

// matrix_multiply multiplies two matrices when their dimensions agree.
std::vector<std::vector<double>> matrix_multiply(
    const std::vector<std::vector<double>>& a,
    const std::vector<std::vector<double>>& b) {
    std::vector<std::vector<double>> out;
    if (a.empty() || b.empty() || a.front().size() != b.size()) {
        return out;
    }
    size_t rows = a.size(), inner = b.size(), cols = b.front().size();
    out.assign(rows, std::vector<double>(cols, 0.0));
    for (size_t i = 0; i < rows; ++i) {
        for (size_t k = 0; k < inner; ++k) {
            for (size_t j = 0; j < cols; ++j) {
                out[i][j] += a[i][k] * b[k][j];
            }
        }
    }
    return out;
}

// matrix_scale multiplies every element of a matrix by factor.
std::vector<std::vector<double>> matrix_scale(
    const std::vector<std::vector<double>>& matrix, double factor) {
    std::vector<std::vector<double>> out;
    out.reserve(matrix.size());
    for (const auto& row : matrix) {
        std::vector<double> scaled;
        scaled.reserve(row.size());
        for (double v : row) {
            scaled.push_back(v * factor);
        }
        out.push_back(scaled);
    }
    return out;
}

// determinant_2x2 computes the determinant of a 2x2 matrix.
double determinant_2x2(const std::vector<std::vector<double>>& matrix) {
    return matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0];
}

// clamp_angle_deg normalizes an angle in degrees to [0, 360).
double clamp_angle_deg(double degrees) {
    degrees = std::fmod(degrees, 360.0);
    return degrees < 0.0 ? degrees + 360.0 : degrees;
}

// reflect_point mirrors p across the point center.
Point reflect_point(const Point& p, const Point& center) {
    return Point{2.0 * center.x - p.x, 2.0 * center.y - p.y};
}

// normalize_vector returns a unit vector with the same direction.
Vec2 normalize_vector(const Vec2& v) {
    double length = vec_length(v);
    if (length == 0.0) {
        return Vec2{0.0, 0.0};
    }
    return Vec2{v.x / length, v.y / length};
}
