// math_numeric.cpp — generated by scripts/generate/generate-cpp.mjs (do not edit by hand).
// Realistic C++ typing blocks for vibetyper: math and numeric helpers.

#include <algorithm>
#include <cmath>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

// gcd_of returns the greatest common divisor of two integers.
int gcd_of(int a, int b) {
    while (b != 0) {
        int t = a % b;
        a = b;
        b = t;
    }
    return a < 0 ? -a : a;
}

// lcm_of returns the least common multiple of two positive integers.
long long lcm_of(int a, int b) {
    if (a == 0 || b == 0) {
        return 0;
    }
    return static_cast<long long>(a) / gcd_of(a, b) * b;
}

// is_prime reports whether n is a prime number via trial division.
bool is_prime(int n) {
    if (n < 2) {
        return false;
    }
    for (int d = 2; d * d <= n; ++d) {
        if (n % d == 0) {
            return false;
        }
    }
    return true;
}

// sieve_of_eratosthenes marks composite numbers up to limit.
std::vector<bool> sieve_of_eratosthenes(int limit) {
    std::vector<bool> composite(limit + 1, false);
    for (int i = 2; i * i <= limit; ++i) {
        if (!composite[i]) {
            for (int j = i * i; j <= limit; j += i) {
                composite[j] = true;
            }
        }
    }
    return composite;
}

// nth_fibonacci returns the n-th Fibonacci number, 0-indexed.
long long nth_fibonacci(int n) {
    if (n < 2) {
        return n;
    }
    long long a = 0, b = 1;
    for (int i = 2; i <= n; ++i) {
        long long next = a + b;
        a = b;
        b = next;
    }
    return b;
}

// factorial_iterative computes n! with a simple loop.
long long factorial_iterative(int n) {
    long long result = 1;
    for (int i = 2; i <= n; ++i) {
        result *= i;
    }
    return result;
}

// binomial_coefficient computes C(n, k) without overflowing intermediate
// factorials.
long long binomial_coefficient(int n, int k) {
    if (k < 0 || k > n) {
        return 0;
    }
    if (k > n - k) {
        k = n - k;
    }
    long long result = 1;
    for (int i = 1; i <= k; ++i) {
        result = result * (n - k + i) / i;
    }
    return result;
}

// mean_of returns the arithmetic average of a vector of doubles.
double mean_of(const std::vector<double>& values) {
    if (values.empty()) {
        return 0.0;
    }
    double sum = 0.0;
    for (double v : values) {
        sum += v;
    }
    return sum / static_cast<double>(values.size());
}

// median_of returns the middle value of a sorted copy of values.
double median_of(std::vector<double> values) {
    if (values.empty()) {
        return 0.0;
    }
    std::sort(values.begin(), values.end());
    size_t mid = values.size() / 2;
    if (values.size() % 2 == 1) {
        return values[mid];
    }
    return (values[mid - 1] + values[mid]) / 2.0;
}

// mode_of returns the most frequent value, first occurrence wins ties.
int mode_of(const std::vector<int>& values) {
    std::unordered_map<int, int> counts;
    int best = 0, bestCount = 0;
    for (int v : values) {
        int c = ++counts[v];
        if (c > bestCount) {
            best = v;
            bestCount = c;
        }
    }
    return best;
}

// variance_of computes the population variance of a sample.
double variance_of(const std::vector<double>& values) {
    if (values.size() < 2) {
        return 0.0;
    }
    double m = mean_of(values);
    double sum = 0.0;
    for (double v : values) {
        double diff = v - m;
        sum += diff * diff;
    }
    return sum / static_cast<double>(values.size());
}

// stddev_of returns the population standard deviation of values.
double stddev_of(const std::vector<double>& values) {
    return std::sqrt(variance_of(values));
}

// clamp_value restricts value to the inclusive range [lo, hi].
int clamp_value(int value, int lo, int hi) {
    return std::max(lo, std::min(hi, value));
}

// lerp linearly interpolates between a and b by the factor t.
double lerp(double a, double b, double t) {
    return a + (b - a) * t;
}

// round_to rounds value to the nearest multiple of 10^-places.
double round_to(double value, int places) {
    double factor = std::pow(10.0, places);
    return std::round(value * factor) / factor;
}

// is_perfect_square reports whether n is the square of an integer.
bool is_perfect_square(int n) {
    if (n < 0) {
        return false;
    }
    int root = static_cast<int>(std::sqrt(static_cast<double>(n)));
    return root * root == n;
}

// sum_digits adds up the decimal digits of a non-negative integer.
int sum_digits(int n) {
    int sum = 0;
    while (n > 0) {
        sum += n % 10;
        n /= 10;
    }
    return sum;
}

// reverse_number reverses the decimal digits of an integer.
int reverse_number(int n) {
    int reversed = 0;
    while (n != 0) {
        reversed = reversed * 10 + n % 10;
        n /= 10;
    }
    return reversed;
}

// is_palindrome_number reports whether n reads the same both ways.
bool is_palindrome_number(int n) {
    if (n < 0) {
        return false;
    }
    return n == reverse_number(n);
}

// prime_factors decomposes n into its prime factors in ascending order.
std::vector<int> prime_factors(int n) {
    std::vector<int> factors;
    for (int d = 2; d * d <= n; ++d) {
        while (n % d == 0) {
            factors.push_back(d);
            n /= d;
        }
    }
    if (n > 1) {
        factors.push_back(n);
    }
    return factors;
}

// next_power_of_two returns the smallest power of two >= n.
int next_power_of_two(int n) {
    int p = 1;
    while (p < n) {
        p <<= 1;
    }
    return p;
}

// collatz_steps counts the steps for n to reach 1 under the Collatz rule.
int collatz_steps(int n) {
    int steps = 0;
    while (n != 1) {
        if (n % 2 == 0) {
            n /= 2;
        } else {
            n = 3 * n + 1;
        }
        ++steps;
    }
    return steps;
}

// int_to_roman converts an integer in [1, 3999] to Roman numerals.
std::string int_to_roman(int n) {
    const std::vector<std::pair<int, std::string>> table = {
        {1000, "M"}, {900, "CM"}, {500, "D"}, {400, "CD"},
        {100, "C"}, {90, "XC"}, {50, "L"}, {40, "XL"},
        {10, "X"}, {9, "IX"}, {5, "V"}, {4, "IV"}, {1, "I"}};
    std::string out;
    for (const auto& entry : table) {
        while (n >= entry.first) {
            out += entry.second;
            n -= entry.first;
        }
    }
    return out;
}

// roman_to_int parses a Roman numeral string into an integer.
int roman_to_int(const std::string& roman) {
    std::unordered_map<char, int> values = {
        {'I', 1}, {'V', 5}, {'X', 10}, {'L', 50},
        {'C', 100}, {'D', 500}, {'M', 1000}};
    int total = 0;
    int prev = 0;
    for (char c : roman) {
        int v = values[c];
        total += (v > prev) ? v - 2 * prev : v;
        prev = v;
    }
    return total;
}

// is_perfect_number reports whether n equals the sum of its proper
// divisors.
bool is_perfect_number(int n) {
    if (n < 2) {
        return false;
    }
    int sum = 1;
    for (int d = 2; d * d <= n; ++d) {
        if (n % d == 0) {
            sum += d;
            if (d != n / d) {
                sum += n / d;
            }
        }
    }
    return sum == n;
}

// digit_count returns how many decimal digits a non-negative integer has.
int digit_count(int n) {
    if (n == 0) {
        return 1;
    }
    int count = 0;
    while (n > 0) {
        ++count;
        n /= 10;
    }
    return count;
}
