// string_utils.cpp — generated by scripts/generate/generate-cpp.mjs (do not edit by hand).
// Realistic C++ typing blocks for vibetyper: string utilities.

#include <algorithm>
#include <cctype>
#include <sstream>
#include <string>
#include <unordered_map>
#include <vector>

// to_lower returns a lowercase copy of the input string.
std::string to_lower(std::string text) {
    std::transform(text.begin(), text.end(), text.begin(),
                   [](unsigned char c) { return std::tolower(c); });
    return text;
}

// to_upper returns an uppercase copy of the input string.
std::string to_upper(std::string text) {
    std::transform(text.begin(), text.end(), text.begin(),
                   [](unsigned char c) { return std::toupper(c); });
    return text;
}

// swapcase flips the case of every letter in text.
std::string swapcase(const std::string& text) {
    std::string out = text;
    for (char& c : out) {
        unsigned char u = static_cast<unsigned char>(c);
        if (std::islower(u)) {
            c = static_cast<char>(std::toupper(u));
        } else if (std::isupper(u)) {
            c = static_cast<char>(std::tolower(u));
        }
    }
    return out;
}

// trim removes leading and trailing whitespace from a string.
std::string trim(const std::string& text) {
    size_t start = text.find_first_not_of(" \t\r\n");
    if (start == std::string::npos) {
        return "";
    }
    size_t end = text.find_last_not_of(" \t\r\n");
    return text.substr(start, end - start + 1);
}

// split breaks text into pieces on the given delimiter.
std::vector<std::string> split(const std::string& text, char delimiter) {
    std::vector<std::string> parts;
    std::stringstream stream(text);
    std::string piece;
    while (std::getline(stream, piece, delimiter)) {
        parts.push_back(piece);
    }
    return parts;
}

// join concatenates items with a separator between them.
std::string join(const std::vector<std::string>& items, const std::string& separator) {
    std::ostringstream out;
    for (size_t i = 0; i < items.size(); ++i) {
        if (i > 0) {
            out << separator;
        }
        out << items[i];
    }
    return out.str();
}

// replace_all swaps every occurrence of from for to in text.
std::string replace_all(std::string text, const std::string& from, const std::string& to) {
    if (from.empty()) {
        return text;
    }
    size_t pos = 0;
    while ((pos = text.find(from, pos)) != std::string::npos) {
        text.replace(pos, from.size(), to);
        pos += to.size();
    }
    return text;
}

// starts_with reports whether text begins with the given prefix.
bool starts_with(const std::string& text, const std::string& prefix) {
    return text.size() >= prefix.size() &&
           text.compare(0, prefix.size(), prefix) == 0;
}

// ends_with reports whether text ends with the given suffix.
bool ends_with(const std::string& text, const std::string& suffix) {
    return text.size() >= suffix.size() &&
           text.compare(text.size() - suffix.size(), suffix.size(), suffix) == 0;
}

// is_blank reports whether text is empty or only whitespace.
bool is_blank(const std::string& text) {
    for (char c : text) {
        if (!std::isspace(static_cast<unsigned char>(c))) {
            return false;
        }
    }
    return true;
}

// count_occurrences counts how often needle appears in text.
size_t count_occurrences(const std::string& text, const std::string& needle) {
    size_t count = 0;
    size_t pos = 0;
    while ((pos = text.find(needle, pos)) != std::string::npos) {
        ++count;
        pos += needle.size();
    }
    return count;
}

// is_anagram reports whether two strings use exactly the same letters.
bool is_anagram(const std::string& a, const std::string& b) {
    if (a.size() != b.size()) {
        return false;
    }
    std::unordered_map<char, int> counts;
    for (char c : a) {
        counts[c]++;
    }
    for (char c : b) {
        if (--counts[c] < 0) {
            return false;
        }
    }
    return true;
}

// word_count returns the number of whitespace-separated words in text.
size_t word_count(const std::string& text) {
    std::istringstream stream(text);
    std::string word;
    size_t count = 0;
    while (stream >> word) {
        ++count;
    }
    return count;
}

// to_title_case capitalizes the first letter of every word.
std::string to_title_case(const std::string& text) {
    std::string out = text;
    bool newWord = true;
    for (char& c : out) {
        if (std::isspace(static_cast<unsigned char>(c))) {
            newWord = true;
        } else if (newWord) {
            c = static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
            newWord = false;
        } else {
            c = static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
        }
    }
    return out;
}

// truncate cuts text at a word boundary and appends an ellipsis.
std::string truncate(const std::string& text, size_t maxLength) {
    if (text.size() <= maxLength) {
        return text;
    }
    size_t cut = text.find_last_of(' ', maxLength);
    if (cut == std::string::npos || cut == 0) {
        cut = maxLength;
    }
    return text.substr(0, cut) + "...";
}

// pad_left prepends fill characters until text reaches width.
std::string pad_left(const std::string& text, size_t width, char fill) {
    if (text.size() >= width) {
        return text;
    }
    return std::string(width - text.size(), fill) + text;
}

// pad_right appends fill characters until text reaches width.
std::string pad_right(const std::string& text, size_t width, char fill) {
    if (text.size() >= width) {
        return text;
    }
    return text + std::string(width - text.size(), fill);
}

// extract_digits pulls every integer literal out of a string.
std::vector<int> extract_digits(const std::string& text) {
    std::vector<int> numbers;
    for (size_t i = 0; i < text.size();) {
        if (!std::isdigit(static_cast<unsigned char>(text[i]))) {
            ++i;
            continue;
        }
        size_t start = i;
        while (i < text.size() && std::isdigit(static_cast<unsigned char>(text[i]))) {
            ++i;
        }
        numbers.push_back(std::stoi(text.substr(start, i - start)));
    }
    return numbers;
}

// camel_to_snake converts "maxConnections" to "max_connections".
std::string camel_to_snake(const std::string& text) {
    std::string out;
    for (char c : text) {
        if (std::isupper(static_cast<unsigned char>(c))) {
            if (!out.empty()) {
                out.push_back('_');
            }
            out.push_back(static_cast<char>(std::tolower(static_cast<unsigned char>(c))));
        } else {
            out.push_back(c);
        }
    }
    return out;
}

// snake_to_camel converts "max_connections" to "maxConnections".
std::string snake_to_camel(const std::string& text) {
    std::string out;
    bool upperNext = false;
    for (char c : text) {
        if (c == '_') {
            upperNext = true;
        } else if (upperNext) {
            out.push_back(static_cast<char>(std::toupper(static_cast<unsigned char>(c))));
            upperNext = false;
        } else {
            out.push_back(c);
        }
    }
    return out;
}

// common_prefix returns the longest prefix shared by all given strings.
std::string common_prefix(const std::vector<std::string>& words) {
    if (words.empty()) {
        return "";
    }
    std::string prefix = words.front();
    for (size_t i = 1; i < words.size() && !prefix.empty(); ++i) {
        size_t len = 0;
        while (len < prefix.size() && len < words[i].size() &&
               prefix[len] == words[i][len]) {
            ++len;
        }
        prefix.resize(len);
    }
    return prefix;
}

// mask_middle hides the middle of a string, keeping the ends visible.
std::string mask_middle(const std::string& text, size_t keepStart, size_t keepEnd) {
    if (text.size() <= keepStart + keepEnd) {
        return std::string(text.size(), '*');
    }
    return text.substr(0, keepStart) +
           std::string(text.size() - keepStart - keepEnd, '*') +
           text.substr(text.size() - keepEnd);
}

// slugify converts arbitrary text into a lowercase hyphen-separated slug.
std::string slugify(const std::string& text) {
    std::string slug;
    bool lastDash = false;
    for (unsigned char c : text) {
        if (std::isalnum(c)) {
            slug.push_back(static_cast<char>(std::tolower(c)));
            lastDash = false;
        } else if (!lastDash && !slug.empty()) {
            slug.push_back('-');
            lastDash = true;
        }
    }
    while (!slug.empty() && slug.back() == '-') {
        slug.pop_back();
    }
    return slug;
}

// levenshtein_distance computes the edit distance between two strings
// using a two-row dynamic programming table.
int levenshtein_distance(const std::string& a, const std::string& b) {
    std::vector<int> prev(b.size() + 1), curr(b.size() + 1);
    for (size_t j = 0; j <= b.size(); ++j) {
        prev[j] = static_cast<int>(j);
    }
    for (size_t i = 1; i <= a.size(); ++i) {
        curr[0] = static_cast<int>(i);
        for (size_t j = 1; j <= b.size(); ++j) {
            int cost = (a[i - 1] == b[j - 1]) ? 0 : 1;
            curr[j] = std::min({prev[j] + 1, curr[j - 1] + 1, prev[j - 1] + cost});
        }
        std::swap(prev, curr);
    }
    return prev[b.size()];
}
