// threading_utils.cpp — generated by scripts/generate/generate-cpp.mjs (do not edit by hand).
// Realistic C++ typing blocks for vibetyper: threading and concurrency utilities.

#include <algorithm>
#include <atomic>
#include <chrono>
#include <condition_variable>
#include <functional>
#include <mutex>
#include <queue>
#include <thread>
#include <vector>

// ThreadSafeCounter is an atomic integer counter.
class ThreadSafeCounter {
public:
    void increment() { value_.fetch_add(1, std::memory_order_relaxed); }
    long load() const { return value_.load(std::memory_order_relaxed); }

private:
    std::atomic<long> value_{0};
};

// ThreadSafeQueue is a blocking FIFO queue for worker threads.
class ThreadSafeQueue {
public:
    void push(int value);
    bool pop(int& value, std::chrono::milliseconds timeout);

private:
    std::mutex mutex_;
    std::condition_variable notEmpty_;
    std::queue<int> items_;
};

void ThreadSafeQueue::push(int value) {
    {
        std::lock_guard<std::mutex> lock(mutex_);
        items_.push(value);
    }
    notEmpty_.notify_one();
}

bool ThreadSafeQueue::pop(int& value, std::chrono::milliseconds timeout) {
    std::unique_lock<std::mutex> lock(mutex_);
    if (!notEmpty_.wait_for(lock, timeout, [this] { return !items_.empty(); })) {
        return false;
    }
    value = items_.front();
    items_.pop();
    return true;
}

// parallel_sum adds a vector across several threads.
long long parallel_sum(const std::vector<int>& values, size_t threads) {
    if (values.empty()) {
        return 0;
    }
    if (threads == 0) {
        threads = 1;
    }
    std::atomic<long long> total{0};
    std::vector<std::thread> workers;
    size_t chunkSize = (values.size() + threads - 1) / threads;
    for (size_t start = 0; start < values.size(); start += chunkSize) {
        workers.emplace_back([&values, &total, start, chunkSize] {
            long long local = 0;
            size_t end = std::min(start + chunkSize, values.size());
            for (size_t i = start; i < end; ++i) {
                local += values[i];
            }
            total.fetch_add(local, std::memory_order_relaxed);
        });
    }
    for (std::thread& worker : workers) {
        worker.join();
    }
    return total.load();
}

// worker_pool processes jobs with n workers, collecting results in order.
std::vector<int> worker_pool(const std::vector<int>& jobs, size_t workers,
                             const std::function<int(int)>& process) {
    std::vector<int> results(jobs.size());
    std::atomic<size_t> next{0};
    std::vector<std::thread> pool;
    for (size_t w = 0; w < workers; ++w) {
        pool.emplace_back([&] {
            while (true) {
                size_t i = next.fetch_add(1);
                if (i >= jobs.size()) {
                    break;
                }
                results[i] = process(jobs[i]);
            }
        });
    }
    for (std::thread& worker : pool) {
        worker.join();
    }
    return results;
}

// parallel_for runs fn(i) for every index across several threads.
void parallel_for(size_t count, size_t threads,
                  const std::function<void(size_t)>& fn) {
    if (count == 0) {
        return;
    }
    if (threads == 0) {
        threads = 1;
    }
    if (threads > count) {
        threads = count;
    }
    std::atomic<size_t> next{0};
    std::vector<std::thread> pool;
    for (size_t w = 0; w < threads; ++w) {
        pool.emplace_back([&] {
            while (true) {
                size_t i = next.fetch_add(1);
                if (i >= count) {
                    break;
                }
                fn(i);
            }
        });
    }
    for (std::thread& worker : pool) {
        worker.join();
    }
}

// initialize_once runs init exactly once even when called from many
// threads.
void initialize_once(const std::function<void()>& init) {
    static std::once_flag flag;
    std::call_once(flag, init);
}

// measure_time runs fn and returns the elapsed wall-clock milliseconds.
long long measure_time(const std::function<void()>& fn) {
    auto start = std::chrono::steady_clock::now();
    fn();
    auto end = std::chrono::steady_clock::now();
    return std::chrono::duration_cast<std::chrono::milliseconds>(end - start)
        .count();
}

// wait_until_ready polls a condition for up to timeout milliseconds.
bool wait_until_ready(const std::atomic<bool>& ready,
                      std::chrono::milliseconds timeout) {
    auto deadline = std::chrono::steady_clock::now() + timeout;
    while (!ready.load(std::memory_order_acquire)) {
        if (std::chrono::steady_clock::now() >= deadline) {
            return false;
        }
        std::this_thread::sleep_for(std::chrono::milliseconds(2));
    }
    return true;
}

// RateLimiter spaces out work calls by a minimum interval.
class RateLimiter {
public:
    explicit RateLimiter(std::chrono::milliseconds interval);
    void tick();

private:
    std::chrono::steady_clock::time_point last_;
    std::chrono::milliseconds interval_;
};

RateLimiter::RateLimiter(std::chrono::milliseconds interval)
    : last_(std::chrono::steady_clock::now()), interval_(interval) {}

void RateLimiter::tick() {
    auto now = std::chrono::steady_clock::now();
    auto elapsed = now - last_;
    if (elapsed < interval_) {
        std::this_thread::sleep_for(interval_ - elapsed);
    }
    last_ = std::chrono::steady_clock::now();
}
