// validation_utils.cpp — generated by scripts/generate/generate-cpp.mjs (do not edit by hand).
// Realistic C++ typing blocks for vibetyper: input validation helpers.

#include <cctype>
#include <regex>
#include <sstream>
#include <string>
#include <vector>

// is_valid_email reports whether s looks like a plausible email address.
bool is_valid_email(const std::string& s) {
    static const std::regex pattern(
        R"([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+.[a-zA-Z]{2,})");
    return std::regex_match(s, pattern);
}

// is_valid_url reports whether s is an absolute http(s) URL.
bool is_valid_url(const std::string& s) {
    static const std::regex pattern(R"(^https?://[^s/$.?#].[^s]*$)");
    return std::regex_match(s, pattern);
}

// is_valid_ipv4 reports whether s is a dotted-quad IPv4 address.
bool is_valid_ipv4(const std::string& s) {
    std::istringstream stream(s);
    int part;
    char dot;
    for (int i = 0; i < 4; ++i) {
        if (!(stream >> part) || part < 0 || part > 255) {
            return false;
        }
        if ((i < 3 && !(stream >> dot)) || (i < 3 && dot != '.')) {
            return false;
        }
    }
    return stream.eof();
}

// is_valid_port reports whether port is a valid TCP/UDP port number.
bool is_valid_port(int port) {
    return port >= 1 && port <= 65535;
}

// luhn_valid checks a card number against the Luhn checksum.
bool luhn_valid(const std::string& number) {
    int sum = 0;
    bool doubleDigit = false;
    for (int i = static_cast<int>(number.size()) - 1; i >= 0; --i) {
        int d = number[i] - '0';
        if (d < 0 || d > 9) {
            return false;
        }
        if (doubleDigit) {
            d *= 2;
            if (d > 9) {
                d -= 9;
            }
        }
        sum += d;
        doubleDigit = !doubleDigit;
    }
    return sum % 10 == 0;
}

// is_valid_hex_color reports whether s is a #RGB or #RRGGBB color.
bool is_valid_hex_color(const std::string& s) {
    static const std::regex pattern(R"(^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$)");
    return std::regex_match(s, pattern);
}

// is_valid_uuid reports whether s is a canonical hyphenated UUID.
bool is_valid_uuid(const std::string& s) {
    static const std::regex pattern(
        R"(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)");
    return std::regex_match(s, pattern);
}

// is_valid_semver reports whether s looks like a semantic version.
bool is_valid_semver(const std::string& s) {
    static const std::regex pattern(
        R"(^v?d+.d+.d+(-[0-9A-Za-z.-]+)?(+[0-9A-Za-z.-]+)?$)");
    return std::regex_match(s, pattern);
}

// has_lowercase reports whether s contains a lowercase letter.
bool has_lowercase(const std::string& s) {
    for (char c : s) {
        if (std::islower(static_cast<unsigned char>(c))) {
            return true;
        }
    }
    return false;
}

// has_uppercase reports whether s contains an uppercase letter.
bool has_uppercase(const std::string& s) {
    for (char c : s) {
        if (std::isupper(static_cast<unsigned char>(c))) {
            return true;
        }
    }
    return false;
}

// has_digit reports whether s contains a decimal digit.
bool has_digit(const std::string& s) {
    for (char c : s) {
        if (std::isdigit(static_cast<unsigned char>(c))) {
            return true;
        }
    }
    return false;
}

// has_symbol reports whether s contains a non-alphanumeric symbol.
bool has_symbol(const std::string& s) {
    for (char c : s) {
        if (!std::isalnum(static_cast<unsigned char>(c)) &&
            !std::isspace(static_cast<unsigned char>(c))) {
            return true;
        }
    }
    return false;
}

// is_strong_password requires at least 8 characters and three character
// classes.
bool is_strong_password(const std::string& s) {
    if (s.size() < 8) {
        return false;
    }
    int classes = 0;
    if (has_lowercase(s)) ++classes;
    if (has_uppercase(s)) ++classes;
    if (has_digit(s)) ++classes;
    if (has_symbol(s)) ++classes;
    return classes >= 3;
}

// is_balanced_brackets verifies that (), [] and {} pairs are nested
// correctly.
bool is_balanced_brackets(const std::string& text) {
    std::vector<char> stack;
    for (char c : text) {
        if (c == '(' || c == '[' || c == '{') {
            stack.push_back(c);
        } else if (c == ')' || c == ']' || c == '}') {
            if (stack.empty()) {
                return false;
            }
            char open = stack.back();
            if ((c == ')' && open != '(') ||
                (c == ']' && open != '[') ||
                (c == '}' && open != '{')) {
                return false;
            }
            stack.pop_back();
        }
    }
    return stack.empty();
}

// is_valid_isbn13 validates a 13-digit ISBN via its checksum digit.
bool is_valid_isbn13(const std::string& isbn) {
    std::vector<int> digits;
    for (char c : isbn) {
        if (c == '-') {
            continue;
        }
        if (c < '0' || c > '9') {
            return false;
        }
        digits.push_back(c - '0');
    }
    if (digits.size() != 13) {
        return false;
    }
    int sum = 0;
    for (size_t i = 0; i < digits.size(); ++i) {
        sum += (i % 2 == 0) ? digits[i] : digits[i] * 3;
    }
    return sum % 10 == 0;
}

// is_valid_slug reports whether s is a lowercase hyphen-separated slug.
bool is_valid_slug(const std::string& s) {
    static const std::regex pattern(R"(^[a-z0-9]+(?:-[a-z0-9]+)*$)");
    return std::regex_match(s, pattern);
}

// is_valid_hostname reports whether s is a well-formed DNS hostname.
bool is_valid_hostname(const std::string& s) {
    if (s.size() > 253) {
        return false;
    }
    static const std::regex pattern(
        R"(^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(.[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$)");
    return std::regex_match(s, pattern);
}

// is_valid_phone accepts common international phone formats.
bool is_valid_phone(const std::string& s) {
    static const std::regex pattern(R"(^+?[0-9][0-9s().-]{6,19}$)");
    return std::regex_match(s, pattern);
}

// is_all_digits reports whether every character of s is a digit.
bool is_all_digits(const std::string& s) {
    if (s.empty()) {
        return false;
    }
    for (char c : s) {
        if (!std::isdigit(static_cast<unsigned char>(c))) {
            return false;
        }
    }
    return true;
}

// is_valid_mac reports whether s is a colon-separated MAC address.
bool is_valid_mac(const std::string& s) {
    static const std::regex pattern(
        R"(^([0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}$)");
    return std::regex_match(s, pattern);
}

// is_valid_zip reports whether s is a US ZIP or ZIP+4 code.
bool is_valid_zip(const std::string& s) {
    static const std::regex pattern(R"(^d{5}(-d{4})?$)");
    return std::regex_match(s, pattern);
}
