// algorithms.go — generated by scripts/generate/generate-go.mjs (do not edit by hand).
// Realistic Go typing blocks for vibetyper: classic algorithms.
package main

// binarySearch returns the index of target in a sorted slice, or -1.
func binarySearch(sorted []int, target int) int {
	lo, hi := 0, len(sorted)-1
	for lo <= hi {
		mid := lo + (hi-lo)/2
		if sorted[mid] == target {
			return mid
		}
		if sorted[mid] < target {
			lo = mid + 1
		} else {
			hi = mid - 1
		}
	}
	return -1
}

// binarySearchFirst finds the first index of target in a sorted slice that
// may contain duplicates, or -1.
func binarySearchFirst(sorted []int, target int) int {
	lo, hi := 0, len(sorted)-1
	first := -1
	for lo <= hi {
		mid := lo + (hi-lo)/2
		if sorted[mid] < target {
			lo = mid + 1
		} else {
			if sorted[mid] == target {
				first = mid
			}
			hi = mid - 1
		}
	}
	return first
}

// binarySearchLast finds the last index of target in a sorted slice that
// may contain duplicates, or -1.
func binarySearchLast(sorted []int, target int) int {
	lo, hi := 0, len(sorted)-1
	last := -1
	for lo <= hi {
		mid := lo + (hi-lo)/2
		if sorted[mid] > target {
			hi = mid - 1
		} else {
			if sorted[mid] == target {
				last = mid
			}
			lo = mid + 1
		}
	}
	return last
}

// quickSort sorts a slice in place using Hoare-style partitioning.
func quickSort(items []int) {
	var sort func(lo, hi int)
	sort = func(lo, hi int) {
		if lo >= hi {
			return
		}
		pivot := items[lo+(hi-lo)/2]
		i, j := lo, hi
		for i <= j {
			for items[i] < pivot {
				i++
			}
			for items[j] > pivot {
				j--
			}
			if i <= j {
				items[i], items[j] = items[j], items[i]
				i++
				j--
			}
		}
		sort(lo, j)
		sort(i, hi)
	}
	sort(0, len(items)-1)
}

// mergeSort returns a sorted copy of values using top-down mergesort.
func mergeSort(values []int) []int {
	if len(values) <= 1 {
		return append([]int(nil), values...)
	}
	mid := len(values) / 2
	left := mergeSort(values[:mid])
	right := mergeSort(values[mid:])
	merged := make([]int, 0, len(values))
	i, j := 0, 0
	for i < len(left) && j < len(right) {
		if left[i] <= right[j] {
			merged = append(merged, left[i])
			i++
		} else {
			merged = append(merged, right[j])
			j++
		}
	}
	merged = append(merged, left[i:]...)
	merged = append(merged, right[j:]...)
	return merged
}

// insertionSort sorts a slice in place, efficient for nearly-sorted input.
func insertionSort(items []int) {
	for i := 1; i < len(items); i++ {
		key := items[i]
		j := i - 1
		for j >= 0 && items[j] > key {
			items[j+1] = items[j]
			j--
		}
		items[j+1] = key
	}
}

// selectionSort sorts a slice in place by repeatedly picking the minimum
// of the unsorted tail.
func selectionSort(items []int) {
	for i := 0; i < len(items)-1; i++ {
		minIdx := i
		for j := i + 1; j < len(items); j++ {
			if items[j] < items[minIdx] {
				minIdx = j
			}
		}
		items[i], items[minIdx] = items[minIdx], items[i]
	}
}

// twoSum finds the indices of two values that add up to target.
func twoSum(values []int, target int) [2]int {
	seen := make(map[int]int)
	for i, v := range values {
		if j, ok := seen[target-v]; ok {
			return [2]int{j, i}
		}
		seen[v] = i
	}
	return [2]int{-1, -1}
}

// maxSubarraySum returns the largest sum of any contiguous subarray using
// Kadane's algorithm.
func maxSubarraySum(values []int) int {
	if len(values) == 0 {
		return 0
	}
	best, current := values[0], values[0]
	for _, v := range values[1:] {
		if current < 0 {
			current = 0
		}
		current += v
		if current > best {
			best = current
		}
	}
	return best
}

// longestUniqueSubstring returns the length of the longest substring
// without repeating characters.
func longestUniqueSubstring(s string) int {
	lastSeen := make(map[rune]int)
	start, longest := 0, 0
	for i, r := range s {
		if j, ok := lastSeen[r]; ok && j >= start {
			start = j + 1
		}
		lastSeen[r] = i
		if i-start+1 > longest {
			longest = i - start + 1
		}
	}
	return longest
}

// knapsack returns the maximum value that fits in capacity using 0/1
// dynamic programming.
func knapsack(weights, values []int, capacity int) int {
	n := len(weights)
	dp := make([]int, capacity+1)
	for i := 0; i < n; i++ {
		for w := capacity; w >= weights[i]; w-- {
			if dp[w-weights[i]]+values[i] > dp[w] {
				dp[w] = dp[w-weights[i]] + values[i]
			}
		}
	}
	return dp[capacity]
}

// coinChange returns the minimum number of coins from denominations needed
// to make amount, or -1 when impossible.
func coinChange(denominations []int, amount int) int {
	inf := amount + 1
	dp := make([]int, amount+1)
	for i := 1; i <= amount; i++ {
		dp[i] = inf
	}
	for _, coin := range denominations {
		for a := coin; a <= amount; a++ {
			if dp[a-coin]+1 < dp[a] {
				dp[a] = dp[a-coin] + 1
			}
		}
	}
	if dp[amount] == inf {
		return -1
	}
	return dp[amount]
}

// longestCommonSubsequence returns the length of the longest common
// subsequence of two strings.
func longestCommonSubsequence(a, b string) int {
	ar, br := []rune(a), []rune(b)
	dp := make([][]int, len(ar)+1)
	for i := range dp {
		dp[i] = make([]int, len(br)+1)
	}
	for i := 1; i <= len(ar); i++ {
		for j := 1; j <= len(br); j++ {
			if ar[i-1] == br[j-1] {
				dp[i][j] = dp[i-1][j-1] + 1
			} else if dp[i-1][j] > dp[i][j-1] {
				dp[i][j] = dp[i-1][j]
			} else {
				dp[i][j] = dp[i][j-1]
			}
		}
	}
	return dp[len(ar)][len(br)]
}

// topologicalSort orders nodes so every edge points forward, using Kahn's
// algorithm. It returns ok=false when the graph has a cycle.
func topologicalSort(graph map[string][]string) ([]string, bool) {
	indegree := make(map[string]int)
	for node := range graph {
		indegree[node] = 0
	}
	for _, neighbors := range graph {
		for _, next := range neighbors {
			indegree[next]++
		}
	}
	queue := []string{}
	for node, degree := range indegree {
		if degree == 0 {
			queue = append(queue, node)
		}
	}
	var order []string
	for len(queue) > 0 {
		node := queue[0]
		queue = queue[1:]
		order = append(order, node)
		for _, next := range graph[node] {
			indegree[next]--
			if indegree[next] == 0 {
				queue = append(queue, next)
			}
		}
	}
	if len(order) != len(graph) {
		return nil, false
	}
	return order, true
}

// dijkstra returns the shortest distance from start to every reachable
// node in a weighted adjacency map.
func dijkstra(graph map[string]map[string]int, start string) map[string]int {
	dist := make(map[string]int)
	visited := make(map[string]bool)
	for node := range graph {
		dist[node] = 1 << 30
	}
	dist[start] = 0
	for {
		next := ""
		best := 1 << 30
		for node, d := range dist {
			if !visited[node] && d < best {
				best = d
				next = node
			}
		}
		if next == "" {
			break
		}
		visited[next] = true
		for neighbor, weight := range graph[next] {
			if d := dist[next] + weight; d < dist[neighbor] {
				dist[neighbor] = d
			}
		}
	}
	return dist
}

// majorityElement returns the value appearing more than n/2 times using
// the Boyer-Moore voting algorithm, or 0 if none exists.
func majorityElement(values []int) int {
	candidate, count := 0, 0
	for _, v := range values {
		if count == 0 {
			candidate = v
		}
		if v == candidate {
			count++
		} else {
			count--
		}
	}
	return candidate
}

// findMissingNumber finds the one missing integer in a permutation of
// 0..n using XOR cancellation.
func findMissingNumber(values []int) int {
	n := len(values)
	missing := 0
	for i := 0; i <= n; i++ {
		missing ^= i
	}
	for _, v := range values {
		missing ^= v
	}
	return missing
}

// dutchFlag sorts an array of 0s, 1s and 2s in a single pass using a
// three-way partition.
func dutchFlag(items []int) {
	lo, mid, hi := 0, 0, len(items)-1
	for mid <= hi {
		switch items[mid] {
		case 0:
			items[lo], items[mid] = items[mid], items[lo]
			lo++
			mid++
		case 1:
			mid++
		case 2:
			items[mid], items[hi] = items[hi], items[mid]
			hi--
		}
	}
}

// nextPermutation rearranges items into the next lexicographic
// permutation in place, returning false when already descending.
func nextPermutation(items []int) bool {
	i := len(items) - 2
	for i >= 0 && items[i] >= items[i+1] {
		i--
	}
	if i < 0 {
		return false
	}
	j := len(items) - 1
	for items[j] <= items[i] {
		j--
	}
	items[i], items[j] = items[j], items[i]
	lo, hi := i+1, len(items)-1
	for lo < hi {
		items[lo], items[hi] = items[hi], items[lo]
		lo++
		hi--
	}
	return true
}

// mergeSortedSlices merges two sorted slices into one sorted slice.
func mergeSortedSlices(a, b []int) []int {
	out := make([]int, 0, len(a)+len(b))
	i, j := 0, 0
	for i < len(a) && j < len(b) {
		if a[i] <= b[j] {
			out = append(out, a[i])
			i++
		} else {
			out = append(out, b[j])
			j++
		}
	}
	out = append(out, a[i:]...)
	out = append(out, b[j:]...)
	return out
}
