// collections_utils.go — generated by scripts/generate/generate-go.mjs (do not edit by hand).
// Realistic Go typing blocks for vibetyper: collections, containers and slice helpers.
package main

import (
	"container/list"
	"fmt"
	"math/rand"
	"sort"
)

// Stack is a LIFO container of integers backed by a slice.
type Stack struct {
	items []int
}

// Push adds a value to the top of the stack.
func (s *Stack) Push(v int) {
	s.items = append(s.items, v)
}

// Pop removes and returns the top value, reporting whether one existed.
func (s *Stack) Pop() (int, bool) {
	if len(s.items) == 0 {
		return 0, false
	}
	top := s.items[len(s.items)-1]
	s.items = s.items[:len(s.items)-1]
	return top, true
}

// Peek returns the top value without removing it.
func (s *Stack) Peek() (int, bool) {
	if len(s.items) == 0 {
		return 0, false
	}
	return s.items[len(s.items)-1], true
}

// String renders the stack contents for debugging.
func (s *Stack) String() string {
	return fmt.Sprintf("%v", s.items)
}

// StringQueue is a FIFO queue of strings backed by a slice.
type StringQueue struct {
	items []string
}

// Enqueue appends a value to the back of the queue.
func (q *StringQueue) Enqueue(v string) {
	q.items = append(q.items, v)
}

// Dequeue removes and returns the front value, reporting whether one existed.
func (q *StringQueue) Dequeue() (string, bool) {
	if len(q.items) == 0 {
		return "", false
	}
	front := q.items[0]
	q.items = q.items[1:]
	return front, true
}

// Len reports how many values are waiting in the queue.
func (q *StringQueue) Len() int {
	return len(q.items)
}

// StringSet is a set of unique strings backed by a map.
type StringSet struct {
	m map[string]struct{}
}

// NewStringSet builds a set seeded with the given items.
func NewStringSet(items ...string) *StringSet {
	s := &StringSet{m: make(map[string]struct{})}
	for _, item := range items {
		s.Add(item)
	}
	return s
}

// Add inserts an item into the set.
func (s *StringSet) Add(item string) {
	s.m[item] = struct{}{}
}

// Has reports whether the set contains item.
func (s *StringSet) Has(item string) bool {
	_, ok := s.m[item]
	return ok
}

// Items returns the set contents in sorted order.
func (s *StringSet) Items() []string {
	out := make([]string, 0, len(s.m))
	for item := range s.m {
		out = append(out, item)
	}
	sort.Strings(out)
	return out
}

// RingBuffer is a fixed-capacity circular buffer of integers.
type RingBuffer struct {
	data []int
	head int
	size int
}

// NewRingBuffer creates a ring buffer holding at most capacity values.
func NewRingBuffer(capacity int) *RingBuffer {
	return &RingBuffer{data: make([]int, capacity)}
}

// Write adds a value, overwriting the oldest value when full.
func (r *RingBuffer) Write(v int) {
	if len(r.data) == 0 {
		return
	}
	r.data[(r.head+r.size)%len(r.data)] = v
	if r.size < len(r.data) {
		r.size++
	} else {
		r.head = (r.head + 1) % len(r.data)
	}
}

// Read removes and returns the oldest value, reporting whether one existed.
func (r *RingBuffer) Read() (int, bool) {
	if r.size == 0 {
		return 0, false
	}
	v := r.data[r.head]
	r.head = (r.head + 1) % len(r.data)
	r.size--
	return v, true
}

// lruEntry pairs a cache key with its value inside the LRU list.
type lruEntry struct {
	key   string
	value string
}

// LRUCache is a fixed-capacity map with an eviction policy that drops the
// least recently used entry when the cache fills up.
type LRUCache struct {
	capacity int
	items    map[string]*list.Element
	order    *list.List
}

// NewLRUCache creates an LRU cache that holds at most capacity entries.
func NewLRUCache(capacity int) *LRUCache {
	return &LRUCache{
		capacity: capacity,
		items:    make(map[string]*list.Element),
		order:    list.New(),
	}
}

// Get returns the value for key, marking it as recently used.
func (c *LRUCache) Get(key string) (string, bool) {
	el, ok := c.items[key]
	if !ok {
		return "", false
	}
	c.order.MoveToFront(el)
	return el.Value.(*lruEntry).value, true
}

// Put inserts or updates key and evicts the least recently used entry when
// the cache is at capacity.
func (c *LRUCache) Put(key, value string) {
	if el, ok := c.items[key]; ok {
		el.Value.(*lruEntry).value = value
		c.order.MoveToFront(el)
		return
	}
	el := c.order.PushFront(&lruEntry{key: key, value: value})
	c.items[key] = el
	if c.order.Len() > c.capacity {
		oldest := c.order.Back()
		c.order.Remove(oldest)
		delete(c.items, oldest.Value.(*lruEntry).key)
	}
}

// frequencyMap counts how often each string appears in a slice.
func frequencyMap(items []string) map[string]int {
	counts := make(map[string]int)
	for _, item := range items {
		counts[item]++
	}
	return counts
}

// groupBy buckets items by the key returned by keyFor.
func groupBy(items []string, keyFor func(string) string) map[string][]string {
	groups := make(map[string][]string)
	for _, item := range items {
		key := keyFor(item)
		groups[key] = append(groups[key], item)
	}
	return groups
}

// chunk splits a slice into consecutive runs of at most size elements.
func chunk(items []int, size int) [][]int {
	if size <= 0 {
		return nil
	}
	var out [][]int
	for start := 0; start < len(items); start += size {
		end := start + size
		if end > len(items) {
			end = len(items)
		}
		out = append(out, items[start:end])
	}
	return out
}

// uniqueStrings removes duplicates while preserving first-seen order.
func uniqueStrings(items []string) []string {
	seen := make(map[string]bool)
	var out []string
	for _, item := range items {
		if !seen[item] {
			seen[item] = true
			out = append(out, item)
		}
	}
	return out
}

// flattenInts concatenates a slice of slices into one flat slice.
func flattenInts(rows [][]int) []int {
	var out []int
	for _, row := range rows {
		out = append(out, row...)
	}
	return out
}

// zipStrings pairs elements of a and b by index, stopping at the shorter
// slice.
func zipStrings(a, b []string) [][2]string {
	n := len(a)
	if len(b) < n {
		n = len(b)
	}
	pairs := make([][2]string, 0, n)
	for i := 0; i < n; i++ {
		pairs = append(pairs, [2]string{a[i], b[i]})
	}
	return pairs
}

// differenceStrings returns the elements of a that are not in b.
func differenceStrings(a, b []string) []string {
	inB := make(map[string]bool)
	for _, item := range b {
		inB[item] = true
	}
	var out []string
	for _, item := range a {
		if !inB[item] {
			out = append(out, item)
		}
	}
	return out
}

// intersectionStrings returns elements present in both slices, in the
// first-seen order of a.
func intersectionStrings(a, b []string) []string {
	inB := make(map[string]bool)
	for _, item := range b {
		inB[item] = true
	}
	seen := make(map[string]bool)
	var out []string
	for _, item := range a {
		if inB[item] && !seen[item] {
			seen[item] = true
			out = append(out, item)
		}
	}
	return out
}

// partitionInts splits values into those passing and failing pred.
func partitionInts(values []int, pred func(int) bool) (passing, failing []int) {
	for _, v := range values {
		if pred(v) {
			passing = append(passing, v)
		} else {
			failing = append(failing, v)
		}
	}
	return passing, failing
}

// rotateLeft shifts the elements of a slice left by k positions, wrapping
// around, and returns a new slice.
func rotateLeft(items []int, k int) []int {
	if len(items) == 0 {
		return items
	}
	k %= len(items)
	out := make([]int, 0, len(items))
	out = append(out, items[k:]...)
	out = append(out, items[:k]...)
	return out
}

// minValue returns the smallest value in a slice, or 0 when empty.
func minValue(values []int) int {
	if len(values) == 0 {
		return 0
	}
	best := values[0]
	for _, v := range values[1:] {
		if v < best {
			best = v
		}
	}
	return best
}

// maxValue returns the largest value in a slice, or 0 when empty.
func maxValue(values []int) int {
	if len(values) == 0 {
		return 0
	}
	best := values[0]
	for _, v := range values[1:] {
		if v > best {
			best = v
		}
	}
	return best
}

// indexOfString returns the first index of target in items, or -1.
func indexOfString(items []string, target string) int {
	for i, item := range items {
		if item == target {
			return i
		}
	}
	return -1
}

// shuffle returns a randomly permuted copy of items.
func shuffle(items []int) []int {
	out := append([]int(nil), items...)
	for i := len(out) - 1; i > 0; i-- {
		j := rand.Intn(i + 1)
		out[i], out[j] = out[j], out[i]
	}
	return out
}
