// concurrency_utils.go — generated by scripts/generate/generate-go.mjs (do not edit by hand).
// Realistic Go typing blocks for vibetyper: concurrency utilities.
package main

import (
	"context"
	"sync"
	"time"
)

// Counter is a goroutine-safe integer counter.
type Counter struct {
	mu    sync.Mutex
	value int
}

// Increment adds one to the counter.
func (c *Counter) Increment() {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.value++
}

// Value returns the current count.
func (c *Counter) Value() int {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.value
}

// workerPool processes jobs with n concurrent workers, returning results
// in completion order.
func workerPool(jobs []int, workers int, process func(int) int) []int {
	jobCh := make(chan int)
	resultCh := make(chan int, len(jobs))
	var wg sync.WaitGroup
	for i := 0; i < workers; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for job := range jobCh {
				resultCh <- process(job)
			}
		}()
	}
	go func() {
		defer close(jobCh)
		for _, job := range jobs {
			jobCh <- job
		}
	}()
	go func() {
		wg.Wait()
		close(resultCh)
	}()
	var results []int
	for result := range resultCh {
		results = append(results, result)
	}
	return results
}

// runParallel executes each function in its own goroutine and returns the
// results in input order.
func runParallel(fns ...func() int) []int {
	results := make([]int, len(fns))
	var wg sync.WaitGroup
	for i, fn := range fns {
		wg.Add(1)
		go func(idx int, f func() int) {
			defer wg.Done()
			results[idx] = f()
		}(i, fn)
	}
	wg.Wait()
	return results
}

// fanIn merges several channels into a single output channel.
func fanIn(channels ...<-chan int) <-chan int {
	out := make(chan int)
	var wg sync.WaitGroup
	for _, ch := range channels {
		wg.Add(1)
		go func(c <-chan int) {
			defer wg.Done()
			for v := range c {
				out <- v
			}
		}(ch)
	}
	go func() {
		wg.Wait()
		close(out)
	}()
	return out
}

// waitWithTimeout waits for the group with a deadline, reporting whether
// it finished in time.
func waitWithTimeout(wg *sync.WaitGroup, timeout time.Duration) bool {
	done := make(chan struct{})
	go func() {
		wg.Wait()
		close(done)
	}()
	select {
	case <-done:
		return true
	case <-time.After(timeout):
		return false
	}
}

// rateLimiter yields one token every interval, limiting how often the
// callback may run.
func rateLimiter(interval time.Duration, work func(int), total int) {
	ticker := time.NewTicker(interval)
	defer ticker.Stop()
	count := 0
	for range ticker.C {
		work(count)
		count++
		if count >= total {
			return
		}
	}
}

// SafeMap is a generic map protected by a read-write mutex.
type SafeMap[K comparable, V any] struct {
	mu sync.RWMutex
	m  map[K]V
}

// NewSafeMap creates an empty safe map.
func NewSafeMap[K comparable, V any]() *SafeMap[K, V] {
	return &SafeMap[K, V]{m: make(map[K]V)}
}

// Get returns the value stored for key.
func (s *SafeMap[K, V]) Get(key K) (V, bool) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	v, ok := s.m[key]
	return v, ok
}

// Set stores value under key.
func (s *SafeMap[K, V]) Set(key K, value V) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.m[key] = value
}

// runOnce wraps fn so it runs exactly once no matter how many goroutines
// call the result.
func runOnce(fn func()) func() {
	var once sync.Once
	return func() {
		once.Do(fn)
	}
}

// parallelSum adds a slice of integers across several goroutines.
func parallelSum(values []int, workers int) int {
	if len(values) == 0 {
		return 0
	}
	if workers < 1 {
		workers = 1
	}
	chunkSize := (len(values) + workers - 1) / workers
	sums := make(chan int, workers)
	var wg sync.WaitGroup
	for start := 0; start < len(values); start += chunkSize {
		end := start + chunkSize
		if end > len(values) {
			end = len(values)
		}
		wg.Add(1)
		go func(part []int) {
			defer wg.Done()
			total := 0
			for _, v := range part {
				total += v
			}
			sums <- total
		}(values[start:end])
	}
	go func() {
		wg.Wait()
		close(sums)
	}()
	total := 0
	for part := range sums {
		total += part
	}
	return total
}

// semaphore limits concurrent access to a resource using a buffered
// channel of tokens.
type semaphore struct {
	tokens chan struct{}
}

// newSemaphore creates a semaphore allowing at most n concurrent holders.
func newSemaphore(n int) *semaphore {
	return &semaphore{tokens: make(chan struct{}, n)}
}

// Acquire blocks until a token is available.
func (s *semaphore) Acquire() {
	s.tokens <- struct{}{}
}

// Release returns a token to the pool.
func (s *semaphore) Release() {
	<-s.tokens
}

// runWithTimeout runs fn and returns an error if it exceeds the timeout.
func runWithTimeout(timeout time.Duration, fn func() error) error {
	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()
	done := make(chan error, 1)
	go func() {
		done <- fn()
	}()
	select {
	case err := <-done:
		return err
	case <-ctx.Done():
		return ctx.Err()
	}
}

// pipeline connects a generator to a transformer through a channel and
// returns the collected output.
func pipeline(source []int, transform func(int) int) []int {
	in := make(chan int)
	out := make(chan int)
	go func() {
		defer close(in)
		for _, v := range source {
			in <- v
		}
	}()
	go func() {
		defer close(out)
		for v := range in {
			out <- transform(v)
		}
	}()
	var results []int
	for v := range out {
		results = append(results, v)
	}
	return results
}
