// data_structures.go — generated by scripts/generate/generate-go.mjs (do not edit by hand).
// Realistic Go typing blocks for vibetyper: classic data structures.
package main

// TreeNode is a node of a binary search tree holding an integer value.
type TreeNode struct {
	Value       int
	Left, Right *TreeNode
}

// Insert adds value into the tree rooted at n, keeping BST order.
func (n *TreeNode) Insert(value int) {
	if value < n.Value {
		if n.Left == nil {
			n.Left = &TreeNode{Value: value}
		} else {
			n.Left.Insert(value)
		}
		return
	}
	if n.Right == nil {
		n.Right = &TreeNode{Value: value}
	} else {
		n.Right.Insert(value)
	}
}

// Contains reports whether value exists in the tree.
func (n *TreeNode) Contains(value int) bool {
	if n == nil {
		return false
	}
	switch {
	case value < n.Value:
		return n.Left.Contains(value)
	case value > n.Value:
		return n.Right.Contains(value)
	default:
		return true
	}
}

// InOrder returns the values in sorted order via an in-order traversal.
func (n *TreeNode) InOrder() []int {
	if n == nil {
		return nil
	}
	out := n.Left.InOrder()
	out = append(out, n.Value)
	out = append(out, n.Right.InOrder()...)
	return out
}

// Height returns the number of levels in the tree.
func (n *TreeNode) Height() int {
	if n == nil {
		return 0
	}
	left, right := n.Left.Height(), n.Right.Height()
	if left > right {
		return left + 1
	}
	return right + 1
}

// MinHeap is a binary min-heap backed by a slice.
type MinHeap struct {
	items []int
}

// Push adds a value to the heap.
func (h *MinHeap) Push(v int) {
	h.items = append(h.items, v)
	for i := len(h.items) - 1; i > 0; {
		parent := (i - 1) / 2
		if h.items[parent] <= h.items[i] {
			break
		}
		h.items[parent], h.items[i] = h.items[i], h.items[parent]
		i = parent
	}
}

// Pop removes and returns the smallest value.
func (h *MinHeap) Pop() (int, bool) {
	if len(h.items) == 0 {
		return 0, false
	}
	top := h.items[0]
	last := len(h.items) - 1
	h.items[0] = h.items[last]
	h.items = h.items[:last]
	for i := 0; ; {
		left, right := 2*i+1, 2*i+2
		smallest := i
		if left < len(h.items) && h.items[left] < h.items[smallest] {
			smallest = left
		}
		if right < len(h.items) && h.items[right] < h.items[smallest] {
			smallest = right
		}
		if smallest == i {
			break
		}
		h.items[i], h.items[smallest] = h.items[smallest], h.items[i]
		i = smallest
	}
	return top, true
}

// Graph is a directed adjacency-map graph keyed by node name.
type Graph struct {
	adj map[string][]string
}

// NewGraph creates an empty graph.
func NewGraph() *Graph {
	return &Graph{adj: make(map[string][]string)}
}

// AddEdge records a directed edge from from to to.
func (g *Graph) AddEdge(from, to string) {
	g.adj[from] = append(g.adj[from], to)
}

// Neighbors lists the nodes reachable in one hop from node.
func (g *Graph) Neighbors(node string) []string {
	return append([]string(nil), g.adj[node]...)
}

// BFS visits every node reachable from start in breadth-first order.
func (g *Graph) BFS(start string) []string {
	visited := make(map[string]bool)
	var order []string
	queue := []string{start}
	visited[start] = true
	for len(queue) > 0 {
		node := queue[0]
		queue = queue[1:]
		order = append(order, node)
		for _, next := range g.adj[node] {
			if !visited[next] {
				visited[next] = true
				queue = append(queue, next)
			}
		}
	}
	return order
}

// FenwickTree is a binary indexed tree for prefix sums over an implicit
// array.
type FenwickTree struct {
	tree []int
}

// NewFenwickTree creates a fenwick tree sized for n elements.
func NewFenwickTree(n int) *FenwickTree {
	return &FenwickTree{tree: make([]int, n+1)}
}

// Add adds delta to the element at 1-based index.
func (f *FenwickTree) Add(index, delta int) {
	for i := index; i < len(f.tree); i += i & -i {
		f.tree[i] += delta
	}
}

// PrefixSum returns the sum of elements 1..index.
func (f *FenwickTree) PrefixSum(index int) int {
	sum := 0
	for i := index; i > 0; i -= i & -i {
		sum += f.tree[i]
	}
	return sum
}

// hash1 is a simple FNV-1a-style hash used by the bloom filter.
func hash1(s string) int {
	h := 2166136261
	for _, b := range []byte(s) {
		h ^= int(b)
		h *= 16777619
	}
	if h < 0 {
		h = -h
	}
	return h
}

// hash2 is a djb2-style hash, distinct from hash1.
func hash2(s string) int {
	h := 5381
	for _, b := range []byte(s) {
		h = h*33 + int(b)
	}
	if h < 0 {
		h = -h
	}
	return h
}

// BloomFilter is a probabilistic set that never produces false negatives.
type BloomFilter struct {
	bits []bool
	size int
}

// NewBloomFilter creates a bloom filter with the given number of bits.
func NewBloomFilter(size int) *BloomFilter {
	return &BloomFilter{bits: make([]bool, size), size: size}
}

// Add marks an item as present.
func (b *BloomFilter) Add(item string) {
	b.bits[hash1(item)%b.size] = true
	b.bits[hash2(item)%b.size] = true
}

// MaybeContains reports whether the item may be present; a false positive
// is possible but a false negative is not.
func (b *BloomFilter) MaybeContains(item string) bool {
	return b.bits[hash1(item)%b.size] && b.bits[hash2(item)%b.size]
}

// TrieNode is one node of a rune-based prefix tree.
type TrieNode struct {
	children map[rune]*TrieNode
	terminal bool
}

// NewTrieNode creates an empty trie node.
func NewTrieNode() *TrieNode {
	return &TrieNode{children: make(map[rune]*TrieNode)}
}

// Insert adds a word to the trie.
func (n *TrieNode) Insert(word string) {
	node := n
	for _, r := range word {
		child, ok := node.children[r]
		if !ok {
			child = NewTrieNode()
			node.children[r] = child
		}
		node = child
	}
	node.terminal = true
}

// Search reports whether word is a complete word in the trie.
func (n *TrieNode) Search(word string) bool {
	node := n
	for _, r := range word {
		child, ok := node.children[r]
		if !ok {
			return false
		}
		node = child
	}
	return node.terminal
}

// StartsWith reports whether any stored word begins with prefix.
func (n *TrieNode) StartsWith(prefix string) bool {
	node := n
	for _, r := range prefix {
		child, ok := node.children[r]
		if !ok {
			return false
		}
		node = child
	}
	return true
}
