// domain_models.go — generated by scripts/generate/generate-go.mjs (do not edit by hand).
// Realistic Go typing blocks for vibetyper: domain models and their methods.
package main

import (
	"errors"
	"fmt"
	"strings"
	"time"
)

// User is a registered account in the system.
type User struct {
	ID        int
	Name      string
	Email     string
	CreatedAt time.Time
}

// DisplayName returns the name, falling back to the email prefix.
func (u User) DisplayName() string {
	if strings.TrimSpace(u.Name) != "" {
		return u.Name
	}
	at := strings.Index(u.Email, "@")
	if at > 0 {
		return u.Email[:at]
	}
	return "anonymous"
}

// Product is an item available for sale.
type Product struct {
	SKU        string
	Name       string
	PriceCents int64
	Stock      int
}

// TotalValue is the retail value of the current stock on hand.
func (p Product) TotalValue() int64 {
	return p.PriceCents * int64(p.Stock)
}

// Restock adds n units to the available stock.
func (p *Product) Restock(n int) {
	p.Stock += n
}

// OrderItem is one line of an order.
type OrderItem struct {
	SKU   string
	Qty   int
	Price int64
}

// Order is a customer's purchase, tracked through a lifecycle of statuses.
type Order struct {
	ID     string
	Items  []OrderItem
	Status string
}

// AddItem appends a line item to the order.
func (o *Order) AddItem(item OrderItem) {
	o.Items = append(o.Items, item)
}

// Subtotal sums the cost of every line item.
func (o Order) Subtotal() int64 {
	var total int64
	for _, item := range o.Items {
		total += item.Price * int64(item.Qty)
	}
	return total
}

// BankAccount tracks a balance in cents for one owner.
type BankAccount struct {
	Owner        string
	BalanceCents int64
}

// Deposit credits the account, rejecting negative amounts.
func (a *BankAccount) Deposit(amount int64) error {
	if amount <= 0 {
		return errors.New("deposit must be positive")
	}
	a.BalanceCents += amount
	return nil
}

// Withdraw debits the account, guarding against overdraft.
func (a *BankAccount) Withdraw(amount int64) error {
	if amount <= 0 {
		return errors.New("withdrawal must be positive")
	}
	if amount > a.BalanceCents {
		return errors.New("insufficient funds")
	}
	a.BalanceCents -= amount
	return nil
}

// Book is a published work in the library catalog.
type Book struct {
	Title  string
	Author string
	Pages  int
	ISBN   string
}

// Citation renders the book in a simple author-title format.
func (b Book) Citation() string {
	return fmt.Sprintf("%s. %s.", b.Author, b.Title)
}

// Vehicle records the basic facts of a car in a fleet.
type Vehicle struct {
	Make    string
	Model   string
	Year    int
	Mileage int
}

// Age computes how old the vehicle is relative to currentYear.
func (v Vehicle) Age(currentYear int) int {
	if currentYear < v.Year {
		return 0
	}
	return currentYear - v.Year
}

// Drive adds miles to the odometer.
func (v *Vehicle) Drive(miles int) {
	if miles > 0 {
		v.Mileage += miles
	}
}

// Employee is a member of staff with a salary in dollars per year.
type Employee struct {
	ID         int
	Name       string
	Department string
	Salary     int
}

// AnnualBonus computes a bonus as a percentage of salary.
func (e Employee) AnnualBonus(percent float64) int {
	return int(float64(e.Salary) * percent / 100)
}

// Student holds the course grades of one learner.
type Student struct {
	Name   string
	Grades []float64
}

// AddGrade appends a grade in the 0..100 range.
func (s *Student) AddGrade(grade float64) {
	if grade >= 0 && grade <= 100 {
		s.Grades = append(s.Grades, grade)
	}
}

// Average returns the mean of the recorded grades.
func (s Student) Average() float64 {
	if len(s.Grades) == 0 {
		return 0
	}
	sum := 0.0
	for _, g := range s.Grades {
		sum += g
	}
	return sum / float64(len(s.Grades))
}
