// domain_models_2.go — generated by scripts/generate/generate-go.mjs (do not edit by hand).
// Realistic Go typing blocks for vibetyper: domain models and their methods.
package main

import (
	"fmt"
	"strings"
	"time"
)

// Song is a track in the music library.
type Song struct {
	Title       string
	Artist      string
	DurationSec int
	PlayCount   int
}

// Minutes renders the duration as "m:ss".
func (s Song) Minutes() string {
	return fmt.Sprintf("%d:%02d", s.DurationSec/60, s.DurationSec%60)
}

// BumpPlayCount records one more play.
func (s *Song) BumpPlayCount() {
	s.PlayCount++
}

// Task is a unit of work on a project board.
type Task struct {
	ID    int
	Title string
	Done  bool
	Due   time.Time
}

// Complete marks the task as finished.
func (t *Task) Complete() {
	t.Done = true
}

// Overdue reports whether the task is unfinished and past its due date.
func (t Task) Overdue(now time.Time) bool {
	return !t.Done && now.After(t.Due)
}

// SensorReading is one sample from an environmental sensor.
type SensorReading struct {
	DeviceID    string
	Temperature float64
	Humidity    float64
	TakenAt     time.Time
}

// HeatIndex approximates the perceived temperature from humidity.
func (r SensorReading) HeatIndex() float64 {
	t := r.Temperature
	h := r.Humidity
	return -42.379 + 2.04901523*t + 10.14333127*h -
		0.22475541*t*h - 0.00683783*t*t -
		0.05481717*h*h + 0.00122874*t*t*h +
		0.00085282*t*h*h - 0.00000199*t*t*h*h
}

// CartItem is one product line in a shopping cart.
type CartItem struct {
	ProductSKU     string
	Quantity       int
	UnitPriceCents int64
}

// LineTotal is the price of the whole line.
func (i CartItem) LineTotal() int64 {
	return i.UnitPriceCents * int64(i.Quantity)
}

// Session is a logged-in browser session with an expiry.
type Session struct {
	Token     string
	UserID    int
	ExpiresAt time.Time
}

// IsExpired reports whether the session has passed its expiry.
func (s Session) IsExpired(now time.Time) bool {
	return now.After(s.ExpiresAt)
}

// Remaining returns how long the session still has to live.
func (s Session) Remaining(now time.Time) time.Duration {
	return s.ExpiresAt.Sub(now)
}

// Notification is a user-facing alert.
type Notification struct {
	ID      string
	Kind    string
	Message string
	Read    bool
}

// MarkRead flags the notification as seen.
func (n *Notification) MarkRead() {
	n.Read = true
}

// Address is a postal address for shipping or billing.
type Address struct {
	Street string
	City   string
	State  string
	ZIP    string
}

// String renders the address on a single line.
func (a Address) String() string {
	return strings.Join([]string{a.Street, a.City, a.State, a.ZIP}, ", ")
}

// Recipe is a set of ingredients and a procedure.
type Recipe struct {
	Name        string
	Servings    int
	Ingredients []string
}

// IngredientCount reports how many ingredients the recipe lists.
func (r Recipe) IngredientCount() int {
	return len(r.Ingredients)
}

// ScaleServings returns a copy adjusted to feed n people.
func (r Recipe) ScaleServings(n int) Recipe {
	if n <= 0 {
		return r
	}
	factor := float64(n) / float64(r.Servings)
	scaled := r
	scaled.Servings = n
	scaled.Ingredients = make([]string, len(r.Ingredients))
	for i, ing := range r.Ingredients {
		scaled.Ingredients[i] = fmt.Sprintf("%s (x%.1f)", ing, factor)
	}
	return scaled
}

// Payment is a single charge against an order.
type Payment struct {
	ID          string
	OrderID     string
	AmountCents int64
	Method      string
}

// Refundable reports whether the payment can still be reversed.
func (p Payment) Refundable() bool {
	return p.AmountCents > 0
}

// Event is a timestamped fact emitted by an application.
type Event struct {
	Type      string
	Payload   map[string]any
	CreatedAt time.Time
}

// Key returns a stable deduplication key for the event.
func (e Event) Key() string {
	return e.Type + "@" + e.CreatedAt.Format(time.RFC3339Nano)
}

// Message is a chat message between two users.
type Message struct {
	ID         string
	FromID     int
	ToID       int
	ReplyToID  string
	Body       string
	SentAt     time.Time
}

// IsReply reports whether the message answers an earlier message.
func (m Message) IsReply() bool {
	return m.ReplyToID != ""
}
