// encoding_utils.go — generated by scripts/generate/generate-go.mjs (do not edit by hand).
// Realistic Go typing blocks for vibetyper: encoding and decoding helpers.
package main

import (
	"bytes"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"strconv"
	"strings"
	"unicode/utf8"
)

// base64Encode encodes bytes as a standard base64 string.
func base64Encode(data []byte) string {
	return base64.StdEncoding.EncodeToString(data)
}

// base64Decode decodes a standard base64 string back into bytes.
func base64Decode(encoded string) ([]byte, error) {
	return base64.StdEncoding.DecodeString(encoded)
}

// hexEncode renders bytes as lowercase hexadecimal text.
func hexEncode(data []byte) string {
	return hex.EncodeToString(data)
}

// hexDecode parses a hexadecimal string into bytes.
func hexDecode(text string) ([]byte, error) {
	return hex.DecodeString(text)
}

// rot13Text applies ROT13, the classic letter-substitution cipher, to a
// string.
func rot13Text(text string) string {
	var b strings.Builder
	for _, r := range text {
		switch {
		case r >= 'a' && r <= 'z':
			b.WriteRune('a' + (r-'a'+13)%26)
		case r >= 'A' && r <= 'Z':
			b.WriteRune('A' + (r-'A'+13)%26)
		default:
			b.WriteRune(r)
		}
	}
	return b.String()
}

// urlSafeBase64 encodes bytes with the URL-safe alphabet, omitting
// padding.
func urlSafeBase64(data []byte) string {
	return base64.RawURLEncoding.EncodeToString(data)
}

// jsonValid reports whether text is well-formed JSON.
func jsonValid(text string) bool {
	return json.Valid([]byte(text))
}

// jsonCompact strips insignificant whitespace from a JSON document.
func jsonCompact(text string) (string, error) {
	var buf bytes.Buffer
	if err := json.Compact(&buf, []byte(text)); err != nil {
		return "", fmt.Errorf("compact json: %w", err)
	}
	return buf.String(), nil
}

// runeCount returns the number of runes in a string.
func runeCount(text string) int {
	return utf8.RuneCountInString(text)
}

// xorBytes applies a repeating key to data, returning the result.
func xorBytes(data, key []byte) []byte {
	out := make([]byte, len(data))
	if len(key) == 0 {
		copy(out, data)
		return out
	}
	for i, b := range data {
		out[i] = b ^ key[i%len(key)]
	}
	return out
}

// reverseBytes returns a copy of data with the byte order flipped.
func reverseBytes(data []byte) []byte {
	out := make([]byte, len(data))
	for i, b := range data {
		out[len(data)-1-i] = b
	}
	return out
}

// toBinaryString renders an integer as a binary string without a sign.
func toBinaryString(n int) string {
	if n < 0 {
		n = -n
	}
	return strconv.FormatInt(int64(n), 2)
}

// parseHex interprets text as a base-16 integer.
func parseHex(text string) (int, error) {
	v, err := strconv.ParseUint(text, 16, 64)
	return int(v), err
}

// quoteText wraps text in double quotes with escapes, safe to embed in
// Go source or JSON.
func quoteText(text string) string {
	return strconv.Quote(text)
}

// unquoteText removes quotes and decodes escapes from a quoted string.
func unquoteText(text string) (string, error) {
	return strconv.Unquote(text)
}

// hammingDistance counts the positions where two equal-length byte
// slices differ.
func hammingDistance(a, b []byte) (int, error) {
	if len(a) != len(b) {
		return 0, errors.New("lengths differ")
	}
	distance := 0
	for i := range a {
		if a[i] != b[i] {
			distance++
		}
	}
	return distance, nil
}

// runLengthEncode compresses repeated runs of a character, so "aaabbc"
// becomes "a3b2c1".
func runLengthEncode(text string) string {
	if text == "" {
		return ""
	}
	var b strings.Builder
	run := rune(0)
	count := 0
	for _, r := range text {
		if r != run && count > 0 {
			b.WriteRune(run)
			b.WriteString(strconv.Itoa(count))
			count = 0
		}
		run = r
		count++
	}
	b.WriteRune(run)
	b.WriteString(strconv.Itoa(count))
	return b.String()
}

// runLengthDecode reverses runLengthEncode, expanding "a3b2c1" back to
// "aaabbc".
func runLengthDecode(encoded string) string {
	var b strings.Builder
	i := 0
	for i < len(encoded) {
		r := rune(encoded[i])
		i++
		start := i
		for i < len(encoded) && encoded[i] >= '0' && encoded[i] <= '9' {
			i++
		}
		if start == i {
			b.WriteRune(r)
			continue
		}
		count, _ := strconv.Atoi(encoded[start:i])
		for j := 0; j < count; j++ {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// soundex computes the four-character Soundex code of a name, encoding
// similar-sounding names identically.
func soundex(name string) string {
	upper := strings.ToUpper(name)
	if upper == "" {
		return ""
	}
	code := string(upper[0])
	last := soundexCode(upper[0])
	for i := 1; i < len(upper) && len(code) < 4; i++ {
		c := soundexCode(upper[i])
		if c != 0 && c != last {
			code += strconv.Itoa(c)
		}
		if c != 0 {
			last = c
		}
	}
	return (code + "000")[:4]
}

// soundexCode maps an uppercase letter to its Soundex digit, or 0 for
// vowels and H/W.
func soundexCode(r byte) int {
	switch r {
	case 'B', 'F', 'P', 'V':
		return 1
	case 'C', 'G', 'J', 'K', 'Q', 'S', 'X', 'Z':
		return 2
	case 'D', 'T':
		return 3
	case 'L':
		return 4
	case 'M', 'N':
		return 5
	case 'R':
		return 6
	default:
		return 0
	}
}
