// extra_utils.go — generated by scripts/generate/generate-go.mjs (do not edit by hand).
// Realistic Go typing blocks for vibetyper: miscellaneous utilities.
package main

import (
	"fmt"
	"math"
	"math/rand"
	"sort"
	"strconv"
	"strings"
	"time"
)

// isLeapYear reports whether the given year has a February 29th.
func isLeapYear(year int) bool {
	return year%4 == 0 && (year%100 != 0 || year%400 == 0)
}

// daysInMonth returns the number of days in a month (1-12) of a year.
func daysInMonth(year, month int) int {
	switch month {
	case 2:
		if isLeapYear(year) {
			return 29
		}
		return 28
	case 4, 6, 9, 11:
		return 30
	default:
		return 31
	}
}

// popcount counts the set bits in an unsigned integer.
func popcount(n uint) int {
	count := 0
	for n > 0 {
		n &= n - 1
		count++
	}
	return count
}

// isPowerOfTwo reports whether n is a positive power of two.
func isPowerOfTwo(n int) bool {
	return n > 0 && n&(n-1) == 0
}

// signum returns -1, 0 or 1 according to the sign of n.
func signum(n int) int {
	switch {
	case n < 0:
		return -1
	case n > 0:
		return 1
	default:
		return 0
	}
}

// gcdArray returns the greatest common divisor of every value in a
// slice.
func gcdArray(values []int) int {
	if len(values) == 0 {
		return 0
	}
	result := values[0]
	for _, v := range values[1:] {
		result = gcd(result, v)
	}
	return result
}

// celsiusToFahrenheit converts a temperature from Celsius to Fahrenheit.
func celsiusToFahrenheit(c float64) float64 {
	return c*9/5 + 32
}

// fahrenheitToCelsius converts a temperature from Fahrenheit to Celsius.
func fahrenheitToCelsius(f float64) float64 {
	return (f - 32) * 5 / 9
}

// kilometersToMiles converts a distance from kilometers to miles.
func kilometersToMiles(km float64) float64 {
	return km * 0.621371
}

// milesToKilometers converts a distance from miles to kilometers.
func milesToKilometers(mi float64) float64 {
	return mi / 0.621371
}

// paginate returns the slice of items for one page given a size and
// offset.
func paginate(items []string, offset, limit int) []string {
	if offset < 0 {
		offset = 0
	}
	if limit < 0 {
		limit = 0
	}
	if offset >= len(items) {
		return nil
	}
	end := offset + limit
	if limit == 0 || end > len(items) {
		end = len(items)
	}
	return items[offset:end]
}

// dedupeInts removes duplicate integers, preserving first-seen order.
func dedupeInts(values []int) []int {
	seen := make(map[int]bool)
	var out []int
	for _, v := range values {
		if !seen[v] {
			seen[v] = true
			out = append(out, v)
		}
	}
	return out
}

// sortDescending sorts a slice of integers in descending order in place.
func sortDescending(values []int) {
	sort.Slice(values, func(i, j int) bool {
		return values[i] > values[j]
	})
}

// containsInt reports whether target appears in values.
func containsInt(values []int, target int) bool {
	for _, v := range values {
		if v == target {
			return true
		}
	}
	return false
}

// trimFloatZeros formats a float with up to maxDecimals decimals,
// removing trailing zeros, e.g. 3.50 -> "3.5".
func trimFloatZeros(value float64, maxDecimals int) string {
	s := strconv.FormatFloat(value, 'f', maxDecimals, 64)
	s = strings.TrimRight(s, "0")
	return strings.TrimRight(s, ".")
}

// timeUntil returns how long remains until a future time.
func timeUntil(t time.Time) time.Duration {
	return time.Until(t)
}

// parseBoolStrict interprets common yes/no spellings as a boolean.
func parseBoolStrict(text string) (bool, bool) {
	switch strings.ToLower(strings.TrimSpace(text)) {
	case "true", "yes", "y", "1", "on":
		return true, true
	case "false", "no", "n", "0", "off":
		return false, true
	default:
		return false, false
	}
}

// randomChoice picks a random element of items.
func randomChoice(items []string) string {
	if len(items) == 0 {
		return ""
	}
	return items[rand.Intn(len(items))]
}

// secondsToClock renders a count of seconds as HH:MM:SS.
func secondsToClock(total int) string {
	h := total / 3600
	m := (total % 3600) / 60
	s := total % 60
	return fmt.Sprintf("%02d:%02d:%02d", h, m, s)
}

// isSortedAsc reports whether values are in non-decreasing order.
func isSortedAsc(values []int) bool {
	for i := 1; i < len(values); i++ {
		if values[i] < values[i-1] {
			return false
		}
	}
	return true
}

// intPow raises base to the power exp using exponentiation by squaring.
func intPow(base, exp int) int {
	result := 1
	for exp > 0 {
		if exp%2 == 1 {
			result *= base
		}
		base *= base
		exp /= 2
	}
	return result
}

// clampFloat restricts value to the inclusive range [lo, hi].
func clampFloat(value, lo, hi float64) float64 {
	if value < lo {
		return lo
	}
	if value > hi {
		return hi
	}
	return value
}

// roundToInt rounds a float to the nearest integer, half away from zero.
func roundToInt(value float64) int {
	return int(math.Floor(value + 0.5))
}
