// formatting_utils.go — generated by scripts/generate/generate-go.mjs (do not edit by hand).
// Realistic Go typing blocks for vibetyper: number, size and text formatting.
package main

import (
	"fmt"
	"strconv"
	"strings"
	"time"
	"unicode"
	"unicode/utf8"
)

// commaSeparate inserts thousands separators into an integer string.
func commaSeparate(n int) string {
	negative := n < 0
	digits := strconv.Itoa(absInt(n))
	var b strings.Builder
	for i, d := range digits {
		if i > 0 && (len(digits)-i)%3 == 0 {
			b.WriteByte(',')
		}
		b.WriteRune(d)
	}
	out := b.String()
	if negative {
		return "-" + out
	}
	return out
}

// absInt returns the absolute value of n.
func absInt(n int) int {
	if n < 0 {
		return -n
	}
	return n
}

// percentString renders a fraction as a percentage with the given number
// of decimals.
func percentString(value float64, decimals int) string {
	return strconv.FormatFloat(value*100, 'f', decimals, 64) + "%"
}

// humanBytes renders a byte count as a compact human-readable size.
func humanBytes(n int64) string {
	const unit = 1024
	if n < unit {
		return fmt.Sprintf("%d B", n)
	}
	div, exp := int64(unit), 0
	for m := n / unit; m >= unit; m /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.1f %ciB", float64(n)/float64(div), "KMGTPE"[exp])
}

// humanDuration renders a duration in seconds as "2h 5m" style text.
func humanDuration(seconds int64) string {
	if seconds < 60 {
		return fmt.Sprintf("%ds", seconds)
	}
	minutes := seconds / 60
	if minutes < 60 {
		return fmt.Sprintf("%dm %ds", minutes, seconds%60)
	}
	hours := minutes / 60
	if hours < 24 {
		return fmt.Sprintf("%dh %dm", hours, minutes%60)
	}
	days := hours / 24
	return fmt.Sprintf("%dd %dh", days, hours%24)
}

// padNumber zero-pads an integer to at least width digits.
func padNumber(n, width int) string {
	return fmt.Sprintf("%0*d", width, n)
}

// pluralize appends an "s" unless count is exactly one.
func pluralize(count int, singular string) string {
	if count == 1 {
		return singular
	}
	return singular + "s"
}

// ordinalSuffix returns the ordinal form of a number, e.g. 3 -> "3rd".
func ordinalSuffix(n int) string {
	suffix := "th"
	switch n % 100 {
	case 11, 12, 13:
	case 1:
		suffix = "st"
	case 2:
		suffix = "nd"
	case 3:
		suffix = "rd"
	}
	return strconv.Itoa(n) + suffix
}

// joinWithAnd renders a list in prose form: "a, b and c".
func joinWithAnd(items []string) string {
	switch len(items) {
	case 0:
		return ""
	case 1:
		return items[0]
	case 2:
		return items[0] + " and " + items[1]
	}
	return strings.Join(items[:len(items)-1], ", ") + " and " + items[len(items)-1]
}

// formatMoney renders a dollar amount given in cents with two decimals
// and thousands separators.
func formatMoney(cents int64) string {
	negative := cents < 0
	abs := cents
	if negative {
		abs = -cents
	}
	dollars := commaSeparate(int(abs / 100))
	remainder := abs % 100
	out := fmt.Sprintf("%s.%02d", dollars, remainder)
	if negative {
		out = "-" + out
	}
	return out
}

// truncateMiddle keeps the start and end of a long string, e.g. for file
// paths in a constrained UI.
func truncateMiddle(text string, max int) string {
	runes := []rune(text)
	if len(runes) <= max {
		return text
	}
	keep := (max - 3) / 2
	return string(runes[:keep]) + "..." + string(runes[len(runes)-keep:])
}

// durationBetween returns the elapsed time between two Unix timestamps
// as a human-readable span.
func durationBetween(start, end int64) string {
	if end < start {
		end, start = start, end
	}
	return humanDuration(end - start)
}

// formatRatio renders a ratio in reduced form, e.g. 8:4 -> "2:1".
func formatRatio(a, b int) string {
	g := gcd(a, b)
	if g == 0 {
		return "0:0"
	}
	return strconv.Itoa(a/g) + ":" + strconv.Itoa(b/g)
}

// tableRow pads cells to the given widths, separating them with two
// spaces.
func tableRow(cells []string, widths []int) string {
	var b strings.Builder
	for i, cell := range cells {
		if i > 0 {
			b.WriteString("  ")
		}
		if i < len(widths) {
			b.WriteString(padRight(cell, widths[i], ' '))
		} else {
			b.WriteString(cell)
		}
	}
	return b.String()
}

// timeAgo renders a timestamp relative to now, e.g. "5m ago".
func timeAgo(t time.Time) string {
	elapsed := time.Since(t)
	switch {
	case elapsed < time.Minute:
		return "just now"
	case elapsed < time.Hour:
		return fmt.Sprintf("%dm ago", int(elapsed.Minutes()))
	case elapsed < 24*time.Hour:
		return fmt.Sprintf("%dh ago", int(elapsed.Hours()))
	default:
		return fmt.Sprintf("%dd ago", int(elapsed.Hours()/24))
	}
}

// signedFloat formats a float with an explicit sign and fixed decimals.
func signedFloat(value float64, decimals int) string {
	return strconv.FormatFloat(value, '+', decimals, 64)
}

// upperFirst capitalizes the first rune of a string.
func upperFirst(text string) string {
	if text == "" {
		return ""
	}
	r, size := utf8.DecodeRuneInString(text)
	return string(unicode.ToUpper(r)) + text[size:]
}

// bytesPerSecond renders a transfer rate, e.g. "12.4 MiB/s".
func bytesPerSecond(n int64, elapsed time.Duration) string {
	if elapsed <= 0 {
		return "0 B/s"
	}
	perSecond := float64(n) / elapsed.Seconds()
	return humanBytes(int64(perSecond)) + "/s"
}

// intList renders integers as a compact comma-separated list.
func intList(values []int) string {
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = strconv.Itoa(v)
	}
	return strings.Join(parts, ", ")
}
