// geometry_math.go — generated by scripts/generate/generate-go.mjs (do not edit by hand).
// Realistic Go typing blocks for vibetyper: geometry and matrix helpers.
package main

import (
	"math"
)

// Point is a 2D coordinate.
type Point struct {
	X float64
	Y float64
}

// Distance returns the Euclidean distance to another point.
func (p Point) Distance(other Point) float64 {
	dx := p.X - other.X
	dy := p.Y - other.Y
	return math.Sqrt(dx*dx + dy*dy)
}

// Midpoint returns the point halfway between p and other.
func (p Point) Midpoint(other Point) Point {
	return Point{X: (p.X + other.X) / 2, Y: (p.Y + other.Y) / 2}
}

// Rect is an axis-aligned rectangle.
type Rect struct {
	Min Point
	Max Point
}

// Contains reports whether p lies inside the rectangle, inclusive.
func (r Rect) Contains(p Point) bool {
	return p.X >= r.Min.X && p.X <= r.Max.X && p.Y >= r.Min.Y && p.Y <= r.Max.Y
}

// Area is the rectangle's width times height.
func (r Rect) Area() float64 {
	return (r.Max.X - r.Min.X) * (r.Max.Y - r.Min.Y)
}

// Circle is defined by a center point and a radius.
type Circle struct {
	Center Point
	Radius float64
}

// Area is pi times the radius squared.
func (c Circle) Area() float64 {
	return math.Pi * c.Radius * c.Radius
}

// Circumference is the distance around the circle.
func (c Circle) Circumference() float64 {
	return 2 * math.Pi * c.Radius
}

// Vec2 is a 2D vector.
type Vec2 struct {
	X float64
	Y float64
}

// Add returns the component-wise sum of two vectors.
func (v Vec2) Add(other Vec2) Vec2 {
	return Vec2{X: v.X + other.X, Y: v.Y + other.Y}
}

// Dot returns the scalar product of two vectors.
func (v Vec2) Dot(other Vec2) float64 {
	return v.X*other.X + v.Y*other.Y
}

// Length is the magnitude of the vector.
func (v Vec2) Length() float64 {
	return math.Hypot(v.X, v.Y)
}

// rotatePoint rotates p around the origin by the given angle in radians.
func rotatePoint(p Point, angle float64) Point {
	cos := math.Cos(angle)
	sin := math.Sin(angle)
	return Point{
		X: p.X*cos - p.Y*sin,
		Y: p.X*sin + p.Y*cos,
	}
}

// angleBetween returns the unsigned angle in radians between two vectors.
func angleBetween(a, b Vec2) float64 {
	denom := a.Length() * b.Length()
	if denom == 0 {
		return 0
	}
	return math.Acos(a.Dot(b) / denom)
}

// polygonArea computes the signed area of a polygon using the shoelace
// formula; the absolute value is the usual area.
func polygonArea(points []Point) float64 {
	n := len(points)
	if n < 3 {
		return 0
	}
	sum := 0.0
	for i := 0; i < n; i++ {
		j := (i + 1) % n
		sum += points[i].X*points[j].Y - points[j].X*points[i].Y
	}
	return sum / 2
}

// distanceToSegment returns the shortest distance from p to the segment
// between a and b.
func distanceToSegment(p, a, b Point) float64 {
	dx, dy := b.X-a.X, b.Y-a.Y
	if dx == 0 && dy == 0 {
		return p.Distance(a)
	}
	t := ((p.X-a.X)*dx + (p.Y-a.Y)*dy) / (dx*dx + dy*dy)
	if t < 0 {
		t = 0
	}
	if t > 1 {
		t = 1
	}
	closest := Point{X: a.X + t*dx, Y: a.Y + t*dy}
	return p.Distance(closest)
}

// matrixMultiply multiplies two matrices, returning nil when the inner
// dimensions do not agree.
func matrixMultiply(a, b [][]float64) [][]float64 {
	if len(a) == 0 || len(b) == 0 || len(a[0]) != len(b) {
		return nil
	}
	rows, inner, cols := len(a), len(b), len(b[0])
	out := make([][]float64, rows)
	for i := 0; i < rows; i++ {
		out[i] = make([]float64, cols)
		for k := 0; k < inner; k++ {
			for j := 0; j < cols; j++ {
				out[i][j] += a[i][k] * b[k][j]
			}
		}
	}
	return out
}

// matrixScale multiplies every element of a matrix by factor.
func matrixScale(m [][]float64, factor float64) [][]float64 {
	out := make([][]float64, len(m))
	for i, row := range m {
		out[i] = make([]float64, len(row))
		for j, v := range row {
			out[i][j] = v * factor
		}
	}
	return out
}

// determinant2x2 computes the determinant of a 2x2 matrix.
func determinant2x2(m [][]float64) float64 {
	return m[0][0]*m[1][1] - m[0][1]*m[1][0]
}

// clampAngle normalizes an angle in degrees to [0, 360).
func clampAngle(deg float64) float64 {
	deg = math.Mod(deg, 360)
	if deg < 0 {
		deg += 360
	}
	return deg
}
