// math_numeric.go — generated by scripts/generate/generate-go.mjs (do not edit by hand).
// Realistic Go typing blocks for vibetyper: math and numeric helpers.
package main

import (
	"math"
	"math/rand"
	"sort"
	"strconv"
	"strings"
)

// gcd returns the greatest common divisor of two integers using Euclid's
// algorithm.
func gcd(a, b int) int {
	for b != 0 {
		a, b = b, a%b
	}
	if a < 0 {
		return -a
	}
	return a
}

// lcm returns the least common multiple of two positive integers.
func lcm(a, b int) int {
	if a == 0 || b == 0 {
		return 0
	}
	return a / gcd(a, b) * b
}

// isPrime reports whether n is prime using trial division up to the square
// root of n.
func isPrime(n int) bool {
	if n < 2 {
		return false
	}
	for i := 2; i*i <= n; i++ {
		if n%i == 0 {
			return false
		}
	}
	return true
}

// primesUpTo returns every prime less than or equal to limit using the
// sieve of Eratosthenes.
func primesUpTo(limit int) []int {
	composite := make([]bool, limit+1)
	var primes []int
	for i := 2; i <= limit; i++ {
		if composite[i] {
			continue
		}
		primes = append(primes, i)
		for j := i * i; j <= limit; j += i {
			composite[j] = true
		}
	}
	return primes
}

// nthFibonacci returns the n-th Fibonacci number, 0-indexed.
func nthFibonacci(n int) int {
	if n < 2 {
		return n
	}
	a, b := 0, 1
	for i := 2; i <= n; i++ {
		a, b = b, a+b
	}
	return b
}

// factorial computes n! iteratively and returns 1 for n <= 1.
func factorial(n int) int {
	result := 1
	for i := 2; i <= n; i++ {
		result *= i
	}
	return result
}

// binomial computes C(n, k) with a multiplicative formula that avoids huge
// intermediate factorials.
func binomial(n, k int) int {
	if k < 0 || k > n {
		return 0
	}
	if k > n-k {
		k = n - k
	}
	result := 1
	for i := 1; i <= k; i++ {
		result = result * (n - k + i) / i
	}
	return result
}

// mean returns the arithmetic average of a slice of floats.
func mean(values []float64) float64 {
	if len(values) == 0 {
		return 0
	}
	sum := 0.0
	for _, v := range values {
		sum += v
	}
	return sum / float64(len(values))
}

// median returns the middle value of a sorted copy of values, or the average
// of the two middle values when the length is even.
func median(values []float64) float64 {
	if len(values) == 0 {
		return 0
	}
	sorted := append([]float64(nil), values...)
	sort.Float64s(sorted)
	mid := len(sorted) / 2
	if len(sorted)%2 == 1 {
		return sorted[mid]
	}
	return (sorted[mid-1] + sorted[mid]) / 2
}

// mode returns the most frequent value in a slice, using the first
// occurrence to break ties.
func mode(values []int) int {
	counts := make(map[int]int)
	best, bestCount := 0, 0
	for _, v := range values {
		counts[v]++
		if counts[v] > bestCount {
			best, bestCount = v, counts[v]
		}
	}
	return best
}

// variance computes the population variance of a sample of floats.
func variance(values []float64) float64 {
	if len(values) < 2 {
		return 0
	}
	m := mean(values)
	sum := 0.0
	for _, v := range values {
		diff := v - m
		sum += diff * diff
	}
	return sum / float64(len(values))
}

// stddev returns the population standard deviation of values.
func stddev(values []float64) float64 {
	return math.Sqrt(variance(values))
}

// clamp restricts value to the inclusive range [lo, hi].
func clamp(value, lo, hi int) int {
	if value < lo {
		return lo
	}
	if value > hi {
		return hi
	}
	return value
}

// lerp linearly interpolates between a and b by the factor t in [0, 1].
func lerp(a, b, t float64) float64 {
	return a + (b-a)*t
}

// roundTo rounds value to the nearest multiple of 10^-places.
func roundTo(value float64, places int) float64 {
	factor := math.Pow10(places)
	return math.Round(value*factor) / factor
}

// isPerfectSquare reports whether n is the square of an integer.
func isPerfectSquare(n int) bool {
	if n < 0 {
		return false
	}
	root := int(math.Sqrt(float64(n)))
	return root*root == n
}

// sumDigits adds up the decimal digits of a non-negative integer.
func sumDigits(n int) int {
	sum := 0
	for n > 0 {
		sum += n % 10
		n /= 10
	}
	return sum
}

// reverseNumber reverses the decimal digits of an integer, preserving sign.
func reverseNumber(n int) int {
	reversed := 0
	for n != 0 {
		reversed = reversed*10 + n%10
		n /= 10
	}
	return reversed
}

// isPalindromeNumber reports whether n reads the same forward and backward.
func isPalindromeNumber(n int) bool {
	if n < 0 {
		return false
	}
	return n == reverseNumber(n)
}

// primeFactors decomposes n into its prime factors in ascending order.
func primeFactors(n int) []int {
	var factors []int
	for d := 2; d*d <= n; d++ {
		for n%d == 0 {
			factors = append(factors, d)
			n /= d
		}
	}
	if n > 1 {
		factors = append(factors, n)
	}
	return factors
}

// nextPowerOfTwo returns the smallest power of two >= n, useful when sizing
// buffers and hash tables.
func nextPowerOfTwo(n int) int {
	p := 1
	for p < n {
		p <<= 1
	}
	return p
}

// collatzSteps counts how many steps n takes to reach 1 under the Collatz
// rule.
func collatzSteps(n int) int {
	steps := 0
	for n != 1 {
		if n%2 == 0 {
			n /= 2
		} else {
			n = 3*n + 1
		}
		steps++
	}
	return steps
}

// intToRoman converts an integer in [1, 3999] to Roman numerals.
func intToRoman(n int) string {
	values := []int{1000, 900, 500, 400, 100, 90, 50, 40, 10, 9, 5, 4, 1}
	symbols := []string{"M", "CM", "D", "CD", "C", "XC", "L", "XL", "X", "IX", "V", "IV", "I"}
	var b strings.Builder
	for i, v := range values {
		for n >= v {
			b.WriteString(symbols[i])
			n -= v
		}
	}
	return b.String()
}

// romanToInt parses a Roman numeral string into an integer.
func romanToInt(roman string) int {
	values := map[rune]int{'I': 1, 'V': 5, 'X': 10, 'L': 50, 'C': 100, 'D': 500, 'M': 1000}
	total := 0
	prev := 0
	for _, r := range roman {
		v := values[r]
		if v > prev {
			total += v - 2*prev
		} else {
			total += v
		}
		prev = v
	}
	return total
}

// toBase renders n as a string in the given base (2..36).
func toBase(n, base int) string {
	return strconv.FormatInt(int64(n), base)
}

// fromBase parses a string written in the given base (2..36).
func fromBase(s string, base int) (int, error) {
	v, err := strconv.ParseInt(s, base, 64)
	return int(v), err
}

// randIntRange returns a random integer in [lo, hi] inclusive.
func randIntRange(lo, hi int) int {
	if hi <= lo {
		return lo
	}
	return lo + rand.Intn(hi-lo+1)
}

// percentageOf computes what fraction of total value represents, as a
// percent rounded to one decimal place.
func percentageOf(value, total float64) float64 {
	if total == 0 {
		return 0
	}
	return roundTo(value/total*100, 1)
}

// digitCount returns the number of decimal digits in a non-negative integer.
func digitCount(n int) int {
	if n == 0 {
		return 1
	}
	count := 0
	for n > 0 {
		count++
		n /= 10
	}
	return count
}

// isPerfectNumber reports whether n equals the sum of its proper divisors.
func isPerfectNumber(n int) bool {
	if n < 2 {
		return false
	}
	sum := 1
	for d := 2; d*d <= n; d++ {
		if n%d == 0 {
			sum += d
			if d != n/d {
				sum += n / d
			}
		}
	}
	return sum == n
}
