// networking_utils.go — generated by scripts/generate/generate-go.mjs (do not edit by hand).
// Realistic Go typing blocks for vibetyper: networking and URL helpers.
package main

import (
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/url"
	"strings"
	"time"
)

// parseURLParts splits a URL into its scheme, host, path and query string.
func parseURLParts(raw string) (scheme, host, path, query string, err error) {
	u, err := url.Parse(raw)
	if err != nil {
		return "", "", "", "", err
	}
	return u.Scheme, u.Host, u.Path, u.RawQuery, nil
}

// queryParams parses a raw query string into a multimap of values.
func queryParams(rawQuery string) (map[string][]string, error) {
	values, err := url.ParseQuery(rawQuery)
	if err != nil {
		return nil, err
	}
	return values, nil
}

// buildQueryString renders a parameter map as an encoded query string.
func buildQueryString(params map[string]string) string {
	values := url.Values{}
	for key, value := range params {
		values.Set(key, value)
	}
	return values.Encode()
}

// httpGetWithTimeout fetches a URL with a client-level timeout, returning
// the response body and status code.
func httpGetWithTimeout(target string, timeout time.Duration) (string, int, error) {
	client := &http.Client{Timeout: timeout}
	resp, err := client.Get(target)
	if err != nil {
		return "", 0, err
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", resp.StatusCode, err
	}
	return string(body), resp.StatusCode, nil
}

// retryRequest retries fn up to attempts times, waiting an exponentially
// growing backoff between failures. fn reports success as its first result.
func retryRequest(attempts int, backoff time.Duration, fn func() (bool, error)) error {
	var err error
	for i := 0; i < attempts; i++ {
		var ok bool
		ok, err = fn()
		if ok {
			return nil
		}
		if i < attempts-1 {
			time.Sleep(backoff)
			backoff *= 2
		}
	}
	if err == nil {
		err = fmt.Errorf("operation failed after %d attempts", attempts)
	}
	return err
}

// basicAuthHeader builds the Authorization header value for HTTP Basic
// auth.
func basicAuthHeader(username, password string) string {
	joined := username + ":" + password
	return "Basic " + base64.StdEncoding.EncodeToString([]byte(joined))
}

// splitHostPort separates "host:port" into its parts, defaulting the port
// when missing.
func splitHostPort(address string, defaultPort string) (string, string, error) {
	host, port, err := net.SplitHostPort(address)
	if err != nil {
		if strings.Count(address, ":") == 0 {
			return address, defaultPort, nil
		}
		return "", "", err
	}
	return host, port, nil
}

// parseCookies converts a raw Cookie header into a name -> value map.
func parseCookies(header string) map[string]string {
	out := make(map[string]string)
	for _, part := range strings.Split(header, ";") {
		part = strings.TrimSpace(part)
		eq := strings.Index(part, "=")
		if eq <= 0 {
			continue
		}
		out[strings.TrimSpace(part[:eq])] = strings.TrimSpace(part[eq+1:])
	}
	return out
}

// ipInCIDR reports whether address falls inside the given CIDR range.
func ipInCIDR(address, cidr string) bool {
	ip := net.ParseIP(address)
	_, network, err := net.ParseCIDR(cidr)
	if err != nil {
		return false
	}
	return network.Contains(ip)
}

// defaultPort returns the conventional port for common URL schemes.
func defaultPort(scheme string) string {
	switch scheme {
	case "http":
		return "80"
	case "https":
		return "443"
	case "ftp":
		return "21"
	case "ssh":
		return "22"
	case "smtp":
		return "25"
	default:
		return ""
	}
}

// isReachable reports whether a TCP connection can be established to the
// address within the timeout.
func isReachable(address string, timeout time.Duration) bool {
	conn, err := net.DialTimeout("tcp", address, timeout)
	if err != nil {
		return false
	}
	conn.Close()
	return true
}

// normalizeURL ensures a URL has a scheme and a lowercase host.
func normalizeURL(raw string) string {
	u, err := url.Parse(raw)
	if err != nil {
		return raw
	}
	if u.Scheme == "" {
		u.Scheme = "http"
	}
	u.Host = strings.ToLower(u.Host)
	return u.String()
}

// queryValue returns the first value of key in a URL's query string.
func queryValue(raw, key string) (string, bool) {
	u, err := url.Parse(raw)
	if err != nil {
		return "", false
	}
	values, err := url.ParseQuery(u.RawQuery)
	if err != nil {
		return "", false
	}
	if len(values[key]) == 0 {
		return "", false
	}
	return values[key][0], true
}

// httpStatusText maps common HTTP status codes to their reason phrases.
func httpStatusText(code int) string {
	switch code {
	case 200:
		return "OK"
	case 201:
		return "Created"
	case 204:
		return "No Content"
	case 301:
		return "Moved Permanently"
	case 304:
		return "Not Modified"
	case 400:
		return "Bad Request"
	case 401:
		return "Unauthorized"
	case 403:
		return "Forbidden"
	case 404:
		return "Not Found"
	case 409:
		return "Conflict"
	case 422:
		return "Unprocessable Entity"
	case 429:
		return "Too Many Requests"
	case 500:
		return "Internal Server Error"
	case 502:
		return "Bad Gateway"
	case 503:
		return "Service Unavailable"
	default:
		return ""
	}
}

// urlEncode percent-encodes a string for safe use in URLs.
func urlEncode(value string) string {
	return url.QueryEscape(value)
}

// redactURL strips the query string and fragment from a URL for safe
// logging.
func redactURL(raw string) string {
	u, err := url.Parse(raw)
	if err != nil {
		return raw
	}
	u.RawQuery = ""
	u.Fragment = ""
	return u.String()
}

// headersToMap parses "Key: value" header lines into a map.
func headersToMap(lines []string) map[string]string {
	out := make(map[string]string)
	for _, line := range lines {
		colon := strings.Index(line, ":")
		if colon <= 0 {
			continue
		}
		key := strings.TrimSpace(line[:colon])
		value := strings.TrimSpace(line[colon+1:])
		out[key] = value
	}
	return out
}

// lookupHost resolves host to its IP addresses.
func lookupHost(host string) ([]string, error) {
	addrs, err := net.LookupHost(host)
	if err != nil {
		return nil, err
	}
	return addrs, nil
}

// isHTTPS reports whether a raw URL uses the https scheme.
func isHTTPS(raw string) bool {
	u, err := url.Parse(raw)
	return err == nil && u.Scheme == "https"
}

// fetchJSON performs a GET request and decodes the JSON response body.
func fetchJSON(target string, timeout time.Duration, out any) error {
	client := &http.Client{Timeout: timeout}
	resp, err := client.Get(target)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("GET %s: status %d", target, resp.StatusCode)
	}
	return json.NewDecoder(resp.Body).Decode(out)
}
