// string_utils.go — generated by scripts/generate/generate-go.mjs (do not edit by hand).
// Realistic Go typing blocks for vibetyper: string utilities.
package main

import (
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

// slugify converts arbitrary text into a lowercase, hyphen-separated slug
// suitable for URLs and filenames.
func slugify(text string) string {
	text = strings.ToLower(strings.TrimSpace(text))
	var b strings.Builder
	lastDash := false
	for _, r := range text {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
			lastDash = false
		default:
			if !lastDash && b.Len() > 0 {
				b.WriteByte('-')
				lastDash = true
			}
		}
	}
	return strings.Trim(b.String(), "-")
}

// camelCase converts space-, underscore- or dash-separated words into
// lowerCamelCase.
func camelCase(text string) string {
	words := strings.FieldsFunc(text, func(r rune) bool {
		return r == ' ' || r == '_' || r == '-'
	})
	var b strings.Builder
	for i, w := range words {
		if i == 0 {
			b.WriteString(strings.ToLower(w))
			continue
		}
		b.WriteString(strings.ToUpper(w[:1]))
		b.WriteString(strings.ToLower(w[1:]))
	}
	return b.String()
}

// pascalCase converts words into UpperCamelCase, e.g. "user profile"
// becomes "UserProfile".
func pascalCase(text string) string {
	words := strings.Fields(text)
	var b strings.Builder
	for _, w := range words {
		b.WriteString(strings.ToUpper(w[:1]))
		b.WriteString(strings.ToLower(w[1:]))
	}
	return b.String()
}

// snakeCase converts any mixed-separator text into snake_case, inserting
// underscores between words and before capitals.
func snakeCase(text string) string {
	var b strings.Builder
	prevUpper := false
	for _, r := range text {
		upper := unicode.IsUpper(r)
		if r == ' ' || r == '-' || r == '_' {
			if b.Len() > 0 && !strings.HasSuffix(b.String(), "_") {
				b.WriteByte('_')
			}
			prevUpper = false
			continue
		}
		if upper && b.Len() > 0 && !prevUpper {
			b.WriteByte('_')
		}
		b.WriteRune(unicode.ToLower(r))
		prevUpper = upper
	}
	return b.String()
}

// truncateWords cuts text at a word boundary so the result is at most max
// bytes long, appending an ellipsis when anything was removed.
func truncateWords(text string, max int) string {
	if len(text) <= max {
		return text
	}
	cut := text[:max]
	if i := strings.LastIndex(cut, " "); i > 0 {
		cut = cut[:i]
	}
	return strings.TrimSpace(cut) + "..."
}

// padLeft pads a string on the left with the given fill character until it
// reaches the requested width in runes.
func padLeft(text string, width int, fill rune) string {
	missing := width - utf8.RuneCountInString(text)
	if missing <= 0 {
		return text
	}
	return strings.Repeat(string(fill), missing) + text
}

// padRight appends a fill character until the string reaches the requested
// width in runes.
func padRight(text string, width int, fill rune) string {
	missing := width - utf8.RuneCountInString(text)
	if missing <= 0 {
		return text
	}
	return text + strings.Repeat(string(fill), missing)
}

// levenshtein computes the edit distance between two strings using the
// classic dynamic-programming row optimization.
func levenshtein(a, b string) int {
	ar, br := []rune(a), []rune(b)
	prev := make([]int, len(br)+1)
	curr := make([]int, len(br)+1)
	for j := range prev {
		prev[j] = j
	}
	for i, ca := range ar {
		curr[0] = i + 1
		for j, cb := range br {
			cost := 0
			if ca != cb {
				cost = 1
			}
			curr[j+1] = min3(prev[j+1]+1, curr[j]+1, prev[j]+cost)
		}
		prev, curr = curr, prev
	}
	return prev[len(br)]
}

// min3 returns the smallest of three integers.
func min3(a, b, c int) int {
	if b < a {
		a = b
	}
	if c < a {
		a = c
	}
	return a
}

// isAnagram reports whether two strings contain exactly the same runes.
func isAnagram(a, b string) bool {
	if len(a) != len(b) {
		return false
	}
	counts := make(map[rune]int)
	for _, r := range a {
		counts[r]++
	}
	for _, r := range b {
		counts[r]--
		if counts[r] < 0 {
			return false
		}
	}
	return true
}

// reverseRunes returns a new string with the runes in reverse order,
// preserving multi-byte characters.
func reverseRunes(text string) string {
	runes := []rune(text)
	for i, j := 0, len(runes)-1; i < j; i, j = i+1, j-1 {
		runes[i], runes[j] = runes[j], runes[i]
	}
	return string(runes)
}

// countWords returns the number of whitespace-separated words in text.
func countWords(text string) int {
	return len(strings.Fields(text))
}

// initials extracts the first letter of every word, useful for building
// avatar labels from a full name.
func initials(fullName string) string {
	words := strings.Fields(fullName)
	if len(words) == 0 {
		return "?"
	}
	var b strings.Builder
	for _, w := range words {
		r, _ := utf8.DecodeRuneInString(w)
		b.WriteRune(unicode.ToUpper(r))
	}
	return b.String()
}

var htmlTagRe = regexp.MustCompile("<[^>]*>")

// stripHTMLTags removes every HTML tag from a document, leaving the text.
func stripHTMLTags(html string) string {
	return htmlTagRe.ReplaceAllString(html, "")
}

// sanitizeFilename replaces characters that are unsafe in filenames with
// underscores and collapses whitespace runs.
func sanitizeFilename(name string) string {
	name = strings.Map(func(r rune) rune {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9',
			r == '-', r == '_', r == '.', r == ' ':
			return r
		}
		return '_'
	}, name)
	return strings.Join(strings.Fields(name), " ")
}

// replaceLast replaces the final occurrence of old in text, if present.
func replaceLast(text, old, replacement string) string {
	i := strings.LastIndex(text, old)
	if i == -1 {
		return text
	}
	return text[:i] + replacement + text[i+len(old):]
}

// splitCamelCase inserts a space before each capital letter, so
// "maxConnections" becomes "max Connections".
func splitCamelCase(text string) string {
	var b strings.Builder
	for i, r := range text {
		if unicode.IsUpper(r) && i > 0 {
			b.WriteByte(' ')
		}
		b.WriteRune(r)
	}
	return b.String()
}

// extractNumbers pulls every integer literal out of a string, in order.
func extractNumbers(text string) []int {
	var nums []int
	var current strings.Builder
	flush := func() {
		if current.Len() > 0 {
			if n, err := strconv.Atoi(current.String()); err == nil {
				nums = append(nums, n)
			}
			current.Reset()
		}
	}
	for _, r := range text {
		if r >= '0' && r <= '9' {
			current.WriteRune(r)
		} else {
			flush()
		}
	}
	flush()
	return nums
}

// commonPrefix returns the longest prefix shared by every string in a slice.
func commonPrefix(words []string) string {
	if len(words) == 0 {
		return ""
	}
	prefix := words[0]
	for _, w := range words[1:] {
		for !strings.HasPrefix(w, prefix) {
			prefix = prefix[:len(prefix)-1]
			if prefix == "" {
				return ""
			}
		}
	}
	return prefix
}

// titleCase capitalizes the first letter of every word while lowercasing the
// rest, e.g. "the QUICK fox" becomes "The Quick Fox".
func titleCase(text string) string {
	words := strings.Fields(text)
	for i, w := range words {
		r, size := utf8.DecodeRuneInString(w)
		words[i] = string(unicode.ToUpper(r)) + strings.ToLower(w[size:])
	}
	return strings.Join(words, " ")
}

// indentLines prepends the given prefix to every line of a block of text.
func indentLines(text, prefix string) string {
	return prefix + strings.ReplaceAll(text, "\n", "\n"+prefix)
}

// wrapText breaks text into lines of at most width characters, preserving
// whole words where possible.
func wrapText(text string, width int) []string {
	words := strings.Fields(text)
	if len(words) == 0 {
		return nil
	}
	var lines []string
	line := words[0]
	for _, w := range words[1:] {
		if len(line)+1+len(w) > width {
			lines = append(lines, line)
			line = w
		} else {
			line += " " + w
		}
	}
	return append(lines, line)
}

// joinNonEmpty joins items with a separator, skipping blank entries.
func joinNonEmpty(items []string, sep string) string {
	var kept []string
	for _, item := range items {
		if strings.TrimSpace(item) != "" {
			kept = append(kept, item)
		}
	}
	return strings.Join(kept, sep)
}

// humanizeKey turns a snake_case or dash-separated key into readable title
// text, e.g. "billing_address" becomes "Billing Address".
func humanizeKey(key string) string {
	key = strings.ReplaceAll(key, "_", " ")
	key = strings.ReplaceAll(key, "-", " ")
	var b strings.Builder
	prevSpace := true
	for _, r := range key {
		if r == ' ' {
			b.WriteByte(' ')
			prevSpace = true
			continue
		}
		if prevSpace {
			b.WriteRune(unicode.ToUpper(r))
			prevSpace = false
		} else {
			b.WriteRune(unicode.ToLower(r))
		}
	}
	return strings.TrimSpace(b.String())
}

// uniqueLines returns the lines of text in first-seen order, dropping
// duplicates.
func uniqueLines(text string) []string {
	seen := make(map[string]bool)
	var out []string
	for _, line := range strings.Split(text, "\n") {
		line = strings.TrimRight(line, "\r")
		if !seen[line] {
			seen[line] = true
			out = append(out, line)
		}
	}
	return out
}

// caesarShift rotates every ASCII letter by shift positions, wrapping around
// the alphabet and leaving all other characters untouched.
func caesarShift(text string, shift int) string {
	shift = ((shift % 26) + 26) % 26
	var b strings.Builder
	for _, r := range text {
		switch {
		case r >= 'a' && r <= 'z':
			b.WriteRune('a' + (r-'a'+rune(shift))%26)
		case r >= 'A' && r <= 'Z':
			b.WriteRune('A' + (r-'A'+rune(shift))%26)
		default:
			b.WriteRune(r)
		}
	}
	return b.String()
}

// maskMiddle hides the middle of a string, keeping only the first and last
// few characters, e.g. for account numbers and API tokens.
func maskMiddle(text string, keepStart, keepEnd int) string {
	runes := []rune(text)
	if len(runes) <= keepStart+keepEnd {
		return strings.Repeat("*", len(runes))
	}
	var b strings.Builder
	b.WriteString(string(runes[:keepStart]))
	b.WriteString(strings.Repeat("*", len(runes)-keepStart-keepEnd))
	b.WriteString(string(runes[len(runes)-keepEnd:]))
	return b.String()
}

// normalizeWhitespace collapses runs of whitespace into single spaces and
// trims the ends, handy when parsing pasted input.
func normalizeWhitespace(text string) string {
	return strings.Join(strings.Fields(text), " ")
}

var emailRe = regexp.MustCompile("[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}")

// extractEmails finds every email address embedded in a blob of text.
func extractEmails(text string) []string {
	return emailRe.FindAllString(text, -1)
}

// formatPhone renders a 10-digit US phone number as (555) 123-4567.
func formatPhone(digits string) string {
	digits = strings.Map(func(r rune) rune {
		if r >= '0' && r <= '9' {
			return r
		}
		return -1
	}, digits)
	if len(digits) != 10 {
		return digits
	}
	return fmt.Sprintf("(%s) %s-%s", digits[:3], digits[3:6], digits[6:])
}

// sortedLines returns the non-empty lines of text sorted lexicographically.
func sortedLines(text string) []string {
	var lines []string
	for _, line := range strings.Split(text, "\n") {
		if trimmed := strings.TrimSpace(line); trimmed != "" {
			lines = append(lines, trimmed)
		}
	}
	sort.Strings(lines)
	return lines
}
