// validation_utils.go — generated by scripts/generate/generate-go.mjs (do not edit by hand).
// Realistic Go typing blocks for vibetyper: input validation helpers.
package main

import (
	"encoding/base64"
	"net"
	"net/url"
	"regexp"
	"unicode"
)

var emailCheckRe = regexp.MustCompile("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$")

// isValidEmail reports whether s looks like a plausible email address.
func isValidEmail(s string) bool {
	if len(s) > 254 {
		return false
	}
	return emailCheckRe.MatchString(s)
}

// isValidURL reports whether s parses as an absolute http(s) URL.
func isValidURL(s string) bool {
	u, err := url.Parse(s)
	if err != nil {
		return false
	}
	return u.IsAbs() && (u.Scheme == "http" || u.Scheme == "https")
}

// isValidIP reports whether s is a valid IPv4 or IPv6 address.
func isValidIP(s string) bool {
	return net.ParseIP(s) != nil
}

// isPrivateIP reports whether s is a private, loopback or link-local
// address.
func isPrivateIP(s string) bool {
	ip := net.ParseIP(s)
	if ip == nil {
		return false
	}
	return ip.IsPrivate() || ip.IsLoopback() || ip.IsLinkLocalUnicast()
}

// isValidPort reports whether port is a valid TCP/UDP port number.
func isValidPort(port int) bool {
	return port >= 1 && port <= 65535
}

var hostnameRe = regexp.MustCompile("^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(\\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$")

// isValidHostname reports whether s is a well-formed DNS hostname.
func isValidHostname(s string) bool {
	return len(s) <= 253 && hostnameRe.MatchString(s)
}

// luhnValid checks a card number (or any numeric string) against the Luhn
// checksum used by most payment cards.
func luhnValid(number string) bool {
	sum := 0
	double := false
	for i := len(number) - 1; i >= 0; i-- {
		d := int(number[i] - '0')
		if d < 0 || d > 9 {
			return false
		}
		if double {
			d *= 2
			if d > 9 {
				d -= 9
			}
		}
		sum += d
		double = !double
	}
	return sum%10 == 0
}

var hexColorRe = regexp.MustCompile("^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$")

// isValidHexColor reports whether s is a #RGB or #RRGGBB color.
func isValidHexColor(s string) bool {
	return hexColorRe.MatchString(s)
}

var uuidRe = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// isValidUUID reports whether s is a canonical hyphenated UUID.
func isValidUUID(s string) bool {
	return uuidRe.MatchString(s)
}

var semverRe = regexp.MustCompile("^v?\\d+\\.\\d+\\.\\d+(-[0-9A-Za-z.-]+)?(\\+[0-9A-Za-z.-]+)?$")

// isValidSemver reports whether s looks like a semantic version string.
func isValidSemver(s string) bool {
	return semverRe.MatchString(s)
}

var slugRe = regexp.MustCompile("^[a-z0-9]+(?:-[a-z0-9]+)*$")

// isValidSlug reports whether s is a lowercase hyphen-separated slug.
func isValidSlug(s string) bool {
	return slugRe.MatchString(s)
}

// isValidISBN13 validates a 13-digit ISBN using its checksum digit.
func isValidISBN13(isbn string) bool {
	digits := make([]int, 0, 13)
	for _, r := range isbn {
		if r == '-' {
			continue
		}
		if r < '0' || r > '9' {
			return false
		}
		digits = append(digits, int(r-'0'))
	}
	if len(digits) != 13 {
		return false
	}
	sum := 0
	for i, d := range digits {
		if i%2 == 0 {
			sum += d
		} else {
			sum += d * 3
		}
	}
	return sum%10 == 0
}

// isValidISBN10 validates a 10-digit ISBN, accepting an X check digit.
func isValidISBN10(isbn string) bool {
	digits := make([]int, 0, 10)
	for _, r := range isbn {
		if r == '-' {
			continue
		}
		if r == 'X' || r == 'x' {
			if len(digits) != 9 {
				return false
			}
			digits = append(digits, 10)
			continue
		}
		if r < '0' || r > '9' {
			return false
		}
		digits = append(digits, int(r-'0'))
	}
	if len(digits) != 10 {
		return false
	}
	sum := 0
	for i, d := range digits {
		sum += d * (10 - i)
	}
	return sum%11 == 0
}

// isStrongPassword requires at least 8 characters and three of the four
// character classes.
func isStrongPassword(s string) bool {
	if len(s) < 8 {
		return false
	}
	classes := 0
	for _, check := range []func(string) bool{hasLowercase, hasUppercase, hasDigit, hasSymbol} {
		if check(s) {
			classes++
		}
	}
	return classes >= 3
}

// hasLowercase reports whether s contains at least one lowercase letter.
func hasLowercase(s string) bool {
	for _, r := range s {
		if unicode.IsLower(r) {
			return true
		}
	}
	return false
}

// hasUppercase reports whether s contains at least one uppercase letter.
func hasUppercase(s string) bool {
	for _, r := range s {
		if unicode.IsUpper(r) {
			return true
		}
	}
	return false
}

// hasDigit reports whether s contains at least one decimal digit.
func hasDigit(s string) bool {
	for _, r := range s {
		if unicode.IsDigit(r) {
			return true
		}
	}
	return false
}

// hasSymbol reports whether s contains at least one non-alphanumeric symbol.
func hasSymbol(s string) bool {
	for _, r := range s {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) && !unicode.IsSpace(r) {
			return true
		}
	}
	return false
}

// isBalancedBrackets verifies that (), [] and {} pairs are correctly
// nested.
func isBalancedBrackets(text string) bool {
	var stack []rune
	pairs := map[rune]rune{')': '(', ']': '[', '}': '{'}
	for _, r := range text {
		switch r {
		case '(', '[', '{':
			stack = append(stack, r)
		case ')', ']', '}':
			if len(stack) == 0 || stack[len(stack)-1] != pairs[r] {
				return false
			}
			stack = stack[:len(stack)-1]
		}
	}
	return len(stack) == 0
}

// isValidBase64 reports whether s decodes as standard base64.
func isValidBase64(s string) bool {
	_, err := base64.StdEncoding.DecodeString(s)
	return err == nil
}

var phoneRe = regexp.MustCompile("^\\+?[0-9][0-9\\s().-]{6,19}$")

// isValidPhoneNumber accepts common international phone formats.
func isValidPhoneNumber(s string) bool {
	return phoneRe.MatchString(s)
}

// isAllDigits reports whether every rune in s is a decimal digit.
func isAllDigits(s string) bool {
	if s == "" {
		return false
	}
	for _, r := range s {
		if r < '0' || r > '9' {
			return false
		}
	}
	return true
}
